var s_iOffsetX=0,s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var g=a.toLowerCase(),c=window.document,f=c.documentElement;if(void 0===window["inner"+a])a=f["client"+a];else if(window["inner"+a]!=f["client"+a]){var h=c.createElement("body");h.id="vpw-test-b";h.style.cssText="overflow:scroll";var d=c.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+g+":"+f["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";h.appendChild(d);f.insertBefore(h,c.head);
a=7==d["offset"+a]?f["client"+a]:window["inner"+a];f.removeChild(h)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var g=getSize("Width");s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,g/CANVAS_WIDTH);var c=CANVAS_WIDTH*s_iScaleFactor,f=CANVAS_HEIGHT*s_iScaleFactor,h;f<a?(h=a-f,f+=h,c+=CANVAS_WIDTH/CANVAS_HEIGHT*h):c<g&&(h=g-c,c+=h,f+=CANVAS_HEIGHT/CANVAS_WIDTH*h);h=a/2-f/2;var d=g/2-c/2,e=CANVAS_WIDTH/c;if(d*e<-EDGEBOARD_X||h*e<-EDGEBOARD_Y)s_iScaleFactor=Math.min(a/
(CANVAS_HEIGHT-2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*s_iScaleFactor,f=CANVAS_HEIGHT*s_iScaleFactor,h=(a-f)/2,d=(g-c)/2,e=CANVAS_WIDTH/c;s_iOffsetX=-1*d*e;s_iOffsetY=-1*h*e;0<=h&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",c+"px");$("#canvas").css("height",f+"px");0>h?$("#canvas").css("top",h+"px"):$("#canvas").css("top",
"0px");$("#canvas").css("left",d+"px")}}function createBitmap(a,g,c){var f=new createjs.Bitmap(a),h=new createjs.Shape;g&&c?h.graphics.beginFill("#fff").drawRect(-g/2,-c/2,g,c):h.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);f.hitArea=h;return f}function createSprite(a,g,c,f,h,d){a=null!==g?new createjs.Sprite(a,g):new createjs.Sprite(a);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-c,-f,h,d);a.hitArea=g;return a}
function randomFloatBetween(a,g,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(g-a),g).toFixed(c))}function shuffle(a){for(var g=a.length,c,f;0!==g;)f=Math.floor(Math.random()*g),--g,c=a[g],a[g]=a[f],a[f]=c;return a}function formatTime(a){a/=1E3;var g=Math.floor(a/60);a=parseFloat(a-60*g).toFixed(1);var c="",c=10>g?c+("0"+g+":"):c+(g+":");return 10>a?c+("0"+a):c+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,g){var c,f;c=getBounds(a,.9);f=getBounds(g,.98);return calculateIntersection(c,f)}function calculateIntersection(a,g){var c,f,h,d,e,m,b,p;c=a.x+(h=a.width/2);f=a.y+(d=a.height/2);e=g.x+(m=g.width/2);b=g.y+(p=g.height/2);c=Math.abs(c-e)-(h+m);f=Math.abs(f-b)-(d+p);return 0>c&&0>f?(c=Math.min(Math.min(a.width,g.width),-c),f=Math.min(Math.min(a.height,g.height),-f),{x:Math.max(a.x,g.x),y:Math.max(a.y,g.y),width:c,height:f,rect1:a,rect2:g}):null}
function getBounds(a,g){var c={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var f=a.children,h=f.length,d,e;for(e=0;e<h;e++)d=getBounds(f[e],1),d.x<c.x&&(c.x=d.x),d.y<c.y&&(c.y=d.y),d.x+d.width>c.x2&&(c.x2=d.x+d.width),d.y+d.height>c.y2&&(c.y2=d.y+d.height);Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{var m,b;a instanceof createjs.Bitmap?
(h=a.sourceRect||a.image,e=h.width*g,m=h.height*g):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(h=a.spriteSheet.getFrame(a.currentFrame),e=h.rect.width,m=h.rect.height,f=h.regX,b=h.regY):(c.x=a.x||0,c.y=a.y||0):(c.x=a.x||0,c.y=a.y||0);f=f||0;e=e||0;b=b||0;m=m||0;c.regX=f;c.regY=b;h=a.localToGlobal(0-f,0-b);d=a.localToGlobal(e-f,m-b);e=a.localToGlobal(e-f,0-b);f=a.localToGlobal(0-f,m-b);c.x=Math.min(Math.min(Math.min(h.x,
d.x),e.x),f.x);c.y=Math.min(Math.min(Math.min(h.y,d.y),e.y),f.y);c.width=Math.max(Math.max(Math.max(h.x,d.x),e.x),f.x)-c.x;c.height=Math.max(Math.max(Math.max(h.y,d.y),e.y),f.y)-c.y}return c}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);a.dispatchEvent(g)}}};
(function(){function a(a){var f={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in f?document.body.className=f[a.type]:(document.body.className=this[g]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var g="hidden";g in document?document.addEventListener("visibilitychange",a):(g="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(g="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(g="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,g,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:c,volume:g}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,g){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=g}function setMute(a,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(g)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var g=window.location.search.substring(1).split("&"),c=0;c<g.length;c++){var f=g[c].split("=");if(f[0]==a)return f[1]}}function distanceV2(a,g){var c=a.x-g.x,f=a.y-g.y;return c*c+f*f}
function collisionRect(a,g){return a.x<g.x+g.width&&a.x+a.width>g.x&&a.y<g.y+g.height&&a.y+a.height>g.y?!0:!1}function saveItem(a,g){localStorage.setItem(a,g)}function getItem(a){return localStorage.getItem(a)}function clearAllItem(){localStorage.clear()}
function CSpriteLibrary(){var a,g,c,f,h,d;this.init=function(e,m,b){c=g=0;f=e;h=m;d=b;a={}};this.addSprite=function(e,d){a.hasOwnProperty(e)||(a[e]={szPath:d,oSprite:new Image},g++)};this.getSprite=function(e){return a.hasOwnProperty(e)?a[e].oSprite:null};this._onSpritesLoaded=function(){h.call(d)};this._onSpriteLoaded=function(){f.call(d);++c==g&&this._onSpritesLoaded()};this.loadSprites=function(){for(var e in a)a[e].oSprite.oSpriteLibrary=this,a[e].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[e].oSprite.src=a[e].szPath};this.getNumSprites=function(){return g}}
var CANVAS_WIDTH=1360,CANVAS_HEIGHT=540,EDGEBOARD_X=300,EDGEBOARD_Y=100,FPS=30,DISABLE_SOUND_MOBILE=!1,FONT_GAME="rocks__gregular",TEXT_COLOR="#e6a900",CONFIRMATION_EXIT=0,CONFIRMATION_RESET=1,FPS_TIME=1E3/FPS,URL_LEVELS_SETTINGS="json/levels_settings.json",OFFSET_PLATFORM_COL_DIMENSION=[{x:6,y:8},{x:6,y:8}],OFFSET_PLATFORM_COL_POINT=[{x:2,y:6},{x:2,y:6}],OFFSET_HEIGHT_PLATFORM_CHRACTER=26,OFFSET_PLAYER_COL_DIMENSION={x:-55,y:-67},OFFSET_PLAYER_COL_POINT={x:70,y:50},TOLLERANCE_Y_FOR_ANIMATION=100,
PLATFORM_Y_START=120,LOGO_Y_POS=.5*CANVAS_HEIGHT-80,FIRST_PLATFORM_X=250,LAST_PLATFORM_X=.2*CANVAS_WIDTH,PARALLAXE_OBJ_X_RANDOMIZE=-150,PARALLAXE_OBJ_X_REPOS=CANVAS_WIDTH+150,MAX_POS_X_RANDOM_PARALLAXE=150,MAX_SCALE_PARALLAXE=1,MIN_SCALE_PARALLAXE=.6,PARALLAXE_Y_POS_ICE=440,PARALLAXE_Y_POS_VM=540,MAX_NUM_PARALLAXE=3,FALL_LIMIT_Y=CANVAS_HEIGHT+100,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,SEA_NUMBER=2,POSITION_Y_SEA=490,NUMBER_OF_STARS=3,STARS_POSITION=[{x:700,y:216},{x:754,y:216},{x:809,
y:216}],SHOW_COLLISION_SHAPE=!1,SCALE_STAR_FACTOR=1.2,OFFSET_RECT_ARRIVAL={x:10,y:150},OFFSET_ARRIVAL_POS={x:0,y:5},GAME_STATE_HELP=0,GAME_STATE_PLAY=1,GAME_STATE_FINISH=2,GAME_STATE_GAMEOVER=3,COLLISION_PLATFORM=0,COLLISION_WALL=1,COLLISION_NOTHING=2,COLLISION_ARRIVAL=3,PREVIEW_COLLISION=4,DECREASE_FACTOR_VOL_GAME_COMPLETED=.95,DECREASE_FACTOR_VOL_LEVEL_COMPLETED=.85,OFFSET_HEIGHT_COLLISION_PLATFORM=-2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_BUT_NO_DOWN=
6,ON_BUT_YES_DOWN=7,ON_CONTROLLER_END=8,ON_CONTROLLER_REMOVE=9,ON_CONTROLLER_ROLL=10,EASE_CUBIC_OUT=1,WEIGHT_ARRIVAL=92,ON_VISIBLE_X=CANVAS_WIDTH+20,PLATFORM_SPEED,NUM_LEVEL_FOR_ADS,PERCENTAGE_STARS;TEXT_GAMEOVER="GAME OVER";TEXT_COMMANDS="CONTROLS";TEXT_ALL_COMPLETE="ALL LEVEL COMPLETE";TEXT_SELECT_A_LEVEL="SELECT A LEVEL";TEXT_CREDITS_DEVELOPED="Developed by";TEXT_LINK1="www.codethislab.com";TEXT_SCORES="SCORES";TEXT_TOTAL_SCORE="TOTAL SCORE";TEXT_CONGRATULATIONS="CONGRATULATIONS !";
TEXT_PAUSE="PAUSE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_SCORE="SCORE";TEXT_LEVEL_COMPLETED="LEVEL COMPLETED!!!";TEXT_GAME_COMPLETED="GAME COMPLETED";TEXT_FINAL_SCORE="FINAL SCORE";TEXT_HELP_INPUT="JUMP";TEXT_HELP_COIN="COLLECT";TEXT_HELP_SPIKE="AVOID";TEXT_RESET="ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!";TEXT_LEVEL="LEVEL";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,g,c,f,h,d,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));e.addChild(m);m=s_oSpriteLibrary.getSprite("progress_bar");f=createBitmap(m);f.x=CANVAS_WIDTH/2-m.width/2;f.y=CANVAS_HEIGHT-200;e.addChild(f);a=m.width;g=m.height;h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,1,g);e.addChild(h);f.mask=
h;c=new createjs.Text("","30px "+FONT_GAME,TEXT_COLOR);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-200;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";e.addChild(c);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;e.addChild(d)};this.refreshLoader=function(e){c.text=e+"%";h.graphics.clear();e=Math.floor(e*a/100);h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,e,g)};this._init()}
function CMain(a){var g,c=0,f=0,h=STATE_LOADING,d,e,m;this.initContainer=function(){var b=document.getElementById("canvas");s_oStage=new createjs.Stage(b);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;b.opacity=.5;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(b){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;s_oTweenController=new CTweenController;e=new CPreloader;g=!0};this.soundLoaded=function(){c++;e.refreshLoader(Math.floor(c/f*100));if(c===f){e.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/broken_stone.ogg","broken_stone"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/coin.ogg","coin"),createjs.Sound.registerSound("./sounds/game_completed.ogg","game_completed"),createjs.Sound.registerSound("./sounds/hero_falling.ogg",
"hero_falling"),createjs.Sound.registerSound("./sounds/hit_axe.ogg","hit_axe"),createjs.Sound.registerSound("./sounds/jump.ogg","jump"),createjs.Sound.registerSound("./sounds/level_completed.ogg","level_completed"),createjs.Sound.registerSound("./sounds/splash.ogg","splash"),createjs.Sound.registerSound("./sounds/hero_spike.ogg","hero_spike"),createjs.Sound.registerSound("./sounds/star.ogg","star")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/broken_stone.mp3","broken_stone"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/coin.mp3","coin"),createjs.Sound.registerSound("./sounds/game_completed.mp3","game_completed"),createjs.Sound.registerSound("./sounds/hero_falling.mp3","hero_falling"),createjs.Sound.registerSound("./sounds/hit_axe.mp3",
"hit_axe"),createjs.Sound.registerSound("./sounds/jump.mp3","jump"),createjs.Sound.registerSound("./sounds/level_completed.mp3","level_completed"),createjs.Sound.registerSound("./sounds/splash.mp3","splash"),createjs.Sound.registerSound("./sounds/hero_spike.mp3","hero_spike"),createjs.Sound.registerSound("./sounds/star.mp3","star")),f+=13)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_restart_big","./sprites/but_restart_big.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_level",
"./sprites/but_level.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_ice","./sprites/bg_ice.jpg");s_oSpriteLibrary.addSprite("bg_mountain","./sprites/bg_mountain.jpg");s_oSpriteLibrary.addSprite("bg_volcano","./sprites/bg_volcano.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_home",
"./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("player","./sprites/player.png");s_oSpriteLibrary.addSprite("game_completed_panel","./sprites/game_completed_panel.png");s_oSpriteLibrary.addSprite("level_completed_panel","./sprites/level_completed_panel.png");s_oSpriteLibrary.addSprite("game_over_panel","./sprites/game_over_panel.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("logo",
"./sprites/logo.png");s_oSpriteLibrary.addSprite("sea","./sprites/sea.png");s_oSpriteLibrary.addSprite("help_mouse","./sprites/help_mouse.png");s_oSpriteLibrary.addSprite("help_touch","./sprites/help_touch.png");s_oSpriteLibrary.addSprite("star","./sprites/star.png");s_oSpriteLibrary.addSprite("object_0","./sprites/object_0.png");s_oSpriteLibrary.addSprite("object_1","./sprites/object_1.png");s_oSpriteLibrary.addSprite("parallaxe_ice_0","./sprites/parallaxe_ice_0.png");s_oSpriteLibrary.addSprite("parallaxe_mountain_0",
"./sprites/parallaxe_mountain_0.png");s_oSpriteLibrary.addSprite("parallaxe_volcano_0","./sprites/parallaxe_volcano_0.png");s_oSpriteLibrary.addSprite("parallaxe_volcano_1","./sprites/parallaxe_volcano_1.png");s_oSpriteLibrary.addSprite("arrival_0","./sprites/arrival_0.png");s_oSpriteLibrary.addSprite("arrival_1","./sprites/arrival_1.png");s_oSpriteLibrary.addSprite("platform_ice_0","./sprites/platform_ice_0.png");s_oSpriteLibrary.addSprite("platform_ice_1","./sprites/platform_ice_1.png");s_oSpriteLibrary.addSprite("platform_mountain_0",
"./sprites/platform_mountain_0.png");s_oSpriteLibrary.addSprite("platform_mountain_1","./sprites/platform_mountain_1.png");s_oSpriteLibrary.addSprite("platform_volcano_0","./sprites/platform_volcano_0.png");s_oSpriteLibrary.addSprite("platform_volcano_1","./sprites/platform_volcano_1.png");f+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;e.refreshLoader(Math.floor(c/f*100));if(c===f){e.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=
createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)this._initSounds(),s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.loadJSON();this._loadImages();g=!0};this.onLoadedJSON=function(b){s_aLevelDiagram=b};this.loadJSON=function(){jQuery.getJSON(URL_LEVELS_SETTINGS,this.onLoadedJSON)};this.gotoMenu=function(){new CMenu;
h=STATE_MENU};this.gotoGame=function(b){m=new CGame(d,b);h=STATE_GAME;$(s_oMain).trigger("start_session")};this.gotoLevelMenu=function(){new CLevelMenu(d);h=STATE_MENU};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this.gotoCongratulations=function(b,a){new CCongratulations(b,a);h=STATE_MENU};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;$("#block_game").css("display",
"none")};this._update=function(b){if(!1!==g){var a=(new Date).getTime();s_iTimeElaps=a-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&m.update();s_oStage.update(b)}};s_oMain=this;d=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iAdsLevel=1,s_iLevelReached=1,s_aScores,s_aPercentage,s_aLevelDiagram,s_oTweenController,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack;
function CTextButton(a,g,c,f,h,d,e,m){var b,p,n,k;this._init=function(a,e,d,c,f,m,g){b=[];p=[];var h=createBitmap(d),z=Math.ceil(g/20),x=new createjs.Text(c,"bold "+g+"px "+f,"#000000");x.textAlign="center";x.textBaseline="alphabetic";var A=x.getBounds();x.x=d.width/2+z;x.y=Math.floor(d.height/2)+A.height/3+z;c=new createjs.Text(c,"bold "+g+"px "+f,m);c.textAlign="center";c.textBaseline="alphabetic";A=c.getBounds();c.x=d.width/2;c.y=Math.floor(d.height/2)+A.height/3;n=new createjs.Container;n.x=a;
n.y=e;n.regX=d.width/2;n.regY=d.height/2;n.addChild(h,x,c);s_bMobile||(n.cursor="pointer");k.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");k.removeChild(n)};this.setVisible=function(b){n.visible=b};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,d){b[a]=e;p[a]=d};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;playSound("click",1,0);b[ON_MOUSE_UP]&&
b[ON_MOUSE_UP].call(p[ON_MOUSE_UP])};this.buttonDown=function(){n.scaleX=.9;n.scaleY=.9;b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};this.setPosition=function(b,a){n.x=b;n.y=a};this.setX=function(b){n.x=b};this.setY=function(b){n.y=b};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};k=m;this._init(a,g,c,f,h,d,e);return this}
function CToggle(a,g,c,f,h){var d,e,m,b,p;this._init=function(a,c,f,g){e=[];m=[];var h=new createjs.SpriteSheet({images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{state_true:[0],state_false:[1]}});d=g;b=createSprite(h,"state_"+d,f.width/2/2,f.height/2,f.width/2,f.height);b.x=a;b.y=c;b.stop();s_bMobile||(b.cursor="pointer");p.addChild(b);this._initListener()};this.unload=function(){b.off("mousedown",this.buttonDown);b.off("pressup",this.buttonRelease);
p.removeChild(b)};this._initListener=function(){b.on("mousedown",this.buttonDown);b.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,d){e[b]=a;m[b]=d};this.setCursorType=function(a){b.cursor=a};this.setActive=function(a){d=a;b.gotoAndStop("state_"+d)};this.buttonRelease=function(){b.scaleX=1;b.scaleY=1;playSound("click",1,0);d=!d;b.gotoAndStop("state_"+d);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(m[ON_MOUSE_UP],d)};this.buttonDown=function(){b.scaleX=.9;b.scaleY=.9;e[ON_MOUSE_DOWN]&&
e[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setPosition=function(a,e){b.x=a;b.y=e};p=h;this._init(a,g,c,f)}
function CGfxButton(a,g,c,f){var h,d,e,m,b,p,n,k=!1,l;this._init=function(a,c,f){h=[];d=[];e=createBitmap(f);e.x=a;e.y=c;p=b=1;e.regX=f.width/2;e.regY=f.height/2;s_bMobile||(e.cursor="pointer");l.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);l.removeChild(e)};this.setVisible=function(b){e.visible=b};this.setCursorType=function(b){e.cursor=b};this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",
this.buttonRelease)};this.addEventListener=function(b,a,e){h[b]=a;d[b]=e};this.addEventListenerWithParams=function(b,a,e,c){h[b]=a;d[b]=e;m=c};this.buttonRelease=function(){k||(e.scaleX=0<b?1:-1,e.scaleY=1,playSound("click",1,0),h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(d[ON_MOUSE_UP],m))};this.buttonDown=function(){k||(e.scaleX=0<b?.9:-.9,e.scaleY=.9,h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN],m))};this.rotation=function(b){e.rotation=b};this.getButton=function(){return e};this.setPosition=
function(b,a){e.x=b;e.y=a};this.setX=function(b){e.x=b};this.setY=function(b){e.y=b};this.getButtonImage=function(){return e};this.block=function(a){k=a;e.scaleX=b;e.scaleY=p};this.setScaleX=function(a){b=e.scaleX=a};this.getX=function(){return e.x};this.getY=function(){return e.y};this.pulseAnimation=function(){createjs.Tween.get(e).to({scaleX:.9*b,scaleY:.9*p},850,createjs.Ease.quadOut).to({scaleX:b,scaleY:p},650,createjs.Ease.quadIn).call(function(){n.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(e).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){n.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(e)};l=f;this._init(a,g,c);n=this;return this}
function CMenu(){var a,g,c,f,h,d,e,m,b,p,n,k,l,q,r=null,v;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var r=s_oSpriteLibrary.getSprite("but_play");h=CANVAS_WIDTH/2;d=CANVAS_HEIGHT-90;p=new CGfxButton(h,d,r,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(null!==getItem("olaf_levelreached")){s_iLevelReached=getItem("olaf_levelreached");s_aScores=JSON.parse(getItem("olaf_scores"));s_aPercentage=JSON.parse(getItem("olaf_percentage"));
h=CANVAS_WIDTH/2-200;d=CANVAS_HEIGHT-90;p.setPosition(h,d);c=CANVAS_WIDTH/2+200;f=CANVAS_HEIGHT-90;var u=s_oSpriteLibrary.getSprite("but_continue");k=new CGfxButton(c,f,u,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this);k.pulseAnimation()}else p.pulseAnimation(),this.resetArrays();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-r.height/2-10,m=r.height/2+10,v=new CToggle(e,m,r,s_bAudioActive,s_oStage),v.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);u=s_oSpriteLibrary.getSprite("but_info");a=r.height/2+10;g=r.height/2+10;n=new CGfxButton(a,g,u,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l=new CLogo(.5*CANVAS_WIDTH,-200);s_oStage.addChild(q);createjs.Tween.get(q).to({alpha:0},800).call(function(){q.visible=!1});l.playAnimation();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(b,
l){p.setPosition(h,d-l);k&&k.setPosition(c,f-l);n.setPosition(a+b,g+l);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||v.setPosition(e-b,l+m)};this.unload=function(){p.unload();p=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v.unload(),v=null;s_oStage.removeAllChildren();createjs.Tween.removeAllTweens();s_oMenu=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButInfoRelease=function(){new CCreditsPanel};this._onButNo=function(){r.unload();
r=null};this._onButYes=function(){clearAllItem();this.unload();s_iLevelReached=1;this.resetArrays();s_oMain.gotoLevelMenu()};this._onButContinueRelease=function(){this.unload();playSound("click",1,0);s_oMain.gotoLevelMenu()};this.resetArrays=function(){s_aScores=[];s_aPercentage=[];for(var b=0;b<s_aLevelDiagram.length;b++)s_aScores[b]=0,s_aPercentage[b]=0};this._onButPlayRelease=function(){null===getItem("olaf_levelreached")?(this.unload(),playSound("click",1,0),s_oMain.gotoLevelMenu()):null===r&&
(r=new CConfirmPanel(TEXT_RESET,CONFIRMATION_RESET),r.addEventListener(ON_BUT_NO_DOWN,this._onButNo,this),r.addEventListener(ON_BUT_YES_DOWN,this._onButYes,this))};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a,g){var c,f,h,d,e,m,b,p,n,k=null,l,q,r,v,t=null,u,w,y,z=!1,x=!1;this._init=function(){c=!1;b=p=h=d=f=0;e=g;m=GAME_STATE_HELP;for(var a=0;a<e;a++)f+=s_aScores[a];void 0===f&&(f=0);d=f;this.createLevel();a=s_oSpriteLibrary.getSprite("player");this._createPlayer(a,s_aLevelDiagram[e].playerX,s_aLevelDiagram[e].playerY,s_oStage);this.createSea();n=new CInterface;n.refreshScore(d);n.refreshLevelCounter(e+1);m=GAME_STATE_HELP;setVolume(s_oSoundTrack,.35)};this.createParallaxeObject=function(){v=
new CParallaxObject(0,0,s_oStage);var b=s_aLevelDiagram[e].material,a=0;if("ice"===b)a=PARALLAXE_Y_POS_ICE;else if("volcano"===b||"mountain"===b)a=PARALLAXE_Y_POS_VM;for(var d=0;d<MAX_NUM_PARALLAXE;d++){var c=Math.floor(Math.random()*CANVAS_WIDTH),f=0;"volcano"===b&&(f=Math.round(1*Math.random()));v.addObject(c,a,b,f)}v.setSpeed(PARALLAX_SPEED)};this._createPlayer=function(b,a,e,d){l=new CCharacter(a,e,b,d);l.stopAnimation()};this.createLevel=function(){var b=s_aLevelDiagram[e].platform,a=b.length,
d=b[0].length,c=s_aLevelDiagram[e].material;k?y!==c&&(k.image=s_oSpriteLibrary.getSprite("bg_"+c)):(k=createBitmap(s_oSpriteLibrary.getSprite("bg_"+c)),k.on("mousedown",this._onMouseDown),k.on("pressup",this._onPressUp),y=c,s_oStage.addChild(k));this.createParallaxeObject();q=new CLevelPlatforms(0,0,s_oStage);this.createLevelObject();for(var f=FIRST_PLATFORM_X,m,p=0,g=0;g<d;g++){m=PLATFORM_Y_START;for(var h=0;h<a;h++)m+=50,-1!==b[h][g]&&(q.addPlatform(f,m,p,c,b[h][g]),p++);f+=50}q.createArrival(s_aLevelDiagram[e].last_platform)};
this.createLevelObject=function(){var a=s_aLevelDiagram[e].objects;r=new CLevelObjects(0,0,s_oStage);for(var d=0,c=0;c<a.length;c++){var f=a[c].x+100,m=a[c].y,p=a[c].gid;0===p&&b++;r.addObject(f,m,d,p);d++}};this.createSea=function(){"ice"===s_aLevelDiagram[e].material&&(t=new CSea(0,0,s_oStage),t.setSpeed(PLATFORM_SPEED))};this._onMouseDown=function(){c&&!1!==l.getCollisionWithPlatform()&&m===GAME_STATE_PLAY&&(l.moveUp(),l.stayMouseDown(!0),l.collisionWithPlatform(!1),l.changeState("jump"),playSound("jump",
1,0))};this.win=function(){var b=d;d=f;s_iLevelReached<e+2&&(s_iLevelReached=e+2);h>s_aScores[e]&&(s_aScores[e]=h);var a=this.calculatePercentCoins();a>s_aPercentage[e]&&(s_aPercentage[e]=a);saveItem("olaf_levelreached",s_iLevelReached);saveItem("olaf_scores",JSON.stringify(s_aScores));saveItem("olaf_percentage",JSON.stringify(s_aPercentage));e>=s_aLevelDiagram.length-1?(n.createCongratulations(d,a,h,b),u=playSound("game_completed",1,-1),w=DECREASE_FACTOR_VOL_GAME_COMPLETED):(n.createWinPanel(d,a,
h,b,e),u=playSound("level_completed",1,-1),w=DECREASE_FACTOR_VOL_LEVEL_COMPLETED);setVolume(s_oSoundTrack,0);$(s_oMain).trigger("end_level",e);f=d};this.calculatePercentCoins=function(){return Math.floor(p/b*100)};this._onPressUp=function(){c&&m===GAME_STATE_PLAY&&l.stayMouseDown(!1)};this.unload=function(){c=!1;n.unload();l.unload();u&&(u.destroy(),u=null);s_oStage.removeAllChildren();createjs.Tween.removeAllTweens()};this.onExit=function(){this.unload();$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,1);s_oMain.gotoMenu()};this._onExitHelp=function(){$(s_oMain).trigger("start_level",e);c=!0;l.playAnimation();m=GAME_STATE_PLAY};this.unpause=function(b){c=b;!0===b?l.playAnimation():l.stopAnimation()};this.changeState=function(b){m=b};this.nextLevel=function(){e++;u&&(u.destroy(),u=null);setVolume(s_oSoundTrack,.35);"ice"===y&&y!==s_aLevelDiagram[e].material&&t&&(t.unload(),t=null);$(s_oMain).trigger("start_level",e);n.refreshLevelCounter(e+
1);this.restartLevel()};this._onEnd=function(){this.unload();$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,1);s_oMain.gotoCongratulations(_aResults,f)};this.gameOver=function(){m=GAME_STATE_FINISH;c=!1;n.createLosePanel(f)};this.addScore=function(b){f+=b;h+=b;n.refreshScore(f)};this.restartLevel=function(){l.removeTweens();this.unloadLevel();f=d;p=b=h=0;n.refreshScore(f);l.setPosition(s_aLevelDiagram[e].playerX-10,s_aLevelDiagram[e].playerY);l.playerIDPlatform(0);l.changeState("run");
l.resetJump();this.createLevel();q.setSpeed(PLATFORM_SPEED);v.setSpeed(PARALLAX_SPEED);t&&t.setSpeed(PLATFORM_SPEED);r.setSpeed(PLATFORM_SPEED);u&&(u.destroy(),u=null);setVolume(s_oSoundTrack,.35);c=!0};this.unloadLevel=function(){q.unload();q=null;v.unload();v=null;r.unload();r=null};this.platformFinished=function(){m=GAME_STATE_FINISH;q.setSpeed(0);t&&t.setSpeed(-.5);z=q.getArrival().getY()-l.getY()>=TOLLERANCE_Y_FOR_ANIMATION?!0:!1;l.animationArrival(q.getArrival(),q.getPlatformByID(q.getArrival().getIDPlatform()),
z)};this.collisionPlatform=function(b){!1===b.collide&&!1===l.getCollisionWithPlatform()&&(l.collisionWithPlatform(!0),l.setPosition(l.getX(),b.y+OFFSET_HEIGHT_PLATFORM_CHRACTER),m===GAME_STATE_PLAY&&l.changeState("run"))};this.collisionWall=function(){q.setSpeed(0);v.setSpeed(0);t&&t.setSpeed(-.5);r.setSpeed(0);l.changeState("fall");l.collisionWithPlatform(!1)};this.fallLimit=function(){null!==t?l.getY()>POSITION_Y_SEA+50&&(l.playSeaAnimation(),z=!0,playSound("splash",1,0),m=GAME_STATE_GAMEOVER,
t.setSpeed(-.5)):l.getY()>FALL_LIMIT_Y&&(this.gameOver(),playSound("hero_falling",1,0),m=GAME_STATE_GAMEOVER)};this.spikeCollision=function(){t&&t.setSpeed(-.5);this.changeState(GAME_STATE_GAMEOVER);l.playDeadSpikeAnimation();playSound("hero_spike",1,0)};this.decreaseVolumeSoundLevelComplete=function(b){x=b};this.unloadObject=function(b){r.unloadObject(b)};this.addObtainCoin=function(){p++};this.update=function(){switch(m){case GAME_STATE_PLAY:if(c){var b={rect:l.getRectangle(),id:l.getIDPlatform()},
a=q.update(b);r.update(b);l.playerIDPlatform(a.id);a.collision===COLLISION_PLATFORM?this.collisionPlatform(a):a.collision===COLLISION_WALL?this.collisionWall():a.collision===COLLISION_NOTHING&&(l.collisionWithPlatform(!1),q.getPlatformByID(a.id).setCollideYet(!1));v.update();t&&t.update();this.fallLimit();l.update()}break;case GAME_STATE_FINISH:c&&!z&&!1===l.getCollisionWithPlatform()&&(b={rect:l.getRectangle(),id:l.getIDPlatform()},a=q.update(b),l.playerIDPlatform(a.id),a.collision===COLLISION_PLATFORM&&
(this.collisionPlatform(a),l.changeState("lands")),l.update());t&&t.update();x&&u&&(u.volume*=w);break;case GAME_STATE_GAMEOVER:t&&t.update()}};s_oGame=this;PLATFORM_SPEED=a.platform_velocity;HERO_DOWN_ACCELLERATION=a.hero_down_speed;DECELLERATION_MOUSE_DOWN=a.decelleration_mouse_down;DECELLERATION_NORMAL=a.decelleration_normal;NUM_LEVEL_FOR_ADS=a.num_levels_for_ads;JUMP_MULTIPLY=a.jump_multiplier;PARALLAX_SPEED=a.parallax_speed;COIN_SCORE=a.coin_score;PERCENTAGE_STARS=a.percentage_stars;this._init()}
var s_oGame;
function CInterface(){var a,g,c,f,h,d,e,m,b,p,n,k,l,q,r,v,t,u,w,y,z;this._init=function(){var b=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-b.height/2-10;f=b.height/2+10;p=new CGfxButton(c,f,b,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onExit,this);b=s_oSpriteLibrary.getSprite("but_pause");a=c-b.height-10;g=f;n=new CGfxButton(a,g,b,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onPause,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b=s_oSpriteLibrary.getSprite("audio_icon"),e=a-
b.height-10,m=f,l=new CToggle(e,m,b,s_bAudioActive,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h=CANVAS_WIDTH/2-75;d=53;r=new createjs.Container;r.x=h;r.y=d;t=new createjs.Text(TEXT_SCORE+" 0","normal 36px "+FONT_GAME,"#000000");t.textAlign="left";t.textBaseline="alphabetic";t.x=0;t.y=0;t.outline=3;r.addChild(t);v=new createjs.Text(TEXT_SCORE+" 0","normal 36px "+FONT_GAME,TEXT_COLOR);v.textAlign="left";v.textBaseline="alphabetic";v.x=0;v.y=0;r.addChild(v);this.createLevelCounter();
z=new CAreYouSurePanel(s_oStage);s_oStage.addChild(r);k=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("msg_box"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(h,k){p.setPosition(c-h,k+f);n.setPosition(a-h,k+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(e-h,k+m);r.y=d+k;u.x=b.x+h;u.y=b.y+k};this.createLevelCounter=function(){b={x:10,y:53};u=new createjs.Container;u.x=b.x;u.y=b.y;y=new createjs.Text(TEXT_LEVEL+" 0","normal 36px "+FONT_GAME,"#000000");y.textAlign=
"left";y.textBaseline="alphabetic";y.x=0;y.y=0;y.outline=3;u.addChild(y);w=new createjs.Text(TEXT_LEVEL+" 0","normal 36px "+FONT_GAME,TEXT_COLOR);w.textAlign="left";w.textBaseline="alphabetic";w.x=0;w.y=0;u.addChild(w);s_oStage.addChild(u)};this.unload=function(){p.unload();p=null;n.unload();n=null;z&&z.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oInterface=null};this.createLosePanel=function(b){new CLosePanel(s_oSpriteLibrary.getSprite("game_over_panel"),b)};this.createWinPanel=
function(b,a,e,d,c){new CWinPanel(s_oSpriteLibrary.getSprite("level_completed_panel"),b,a,e,d,c)};this.createCongratulations=function(b,a,e,d){new CCongratulations(s_oSpriteLibrary.getSprite("game_completed_panel"),b,a,e,d)};this.unloadHelpPanel=function(){k&&(k.unload(),k=null)};this.createPauseInterface=function(){q=new CPause};this.unloadPause=function(){q.unload();q=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){z.show()};
this.refreshScore=function(b){v.text=TEXT_SCORE+" "+b;t.text=TEXT_SCORE+" "+b};this.refreshLevelCounter=function(b){w.text=TEXT_LEVEL+": "+b;y.text=w.text};this._onPause=function(){s_oGame.unpause(!1);this.createPauseInterface();createjs.Ticker.paused=!0};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(a,g,c){var f,h,d,e,m=!1;this._init=function(b,a,e){f=createBitmap(e);f.x=.5*CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT;f.regX=.5*e.width;f.regY=.5*e.height;h=new createjs.Container;h.x=b;h.y=a;d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.5;h.addChild(d);h.addChild(f);s_oStage.addChild(h);this.page1();h.on("pressup",function(){s_oHelpPanel._onExitHelp()},null,!0);s_bMobile||(h.cursor="pointer")};this.page1=function(){var b;b=new createjs.Text(TEXT_HELP_INPUT,
"30px "+FONT_GAME,"#000000");b.textAlign="center";b.textBaseline="middle";b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-85;b.outline=3;h.addChild(b);var a;a=new createjs.Text(TEXT_HELP_INPUT,"30px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.lineWidth=600;a.x=b.x;a.y=b.y;h.addChild(a);var d=s_oSpriteLibrary.getSprite("player");(new CCharacter(a.x-90,b.y+40,d,h)).changeState("start_jump_help");a=s_bMobile?s_oSpriteLibrary.getSprite("help_touch"):s_oSpriteLibrary.getSprite("help_mouse");
d=createBitmap(a);d.x=b.x+90;d.y=b.y;d.regX=.5*a.width;d.regY=.5*a.height;h.addChild(d);b=new createjs.Text(TEXT_HELP_COIN,"30px "+FONT_GAME,"#000000");b.textAlign="center";b.textBaseline="middle";b.lineWidth=400;b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT;b.outline=3;h.addChild(b);a=new createjs.Text(b.text,"30px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.lineWidth=b.lineWidth;a.x=b.x;a.y=b.y;h.addChild(a);a=s_oSpriteLibrary.getSprite("object_0");d=new createjs.SpriteSheet({images:[a],
frames:{width:a.width/5,height:a.height/4,regX:a.width/2/5,regY:a.height/2/4},animations:{normal:[0,19,"normal"]}});a=createSprite(d,"run",a.width/2/5,a.height/2/4,a.width/5,a.height/4);a.x=.5*CANVAS_WIDTH-100;a.y=b.y;h.addChild(a);b=new createjs.Text(TEXT_HELP_SPIKE,"30px "+FONT_GAME,"#000000");b.textAlign="center";b.textBaseline="middle";b.lineWidth=600;b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT+85;b.outline=3;h.addChild(b);a=new createjs.Text(b.text,"30px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";
a.textBaseline="middle";a.lineWidth=600;a.x=b.x;a.y=b.y;h.addChild(a);d=s_oSpriteLibrary.getSprite("object_1");a=createBitmap(d);a.x=.5*CANVAS_WIDTH-100;a.y=b.y;a.regX=d.width/2;a.regY=d.height/2;h.addChild(a);createjs.Tween.get(h).to({alpha:1},300,createjs.Ease.cubicOut);b=s_oSpriteLibrary.getSprite("but_continue");e=new CGfxButton(.5*CANVAS_WIDTH+210,.5*CANVAS_HEIGHT+80,b,h);e.addEventListener(ON_MOUSE_UP,this._onExitHelp,this);e.pulseAnimation();s_oStage.addChild(h)};this.unload=function(){s_oStage.removeChild(h);
s_oHelpPanel=null;h.off("click",function(){});e.unload();e=null};this._onExitHelp=function(){m||(m=!0,playSound("click",1,0),createjs.Tween.get(h).to({alpha:0},500).call(function(){s_oHelpPanel.unload();s_oGame._onExitHelp()}))};s_oHelpPanel=this;this._init(a,g,c)}var s_oHelpPanel=null;
function CLosePanel(a,g){var c,f,h,d,e,m,b;this._init=function(a,g){c=new createjs.Container;f=new createjs.Container;b=a.width;f.y=-b;h=createBitmap(a);h.x=.5*CANVAS_WIDTH;h.y=.5*CANVAS_HEIGHT;h.regX=.5*a.width;h.regY=.5*a.height;f.addChild(h);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("click",function(){});c.addChild(d);var k,l;l=new createjs.Text(TEXT_GAMEOVER,"44px "+FONT_GAME,"#000000");l.textAlign="center";l.textBaseline="middle";
l.x=.5*CANVAS_WIDTH;l.y=176;l.outline=4;f.addChild(l);k=new createjs.Text(TEXT_GAMEOVER,"44px "+FONT_GAME,TEXT_COLOR);k.textAlign="center";k.textBaseline="middle";k.x=.5*CANVAS_WIDTH;k.y=l.y;f.addChild(k);l=new createjs.Text(TEXT_SCORE+": "+g,"34px "+FONT_GAME,"#000000");l.textAlign="center";l.textBaseline="middle";l.x=.5*CANVAS_WIDTH;l.y=241;l.outline=4;f.addChild(l);k=new createjs.Text(TEXT_SCORE+": "+g,"34px "+FONT_GAME,TEXT_COLOR);k.textAlign="center";k.textBaseline="middle";k.x=.5*CANVAS_WIDTH;
k.y=l.y;f.addChild(k);c.addChild(f);c.x=0;c.y=0;s_oStage.addChild(c);k=s_oSpriteLibrary.getSprite("but_restart_big");l=s_oSpriteLibrary.getSprite("but_home");e=new CGfxButton(510,350,l,f);e.addEventListener(ON_MOUSE_UP,this._onExit,this);m=new CGfxButton(850,350,k,f);m.addEventListener(ON_MOUSE_UP,this._onRestart,this);m.pulseAnimation();createjs.Tween.get(d).to({alpha:.5},750,createjs.Ease.cubicOut);createjs.Tween.get(f).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?
($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++});$(s_oMain).trigger("save_score",g);$(s_oMain).trigger("share_event",g)};this.unload=function(){var a=this;createjs.Tween.get(f).to({y:CANVAS_HEIGHT+b},1500,createjs.Ease.cubicIn).call(function(){a.unloadButton()})};this.unloadButton=function(){e.unload();e=null;m.unload();m=null};this.blockAllBut=function(){m.block(!0);e.block(!0)};this._onRestart=function(){this.blockAllBut();this.unload();createjs.Tween.get(d).to({alpha:1},
1E3,createjs.Ease.cubicIn).call(function(){s_oGame.restartLevel();s_oGame.changeState(GAME_STATE_PLAY);createjs.Tween.get(d).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(c)})})};this._onExit=function(){this.unload();this.blockAllBut();s_oGame.onExit()};this._init(a,g);return this}
function CWinPanel(a,g,c,f,h,d){var e,m,b,p,n,k,l,q,r,v,t;this._init=function(a,d,c,f,g,h){t=[];e=new createjs.Container;m=new createjs.Container;v=a.width;m.y=-v;b=createBitmap(a);b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT;b.regX=.5*a.width;b.regY=.5*a.height;m.addChild(b);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=0;p.on("click",function(){});e.addChild(p);var r;r=new createjs.Text(TEXT_LEVEL_COMPLETED,"40px "+FONT_GAME,"#000000");r.textAlign=
"center";r.textBaseline="middle";r.x=.5*CANVAS_WIDTH+65;r.y=166;r.outline=4;m.addChild(r);a=new createjs.Text(TEXT_LEVEL_COMPLETED,"40px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.x=r.x;a.y=r.y;m.addChild(a);r=new createjs.Text(TEXT_SCORE+":","32px "+FONT_GAME,"#000000");r.textAlign="center";r.textBaseline="middle";r.x=717;r.y=270;r.outline=4;m.addChild(r);a=new createjs.Text(TEXT_SCORE+":","32px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.x=
r.x;a.y=r.y;m.addChild(a);var q;q=new createjs.Text(g,"32px "+FONT_GAME,"#000000");q.textAlign="left";q.textBaseline="middle";q.x=r.x+54;q.y=270;q.outline=4;m.addChild(q);var C;C=new createjs.Text(g,"32px "+FONT_GAME,TEXT_COLOR);C.textAlign="left";C.textBaseline="middle";C.x=q.x;C.y=q.y;m.addChild(C);var D;D=new createjs.Text("0","32px "+FONT_GAME,"#000000");D.textAlign="center";D.textBaseline="middle";D.x=840;D.y=242;D.outline=4;var E;E=new createjs.Text("0","32px "+FONT_GAME,"#000000");E.textAlign=
"center";E.textBaseline="middle";E.x=840;E.y=242;g=s_oSpriteLibrary.getSprite("star");for(a=0;a<NUMBER_OF_STARS;a++)t[a]=new CStar(STARS_POSITION[a].x,STARS_POSITION[a].y,g,!1,m);e.addChild(m);e.x=0;e.y=0;s_oStage.addChild(e);g=s_oSpriteLibrary.getSprite("but_restart_big");a=s_oSpriteLibrary.getSprite("but_home");r=s_oSpriteLibrary.getSprite("but_continue");n=new CGfxButton(635,350,a,m);n.addEventListener(ON_MOUSE_UP,this._onExit,this);k=new CGfxButton(759,350,g,m);k.addEventListenerWithParams(ON_MOUSE_UP,
this._onRestart,this,h);l=new CGfxButton(882,350,r,m);l.addEventListener(ON_MOUSE_UP,this._onContinue,this);l.pulseAnimation();createjs.Tween.get(p).to({alpha:.5},750,createjs.Ease.cubicOut);var G=this;createjs.Tween.get(m).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++;G.checkPoint(C,q,f,G);G.checkStars(E,D,c,G)});$(s_oMain).trigger("save_score",d);$(s_oMain).trigger("share_event",d)};this.unload=
function(){this.blockAllBut();var a=this;createjs.Tween.get(m).to({y:CANVAS_HEIGHT+v},1E3,createjs.Ease.cubicIn).call(function(){a.unloadButton()});q.unload();r.unload()};this.blockAllBut=function(){k.block(!0);n.block(!0);l.block(!0)};this.unloadButton=function(){n.unload();n=null;k.unload();k=null;l.unload();l=null};this._onRestart=function(a){this.unload();createjs.Tween.get(p).to({alpha:1},1E3,createjs.Ease.cubicIn).call(function(){s_oGame.restartLevel();s_oGame.changeState(GAME_STATE_PLAY);createjs.Tween.get(p).to({alpha:0},
1E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(e)})});$(s_oMain).trigger("restart_level",a)};this.checkStars=function(a,b,e,d){r=new CRollingTextController(a,b,e,4E3,EASE_CUBIC_OUT);r.addEventListener(ON_CONTROLLER_END,d._onFinishRollingStars);r.addEventListener(ON_CONTROLLER_REMOVE,d._onFinishRollingStars);r.addRollingListener(d._onRollingText,d,PERCENTAGE_STARS)};this.checkPoint=function(a,b,e,d){q=new CRollingTextController(a,b,e,4E3,EASE_CUBIC_OUT);q.addEventListener(ON_CONTROLLER_END,
d._onFinishRollingPoint);q.addEventListener(ON_CONTROLLER_REMOVE,d._onFinishRollingPoint);q.addRollingListener(d._onRollingTextScore,d,PERCENTAGE_STARS)};this._onFinishRollingPoint=function(){q.unload()};this._onFinishRollingStars=function(){r.unload()};this._onContinue=function(){this.unload();s_oGame.decreaseVolumeSoundLevelComplete(!0);createjs.Tween.get(p).to({alpha:1},750,createjs.Ease.cubicIn).call(function(){s_oGame.nextLevel();s_oGame.changeState(GAME_STATE_PLAY);createjs.Tween.get(p).to({alpha:0},
750,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(e);s_oGame.decreaseVolumeSoundLevelComplete(!1)})})};this._onRollingTextScore=function(){};this._onRollingText=function(a){t[a].setActive(!0);t[a].pulseAnimation(500,SCALE_STAR_FACTOR);playSound("star",1,0)};this._onExit=function(){this.unload();s_oGame.onExit()};this._init(a,g,c,f,h,d);return this}
function CCharacter(a,g,c,f){var h,d,e,m,b,p,n,k=null,l,q,r=!1,v,t,u,w=!1,y=!1;this._init=function(a,c,f,g){p=g;g=new createjs.SpriteSheet({images:[f],frames:{width:f.width/10,height:f.height/6,regX:f.width/2/10,regY:f.height/6},animations:{run:[0,15,"run",1],jump:[16,19,"jump_stay"],lands_run:[20,23,"run"],lands:[20,26,"idle"],shot:[28,40,"shot_remain"],dance:[41,53,"dance"],fall:[54,58,"fall_stay"],ice:[59],idle:[26],jump_stay:[19],fall_stay:[58],shot_remain:[40],start_jump:{frames:[25,24,23,22,
21,20,19,18],next:"jump"},start_jump_help:{frames:[25,24,23,22,21,20,19],next:"jump_help",speed:.5},jump_help:[19,19,"lands_help",.1],lands_help:[20,26,"start_jump_help",.5]}});b=createSprite(g,"run",f.width/2/10,f.height/6,f.width/10,f.height/6);b.x=a;b.y=c;l=HERO_DOWN_ACCELLERATION;t=f.width/10;u=f.height/6;h=a-t+OFFSET_PLAYER_COL_POINT.x;d=c-u+OFFSET_PLAYER_COL_POINT.y;e=t+OFFSET_PLAYER_COL_DIMENSION.x;m=u+OFFSET_PLAYER_COL_DIMENSION.y;n=new createjs.Rectangle(h,d,e,m);SHOW_COLLISION_SHAPE&&(k=
new createjs.Shape,k.graphics.beginFill("#00ff00").drawRect(n.x,n.y,n.width,n.height),k.alpha=.5,p.addChild(k));v=q=0;p.addChild(b)};this.getX=function(){return b.x};this.getY=function(){return b.y};this.onPlatform=function(a){y=a};this.getOnPlatform=function(){return y};this.setPosition=function(a,e){null!==a&&(b.x=a);null!==e&&(b.y=e);this.rectMovement()};this.rotate=function(a){b.scaleX=a};this.setVisible=function(a){b.visible=a};this.changeState=function(a){b.gotoAndPlay(a)};this.stopAnimation=
function(){b.stop()};this.playAnimation=function(){b.play()};this._onFinishAnimation=function(){b.on("animationend",function(){})};this.collisionWithPlatform=function(a){!0===w&&b.gotoAndPlay("jump");w=a};this.getCollisionWithPlatform=function(){return w};this.getRectangle=function(){return n};this.moveUp=function(){q=-HERO_DOWN_ACCELLERATION*JUMP_MULTIPLY;l=-HERO_DOWN_ACCELLERATION};this.stayMouseDown=function(a){r=a};this.unload=function(){p.removeChild(b);s_oCharacter=null};this.playerIDPlatform=
function(a){v=a};this.getIDPlatform=function(){return v};this.resetJump=function(){l=HERO_DOWN_ACCELLERATION};this.rectMovement=function(){h=b.x-t+OFFSET_PLAYER_COL_POINT.x;d=b.y-u+OFFSET_PLAYER_COL_POINT.y;e=t+OFFSET_PLAYER_COL_DIMENSION.x;m=u+OFFSET_PLAYER_COL_DIMENSION.y;n.setValues(h,d,e,m);SHOW_COLLISION_SHAPE&&(k&&(p.removeChild(k),k=null),k=new createjs.Shape,k.graphics.beginFill("#00ff00").drawRect(n.x,n.y,n.width,n.height),k.alpha=.5,p.addChild(k))};this.animationArrival=function(a,e,d){createjs.Tween.removeTweens(b);
d?(b.gotoAndPlay("shot"),createjs.Tween.get(b).wait(300).call(function(){a.destroyEffect()}),createjs.Tween.get(b).to({y:e.getY()+30,x:a.getX()-10},500,createjs.Ease.quadIn).call(function(){b.gotoAndPlay("lands");b.on("animationend",function(){b.gotoAndStop("idle");b.removeAllEventListeners()});createjs.Tween.get(b).wait(1200).call(function(){b.gotoAndPlay("dance");b.on("animationend",function(){s_oGame.win();b.removeAllEventListeners()})})})):(w&&b.gotoAndPlay("idle"),createjs.Tween.get(b).wait(300).call(function(){b.gotoAndPlay("start_jump");
createjs.Tween.get(b).wait(180).call(function(){createjs.Tween.get(b).to({y:a.getY()-100,x:a.getX()-20},750,createjs.Ease.cubicOut).call(function(){b.gotoAndPlay("shot");createjs.Tween.get(b).wait(300).call(function(){a.destroyEffect()});createjs.Tween.get(b).to({y:e.getY()+30,x:a.getX()-10},500,createjs.Ease.circIn).call(function(){b.gotoAndPlay("lands");b.on("animationend",function(){b.gotoAndStop("idle");b.removeAllEventListeners()});createjs.Tween.get(b).wait(1200).call(function(){b.gotoAndPlay("dance");
b.on("animationend",function(){s_oGame.win();b.removeAllEventListeners()})})})})})}))};this.playSeaAnimation=function(){var a=this;createjs.Tween.get(b).wait(300).call(function(){b.gotoAndStop("ice")});createjs.Tween.get(b).to({y:POSITION_Y_SEA+150},1E3,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(b).to({y:POSITION_Y_SEA+40},1E3,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(b).to({y:POSITION_Y_SEA+70},700,createjs.Ease.cubicInOut).call(function(){a.loopBounceSea();createjs.Tween.get(b).wait(600).call(function(){s_oGame.gameOver()})})})})};
this.playDeadSpikeAnimation=function(){b.gotoAndPlay("fall");s_oGame.changeState(GAME_STATE_GAMEOVER);createjs.Tween.get(b).to({y:b.y-50,x:b.x+30},500,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(b).to({y:CANVAS_HEIGHT+u},750,createjs.Ease.cubicIn).call(function(){s_oGame.gameOver()})})};this.loopBounceSea=function(){var a=this,e=5*Math.random();createjs.Tween.get(b).to({y:POSITION_Y_SEA+50,rotation:e},1E3,createjs.Ease.quartInOut).call(function(){var e=-5*Math.random();createjs.Tween.get(b).to({y:POSITION_Y_SEA+
70,rotation:e},1E3,createjs.Ease.quartInOut).call(function(){a.loopBounceSea()})})};this.removeTweens=function(){createjs.Tween.removeTweens(b)};this.update=function(){l=r?l<HERO_DOWN_ACCELLERATION?l+DECELLERATION_MOUSE_DOWN:HERO_DOWN_ACCELLERATION:l<HERO_DOWN_ACCELLERATION?l+DECELLERATION_NORMAL:HERO_DOWN_ACCELLERATION;-100>b.y&&(b.y=-100);w?q=0:(q+=l,b.y+=q);this.rectMovement()};s_oCharacter=this;this._init(a,g,c,f)}var s_oCharacter;
function CCongratulations(a,g,c,f,h){var d,e,m,b,p,n,k,l,q;this._init=function(a,c,f,g,h){q=[];d=new createjs.Container;e=new createjs.Container;l=a.width;e.y=-l;m=createBitmap(a);m.x=.5*CANVAS_WIDTH;m.y=.5*CANVAS_HEIGHT;m.regX=.5*a.width;m.regY=.5*a.height;e.addChild(m);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=0;b.on("click",function(){});d.addChild(b);var k;k=new createjs.Text(TEXT_CONGRATULATIONS,"42px "+FONT_GAME,"#000000");k.textAlign=
"center";k.textBaseline="middle";k.x=.5*CANVAS_WIDTH;k.y=166;k.outline=4;e.addChild(k);a=new createjs.Text(TEXT_CONGRATULATIONS,"42px "+FONT_GAME,"#ffdc00");a.textAlign="center";a.textBaseline="middle";a.x=.5*CANVAS_WIDTH;a.y=k.y;e.addChild(a);k=new createjs.Text(TEXT_GAME_COMPLETED,"30px "+FONT_GAME,"#000000");k.textAlign="center";k.textBaseline="middle";k.x=685;k.y=236;k.outline=4;e.addChild(k);a=new createjs.Text(TEXT_GAME_COMPLETED,"30px "+FONT_GAME,"#ffdc00");a.textAlign="center";a.textBaseline=
"middle";a.x=k.x;a.y=k.y;e.addChild(a);k=new createjs.Text(TEXT_SCORE+":","26px "+FONT_GAME,"#000000");k.textAlign="center";k.textBaseline="middle";k.x=640;k.y=350;k.outline=4;e.addChild(k);a=new createjs.Text(TEXT_SCORE+":","26px "+FONT_GAME,"#ffdc00");a.textAlign="center";a.textBaseline="middle";a.x=k.x;a.y=k.y;e.addChild(a);var n;n=new createjs.Text(h,"26px "+FONT_GAME,"#000000");n.textAlign="left";n.textBaseline="middle";n.x=k.x+50;n.y=k.y;n.outline=4;e.addChild(n);var x;x=new createjs.Text(h,
"26px "+FONT_GAME,"#ffdc00");x.textAlign="left";x.textBaseline="middle";x.x=n.x;x.y=n.y;e.addChild(x);var A;A=new createjs.Text("0","26px "+FONT_GAME,"#000000");A.textAlign="center";A.textBaseline="middle";A.x=840;A.y=242;A.outline=4;var B;B=new createjs.Text("0","26px "+FONT_GAME,"#000000");B.textAlign="center";B.textBaseline="middle";B.x=840;B.y=242;h=s_oSpriteLibrary.getSprite("star");for(a=0;a<NUMBER_OF_STARS;a++)q[a]=new CStar(STARS_POSITION[a].x-75,STARS_POSITION[a].y+75,h,!1,e);d.addChild(e);
d.x=0;d.y=0;s_oStage.addChild(d);h=s_oSpriteLibrary.getSprite("but_home");p=new CGfxButton(882,350,h,e);p.addEventListener(ON_MOUSE_UP,this._onExit,this);createjs.Tween.get(b).to({alpha:.5},750,createjs.Ease.cubicOut);var F=this;createjs.Tween.get(e).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++;F.checkPoint(x,n,g,F);F.checkStars(B,A,f,F)});$(s_oMain).trigger("save_score",c);$(s_oMain).trigger("share_event",
c)};this.unload=function(){var a=this;createjs.Tween.get(e).to({y:CANVAS_HEIGHT+l},1500,createjs.Ease.cubicIn).call(function(){a.unloadButton()});n.unload();k.unload()};this.unloadButton=function(){p.unload();p=null};this.blockAllBut=function(){p.block(!0)};this._onExit=function(){this.blockAllBut();var a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=0;d.addChild(a);s_oGame.decreaseVolumeSoundLevelComplete(!0);var b=this;createjs.Tween.get(a).to({alpha:1},
2500,createjs.Ease.cubicIn).call(function(){s_oGame.onExit();b.unload()})};this._onRollingTextScore=function(){};this._onRollingText=function(a){q[a].setActive(!0);q[a].pulseAnimation(500,SCALE_STAR_FACTOR);playSound("star",1,0)};this.checkStars=function(a,b,e,d){k=new CRollingTextController(a,b,e,4E3,EASE_CUBIC_OUT);k.addEventListener(ON_CONTROLLER_END,d._onFinishRollingStars);k.addEventListener(ON_CONTROLLER_REMOVE,d._onFinishRollingStars);k.addRollingListener(d._onRollingText,d,PERCENTAGE_STARS)};
this.checkPoint=function(a,b,e,d){n=new CRollingTextController(a,b,e,4E3,EASE_CUBIC_OUT);n.addEventListener(ON_CONTROLLER_END,d._onFinishRollingPoint);n.addEventListener(ON_CONTROLLER_REMOVE,d._onFinishRollingPoint);n.addRollingListener(d._onRollingTextScore,d,PERCENTAGE_STARS)};this._onFinishRollingPoint=function(){n.unload()};this._onFinishRollingStars=function(){k.unload()};this._init(a,g,c,f,h);return this}
function CCreditsPanel(){var a,g,c,f,h,d,e,m,b;this._init=function(){b=new createjs.Container;s_oStage.addChild(b);var p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=.5;b.addChild(p);p=s_oSpriteLibrary.getSprite("msg_box");a=createBitmap(p);b.addChild(a);a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT;a.regX=.5*p.width;a.regY=.5*p.height;d=new createjs.Shape;d.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.01;d.on("click",
this._onLogoButRelease);s_bMobile||(d.cursor="pointer");b.addChild(d);p=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(900,170,p,b);c.addEventListener(ON_MOUSE_UP,this.unload,this);h=new createjs.Text(TEXT_CREDITS_DEVELOPED,"28px "+FONT_GAME,"#000");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2+25;h.y=180;h.outline=3;b.addChild(h);f=new createjs.Text(TEXT_CREDITS_DEVELOPED,"28px "+FONT_GAME,TEXT_COLOR);f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/
2+25;f.y=h.y;b.addChild(f);p=s_oSpriteLibrary.getSprite("logo_ctl");g=createBitmap(p);g.regX=p.width/2;g.regY=p.height/2;g.x=CANVAS_WIDTH/2+25;g.y=260;b.addChild(g);m=new createjs.Text(TEXT_LINK1,"32px "+FONT_GAME,"#000");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2+25;m.y=360;m.outline=3;b.addChild(m);e=new createjs.Text(TEXT_LINK1,"32px "+FONT_GAME,TEXT_COLOR);e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2+25;e.y=m.y;b.addChild(e);this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.refreshButtonPos=function(a,b){};this.unload=function(){playSound("click",1,0);d.off("click",this._onLogoButRelease);c.unload();c=null;s_oStage.removeChild(b)};this._onLogoButRelease=function(){playSound("click",1,0);window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CPause(){var a;this._init=function(){var g=new createjs.Container;g.alpha=1;a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;var c=new createjs.Shape;c.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.hitArea=c;a.on("click",function(){});g.addChild(a);c=new createjs.Text(TEXT_PAUSE,"50px "+FONT_GAME,"#000000");c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT-130;c.textAlign="center";c.outline=5;g.addChild(c);var f=new createjs.Text(TEXT_PAUSE,
"50px "+FONT_GAME,TEXT_COLOR);f.x=c.x;f.y=c.y;f.textAlign="center";g.addChild(f);c=s_oSpriteLibrary.getSprite("but_continue");(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,c,g)).addEventListenerWithParams(ON_MOUSE_UP,this._onLeavePause,this,g);s_oStage.addChild(g)};this.unload=function(){a.off("click",function(){});s_oStage.removeChild(void 0)};this._onLeavePause=function(a){createjs.Ticker.paused=!1;createjs.Tween.get(a).to({alpha:0},300,createjs.quartIn).call(function(){s_oInterface.unloadPause();
s_oGame.unpause(!0)})};this._init();return this}
function CAreYouSurePanel(a){var g,c,f,h,d,e;this._init=function(){d=new createjs.Container;d.visible=!1;e.addChild(d);var a;a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;a.on("click",function(){});d.addChild(a);a=s_oSpriteLibrary.getSprite("msg_box");var b=createBitmap(a);b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT;b.regX=.5*a.width;b.regY=.5*a.height;d.addChild(b);g=new createjs.Text(TEXT_ARE_SURE,"40px "+FONT_GAME,"#000");g.x=CANVAS_WIDTH/2+
25;g.y=200;g.textAlign="center";g.textBaseline="middle";g.outline=5;d.addChild(g);c=new createjs.Text(g.text,"40px "+FONT_GAME,TEXT_COLOR);c.x=g.x;c.y=g.y;c.textAlign="center";c.textBaseline="middle";d.addChild(c);f=new CGfxButton(CANVAS_WIDTH/2+145,350,s_oSpriteLibrary.getSprite("but_yes"),d);f.addEventListener(ON_MOUSE_UP,this._onButYes,this);h=new CGfxButton(CANVAS_WIDTH/2-120,350,s_oSpriteLibrary.getSprite("but_exit_big"),d);h.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.show=function(){s_oGame.unpause(!1);
d.visible=!0};this._onButYes=function(){s_oGame.unpause(!0);s_oGame.onExit()};this._onButNo=function(){s_oGame.unpause(!0);d.visible=!1};this.unload=function(){f.unload();h.unload()};e=a;this._init()}
function CLevelPlatforms(a,g,c){var f,h,d,e,m;this._init=function(a,d,c){m=PLATFORM_SPEED;h=c;e=[];f=new createjs.Container;f.x=a;f.y=d;h.addChild(f);h.setChildIndex(f,2)};this.addPlatform=function(a,d,c,k,m){e[c]=new CPlatform(a,d,c,k,m,f);a>ON_VISIBLE_X&&e[c].setVisible(!1)};this.setSpeed=function(a){m=a};this.setPosition=function(a,e){f.x=a;f.y=e};this.unload=function(){h.removeChild(f);e=f=null;d.unload();d=null};this.unloadPlatform=function(){for(var a=0;a<e.length;a++)f.removeChild(e[a]);e=
null};this.repositionArrivalToLastPlatform=function(){var a=e[e.length-1];d.setPosition(a.getX()+.5*a.getWidth()+OFFSET_ARRIVAL_POS.x,a.getY()+OFFSET_ARRIVAL_POS.y)};this.getPlatformByID=function(a){return e[a]};this.moveArrival=function(){var a=d.getX()+m,e=d.getY();d.setPosition(a,e);a<ON_VISIBLE_X&&d.setVisible(!0)};this.managePlatform=function(){for(var a=0;a<e.length;a++){var d=e[a].getX()+m,c=e[a].getY();e[a].setPosition(d,c);d=e[a].getX();d<ON_VISIBLE_X&&d>-e[a].getWidth()?e[a].setVisible(!0):
e[a].setVisible(!1)}this.moveArrival()};this.createArrival=function(a){a=e.length-1+a;var c=e[a];d=new CArrival(c.getX()+.5*c.getWidth()+OFFSET_ARRIVAL_POS.x,c.getY()+OFFSET_ARRIVAL_POS.y);d.setVisible(!1);d.setIDPlatform(a)};this.collisionPlatforms=function(a){var d=a.rect,c=e[a.id].controlCollision(d);if(c.collision===COLLISION_NOTHING)for(var f=a.id;f<a.id+PREVIEW_COLLISION;f++)if(!(f>e.length-1)){var m=e[f].controlCollision(d);if(m.collision===COLLISION_PLATFORM||m.collision===COLLISION_WALL)return m.collide=
c.collide,m}return c};this.collisionArrival=function(a){!0===d.getVisible()&&d.controlCollision(a)===COLLISION_ARRIVAL&&s_oGame.platformFinished()};this.getArrival=function(){return d};this.update=function(a){this.managePlatform();var d=this.collisionPlatforms(a);this.collisionArrival(a.rect);return d};this._init(a,g,c);return this}
function CPlatform(a,g,c,f,h,d){var e,m,b,p,n,k,l,q=null,r,v,t,u=!1;this._init=function(a,d,c,f,g,h){n=h;t=c;c=s_oSpriteLibrary.getSprite("platform_"+f+"_"+g);k=createBitmap(c);k.x=a;k.y=d;r=c.width+OFFSET_PLATFORM_COL_DIMENSION[g].x;v=c.height+OFFSET_PLATFORM_COL_DIMENSION[g].y;k.regY=0;e=a+OFFSET_PLATFORM_COL_POINT[g].x;m=d+OFFSET_PLATFORM_COL_POINT[g].y;b=r;p=v;l=new createjs.Rectangle(a+OFFSET_PLATFORM_COL_POINT[g].x,d+OFFSET_PLATFORM_COL_POINT[g].y,r,v);SHOW_COLLISION_SHAPE&&(q=new createjs.Shape,
q.graphics.beginFill("#00ff00").drawRect(l.x,l.y,l.width,l.height),q.alpha=.5,n.addChild(q));n.addChild(k)};this.setPosition=function(a,b){k.x=a;k.y=b;this.rectMovement()};this.rectMovement=function(){e=k.x+OFFSET_PLATFORM_COL_POINT[h].x;m=k.y+OFFSET_PLATFORM_COL_POINT[h].y;b=r;p=v;l.setValues(e,m,b,p);SHOW_COLLISION_SHAPE&&(q&&(n.removeChild(q),q=null),q=new createjs.Shape,q.graphics.beginFill("#00ff00").drawRect(l.x,l.y,l.width,l.height),q.alpha=.5,n.addChild(q))};this.getX=function(){return k.x};
this.getY=function(){return k.y};this.getRectX=function(){return l.x};this.getWidth=function(){return r};this.setVisible=function(a){k.visible=a};this.collideYet=function(){return u};this.setCollideYet=function(a){u=a};this.unload=function(){n.removeChild(k)};this.getID=function(){return t};this.setID=function(a){t=a};this.controlCollision=function(a){if(l)return l.intersects(a)?a.x+.6*a.width>l.x&&l.y>=Math.floor(a.y)+OFFSET_HEIGHT_COLLISION_PLATFORM?(a={collision:COLLISION_PLATFORM,id:t,y:k.y,collide:u},
u=!0):a={collision:COLLISION_WALL,id:t,y:k.y}:(u=!1,a={collision:COLLISION_NOTHING,id:t,y:k.y,collide:u}),a};this._init(a,g,c,f,h,d);return this}
function CArrival(a,g){var c,f,h,d,e,m,b,p,n,k,l,q,r;this._init=function(a,g){b=new createjs.Container;b.x=a;var r=s_oSpriteLibrary.getSprite("arrival_1");n=createBitmap(r);n.regX=.5*r.width;n.regY=.5*r.height;n.x=.26*n.regX;n.y=0;b.addChild(n);r=s_oSpriteLibrary.getSprite("arrival_0");k=createBitmap(r);k.regX=.5*r.width;k.regY=.5*r.height;k.x=.26*-k.regX;k.y=0;b.y=g-.4*r.height;b.addChild(k);q=r.height+OFFSET_RECT_ARRIVAL.y;c=k.regX+OFFSET_RECT_ARRIVAL.x;f=k.regY+OFFSET_RECT_ARRIVAL.y;h=a-c;d=g-
f;e=WEIGHT_ARRIVAL;m=q;p=new createjs.Rectangle(a,g,e,m);SHOW_COLLISION_SHAPE&&(l&&(s_oStage.removeChild(l),l=null),l=new createjs.Shape,l.graphics.beginFill("#00ff00").drawRect(p.x,p.y,p.width,p.height),l.alpha=.5,s_oStage.addChild(l));s_oStage.addChild(b)};this.destroyEffect=function(){var a=this;playSound("broken_stone",1,0);playSound("hit_axe",1,0);createjs.Tween.get(n).to({y:-50},500,createjs.Ease.circOut).call(function(){createjs.Tween.get(n).to({y:CANVAS_HEIGHT},1E3,createjs.Ease.circIn)});
createjs.Tween.get(n).to({x:300,rotation:270},2500,createjs.Ease.circOut).call(function(){a.unload()});createjs.Tween.get(k).to({y:-50},500,createjs.Ease.circOut).call(function(){createjs.Tween.get(k).to({y:CANVAS_HEIGHT},1E3,createjs.Ease.circIn)});createjs.Tween.get(k).to({x:-300,rotation:-270},2500,createjs.Ease.circOut).call(function(){})};this.setVisible=function(a){b.visible=a};this.setPosition=function(a,d){b.x=a;b.y=d;this.positionRect()};this.positionRect=function(){h=b.x-c;d=b.y-f;e=WEIGHT_ARRIVAL;
m=q;p.setValues(h,d,e,m);SHOW_COLLISION_SHAPE&&(l&&(s_oStage.removeChild(l),l=null),l=new createjs.Shape,l.graphics.beginFill("#00ff00").drawRect(p.x,p.y,p.width,p.height),l.alpha=.5,s_oStage.addChild(l))};this.setIDPlatform=function(a){r=a};this.getIDPlatform=function(){return r};this.controlCollision=function(a){if(p)return p.intersects(a)?COLLISION_ARRIVAL:COLLISION_NOTHING};this.getVisible=function(){return b.visible};this.getX=function(){return b.x};this.getY=function(){return b.y};this.unload=
function(){s_oStage.removeChild(b);b=null};this._init(a,g)}function CLogo(a,g){var c;this._init=function(a,g){var d=s_oSpriteLibrary.getSprite("logo");c=createBitmap(d);c.regX=.5*d.width;c.regY=.5*d.height;c.x=a;c.y=g;s_oStage.addChild(c)};this.playAnimation=function(){createjs.Tween.get(c).to({y:LOGO_Y_POS},1E3,createjs.Ease.bounceOut)};this.unload=function(){s_oScrollStage.removeChild(c);c=null};this._init(a,g);return this}
function CParallaxObject(a,g,c){var f,h,d,e=0;this._init=function(a,b,e){d=[];f=e;h=new createjs.Container;h.x=a;h.y=b;f.addChild(h);f.setChildIndex(h,1)};this.addObject=function(a,b,e,c){var f=d.length;d.push(new CParallaxeObject(a,b,e,c,h));this.randomObjectScale(d[f]);this.randomFlipObject(d[f])};this.unload=function(){f.removeChild(h);h=null};this.unloadObject=function(){for(var a=0;a<d.length;a++)h.removeChild(d[a])};this.randomObjectScale=function(a){a.scale(Math.random()*-MIN_SCALE_PARALLAXE+
MAX_SCALE_PARALLAXE)};this.randomFlipObject=function(a){1===Math.round(1*Math.random())?a.flip(!0):a.flip(!1)};this.randomPosition=function(a){a.setPosition(Math.random()*MAX_POS_X_RANDOM_PARALLAXE+PARALLAXE_OBJ_X_REPOS,a.getY())};this.randomizeObject=function(a){this.randomPosition(a);this.randomObjectScale(a);this.randomFlipObject(a)};this.setSpeed=function(a){e=a};this.update=function(){for(var a=0;a<d.length;a++){var b=d[a].getX()+e,c=d[a].getY();d[a].setPosition(b,c);d[a].getX()<PARALLAXE_OBJ_X_RANDOMIZE&&
this.randomizeObject(d[a])}};this._init(a,g,c);return this}
function CParallaxeObject(a,g,c,f,h){var d,e,m=1;this._init=function(a,c,f,g,h){f=s_oSpriteLibrary.getSprite("parallaxe_"+f+"_"+g);e=h;d=createBitmap(f);d.regX=.5*f.width;d.regY=f.height;d.x=a;d.y=c;e.addChild(d)};this.flip=function(a){d.scaleX=a?-m:m};this.scale=function(a){m=a;d.scaleX=m;d.scaleY=m};this.setPosition=function(a,e){d.x=a;d.y=e};this.getX=function(){return d.x};this.getY=function(){return d.y};this.unload=function(){e.removeChild(d);d=null};this._init(a,g,c,f,h);return this}
function CSea(a,g,c){var f,h,d,e,m=0;this._init=function(a,c,g){d=[];f=g;h=new createjs.Container;h.x=a;h.y=c;a=s_oSpriteLibrary.getSprite("sea");e=a.width;c=0;g=POSITION_Y_SEA;for(var k=0;k<SEA_NUMBER;k++)d[k]=this.addSea(c,g,a),c+=e;f.addChild(h)};this.addSea=function(a,d,c){c=createBitmap(c);c.x=a;c.y=d;c.regX=e;h.addChild(c);return c};this.unload=function(){f.removeChild(h);h=null};this.setSpeed=function(a){m=a};this.update=function(){for(var a=0;a<d.length;a++)0>d[a].x&&(d[a].x=0===a?d[d.length-
1].x+e:d[a-1].x+e),d[a].x+=m};this._init(a,g,c);return this}
function CLevelObjects(a,g,c){var f,h,d,e;this._init=function(a,b,c){e=PLATFORM_SPEED;h=c;d=[];f=new createjs.Container;f.x=a;f.y=b;h.addChild(f);h.setChildIndex(f,3)};this.addObject=function(a,b,e,c){d[e]=new CObject(a,b,e,c,f);a>ON_VISIBLE_X&&d[e].setVisible(!1)};this.setSpeed=function(a){e=a};this.setPosition=function(a,b){f.x=a;f.y=b};this.unload=function(){h.removeChild(f);d=f=null};this.unloadObjects=function(){for(var a=0;a<d.length;a++)f.removeChild(d[a]);d=null};this.unloadObject=function(a){d[a].unload();
d.splice(a,1);for(a=0;a<d.length;a++)d[a].setID(a)};this.getObjectByID=function(a){return d[a]};this.manageObjects=function(){for(var a=0;a<d.length;a++){var b=d[a].getX()+e,c=d[a].getY();d[a].setPosition(b,c);b=d[a].getX();b<ON_VISIBLE_X&&b>-d[a].getWidth()?d[a].setVisible(!0):d[a].setVisible(!1)}};this.collisionObjects=function(a){a=a.rect;for(var b=0;b<d.length;b++)d[b].getVisible()&&d[b].controlCollision(a)};this.update=function(a){this.manageObjects();this.collisionObjects(a)};this._init(a,g,
c);return this}
function CObject(a,g,c,f,h){var d,e,m,b,p,n,k,l=null,q,r,v,t,u;this._init=function(a,c,f,g,h){p=h;t=f;u=g;f=s_oSpriteLibrary.getSprite("object_"+g);h=g=1;if(0===u){g=4;h=5;var B=new createjs.SpriteSheet({images:[f],frames:{width:f.width/h,height:f.height/g,regX:0,regY:f.height/2/g},animations:{normal:[0,19,"normal"]}});n=createSprite(B,"run",0,f.height/2/g,f.width/h,f.height/g)}else n=createBitmap(f),n.regX=0,n.regY=f.height/2;n.x=a;n.y=c;q=f.width/h;r=f.height/g;v=.5*r;d=a;e=c-v;m=q;b=r;k=new createjs.Rectangle(a,
c,q,r);SHOW_COLLISION_SHAPE&&(l=new createjs.Shape,l.graphics.beginFill("#00ff00").drawRect(k.x,k.y,k.width,k.height),l.alpha=.5,p.addChild(l));p.addChild(n)};this.setPosition=function(a,b){n.x=a;n.y=b;this.rectMovement()};this.rectMovement=function(){d=n.x;e=n.y-v;m=q;b=r;k.setValues(d,e,m,b);SHOW_COLLISION_SHAPE&&(l&&(p.removeChild(l),l=null),l=new createjs.Shape,l.graphics.beginFill("#00ff00").drawRect(k.x,k.y,k.width,k.height),l.alpha=.5,p.addChild(l))};this.getX=function(){return n.x};this.getY=
function(){return n.y};this.getRectX=function(){return k.x};this.getWidth=function(){return q};this.setVisible=function(a){n.visible=a};this.collideYet=function(){return!1};this.getVisible=function(){return n.visible};this.unload=function(){p.removeChild(n)};this.getID=function(){return t};this.setID=function(a){t=a};this.controlCollision=function(a){k&&k.intersects(a)&&(0===f?(s_oGame.addScore(COIN_SCORE),playSound("coin",1,0),s_oGame.addObtainCoin(),s_oGame.unloadObject(t)):1===f&&s_oGame.spikeCollision())};
this._init(a,g,c,f,h);return this}
function CLevelBut(a,g,c,f,h,d){var e,m,b,p=[],n=[],k,l;this._init=function(a,d,c,f){m=[];b=[];var g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=f;k=createSprite(g,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.mouseEnabled=f;k.x=a;k.y=d;k.stop();s_bMobile||(k.cursor="pointer");l.addChild(k);p.push(k);c=new createjs.Text(h,"bold 40px "+FONT_GAME,"#000000");c.x=a-2;c.y=d+13;c.textAlign=
"center";c.textBaseline="alphabetic";c.lineWidth=200;c.outline=6;l.addChild(c);a=new createjs.Text(h,"bold 40px "+FONT_GAME,TEXT_COLOR);a.x=c.x;a.y=c.y;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=200;l.addChild(a);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);l.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.viewBut=function(a){l.addChild(a)};
this.addEventListener=function(a,c,d){m[a]=c;b[a]=d};this.addEventListenerWithParams=function(a,c,d,e){m[a]=c;b[a]=d;n=e};this.ifClickable=function(){return!0===k.mouseEnabled?1:0};this.setActive=function(a,b){e=b;p[a].gotoAndStop("state_"+e);p[a].mouseEnabled=!0};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);e=!e;k.gotoAndStop("state_"+e);m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(b[ON_MOUSE_UP],n)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(b[ON_MOUSE_DOWN],
n)};this.setPosition=function(a,b){k.x=a;k.y=b};this.setVisible=function(a){k.visible=a};l=d;this._init(a,g,c,f)}
function CLevelMenu(a){var g,c,f,h,d,e=[],m,b,p,n;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));m.x=0;m.y=0;s_oStage.addChild(m);var a=s_oSpriteLibrary.getSprite("msg_box");m=createBitmap(a);m.x=.5*CANVAS_WIDTH;m.y=.5*CANVAS_HEIGHT;m.regX=.5*a.width;m.regY=.5*a.height;s_oStage.addChild(m);d=new createjs.Container;d.x=0;d.y=0;a=new createjs.Text(TEXT_SELECT_A_LEVEL," 40px "+FONT_GAME,TEXT_COLOR);a.x=CANVAS_WIDTH/2+25;a.y=176;a.textAlign="center";a.textBaseline="alphabetic";
a.lineWidth=1E3;var l;l=new createjs.Text(TEXT_SELECT_A_LEVEL," 40px "+FONT_GAME,"#000000");l.x=a.x;l.y=176;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=1E3;l.outline=3;d.addChild(l,a);s_oStage.addChild(d);for(var q=l=a=0;q<s_aLevelDiagram.length;q++,a+=85){350<a&&(a=0,l+=100);var r=535+a,v=240+l;q<s_iLevelReached?(e[q]=new CLevelBut(r,v,s_oSpriteLibrary.getSprite("but_level"),!0,q+1,s_oStage),e[q].addEventListenerWithParams(ON_MOUSE_DOWN,this._onClick,this,q),this.addStars(r,v,q)):
e[q]=new CLevelBut(535+a,240+l,s_oSpriteLibrary.getSprite("but_level"),!1,q+1,s_oStage);s_bFirstTime=!0}a=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-a.width/2-10;h=a.height/2+10;b=new CGfxButton(f,h,a,s_oStage);b.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),g=CANVAS_WIDTH-l.width/2-a.width/2-18,c=l.height/2+10,p=new CToggle(g,c,l,s_bAudioActive,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(n);createjs.Tween.get(n).to({alpha:0},1E3).call(function(){s_oStage.removeChild(n)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.addStars=function(a,b,c){var d=[];c=s_aPercentage[c];a-=26;b-=34;for(var e=s_oSpriteLibrary.getSprite("star"),f=0;f<NUMBER_OF_STARS;f++){var g=!1;c>PERCENTAGE_STARS[f]&&(g=!0);d[f]=new CStar(a,b,e,g,s_oStage);d[f].setScale(.5);a+=26}};this.unload=function(){for(var a=
0;a<s_aLevelDiagram.length;a++)e[a].unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(g-a,c+d);b.setPosition(f-a,h+d)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClick=function(a){e[a].ifClickable()&&
(s_oLevelMenu.unload(),s_oMain.gotoGame(a))};this._onExit=function(){playSound("click",1,0);s_oLevelMenu.unload();s_oMain.gotoMenu()};PERCENTAGE_STARS=a.percentage_stars;s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CConfirmPanel(a){var g=this,c=[],f=[],h=[],d,e,m=CANVAS_WIDTH/2,b=CANVAS_HEIGHT/2,p,n,k,l,q;this._init=function(){var b=s_oSpriteLibrary.getSprite("msg_box");e=new createjs.Container;e.x=m;e.y=-b.height;k=new createjs.Shape;k.graphics.beginFill("#000000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;k.on("mousedown",this._onClick);s_oStage.addChild(k);d=createBitmap(b);d.regX=b.width/2;d.regY=b.height/2;e.addChild(d);n=new createjs.Text(a," 30px "+FONT_GAME,"#000");n.x=0;n.y=-90;n.textAlign=
"center";n.textBaseline="alphabetic";n.lineWidth=400;n.outline=3;e.addChild(n);p=new createjs.Text(a," 30px "+FONT_GAME,TEXT_COLOR);p.x=0;p.y=-90;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=400;e.addChild(p);l=new CGfxButton(-100,75,s_oSpriteLibrary.getSprite("but_exit_big"),e);l.pulseAnimation();q=new CGfxButton(100,75,s_oSpriteLibrary.getSprite("but_yes"),e);s_oStage.addChild(e);this.show()};this._initListener=function(){l.addEventListener(ON_MOUSE_DOWN,this.buttonNoDown,this);
q.addEventListener(ON_MOUSE_DOWN,this.buttonYesDown,this)};this.addEventListener=function(a,b,d){c[a]=b;f[a]=d};this.buttonNoDown=function(){c[ON_BUT_NO_DOWN]&&c[ON_BUT_NO_DOWN].call(f[ON_BUT_NO_DOWN],h)};this.buttonYesDown=function(){c[ON_BUT_YES_DOWN]&&c[ON_BUT_YES_DOWN].call(f[ON_BUT_YES_DOWN],h)};this._onClick=function(){};this.show=function(){createjs.Tween.get(k).to({alpha:.7},500);createjs.Tween.get(e).to({y:b},500,createjs.Ease.quadOut).call(function(){g._initListener()})};this.unload=function(){createjs.Tween.get(e).to({y:1.5*
CANVAS_HEIGHT},500).call(function(){s_oStage.removeChild(e)});createjs.Tween.get(k).to({alpha:0},500).call(function(){s_oStage.removeChild(k)})};this._init();s_oVariousHelp=this;return this}var s_oVariousHelp=null,EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CTweenController(){this.tweenValue=function(a,g,c){return a+c*(g-a)};this.easeLinear=function(a,g,c,f){return c*a/f+g};this.easeInCubic=function(a,g,c,f){f=(a/=f)*a*a;return g+c*f};this.easeBackInQuart=function(a,g,c,f){f=(a/=f)*a;return g+c*(2*f*f+2*f*a+-3*f)};this.easeInBack=function(a,g,c,f){return c*(a/=f)*a*(2.70158*a-1.70158)+g};this.easeInSine=function(a,g,c,f){return-c*Math.cos(a/f*(Math.PI/2))+c+g};this.easeInQuad=function(a,g,c,f){return c*(a/=f)*a+g};this.easeOutCubic=function(a,
g,c,f){return c*((a=a/f-1)*a*a+1)+g};this.easeOutElastic=function(a,g,c,f){var h;if(0===a)return g;if(1===(a/=f))return g+c;h=.3*f;return c*Math.pow(2,-10*a)*Math.sin(2*(a*f-h/4)*Math.PI/h)+c+g};this.easeOutBack=function(a,g,c,f){return c*((a=a/f-1)*a*(2.70158*a+1.70158)+1)+g};this.easeInOutCubic=function(a,g,c,f){return 1>(a/=f/2)?c/2*a*a*a+g:c/2*((a-=2)*a*a+2)+g};this.easeOutQuint=function(a,g,c,f){return c*((a=a/f-1)*a*a*a*a+1)+g}}
function CRollingTextController(a,g,c,f,h){var d,e,m,b,p,n,k,l,q,r,v,t,u;this._init=function(a,b,c,d,e){q=[];r=[];p=d;this.setUpdateInfo(c);l=e;t=a;u=b};this.unload=function(){clearInterval(k)};this.setUpdateInfo=function(c){m=parseFloat(a.text);b=m+c;d=0;e=Math.round(p/FPS);n=0;var f=this;k=setInterval(function(){f.update()},FPS_TIME)};this.addEventListener=function(a,b,c){q[a]=b;r[a]=c};this.addRollingListener=function(a,b,c){q[ON_CONTROLLER_ROLL]=a;r[ON_CONTROLLER_ROLL]=b;v=[];for(a=0;a<c.length;a++)v[a]=
{step:c[a],flag:!1}};this.increaseValue=function(a){n=a};this.getTarget=function(){return t};this.update=function(){d++;if(d>e)d=0,t.text=b.toFixed(0),null!==u&&(u.text=b.toFixed(0)),clearInterval(k),null!==q[ON_CONTROLLER_END]&&q[ON_CONTROLLER_END].call(r[ON_CONTROLLER_END],this),0<n?this.setUpdateInfo(n):q[ON_CONTROLLER_REMOVE].call(r[ON_CONTROLLER_REMOVE],this);else{var a;switch(l){case EASE_BACKIN:a=s_oTweenController.easeInBack(d,0,1,e);break;case EASE_BACKOUT:a=s_oTweenController.easeOutBack(d,
0,1,e);break;case EASE_CUBIC_IN:a=s_oTweenController.easeInCubic(d,0,1,e);break;case EASE_CUBIC_OUT:a=s_oTweenController.easeOutCubic(d,0,1,e);break;case EASE_ELASTIC_OUT:a=s_oTweenController.easeOutElastic(d,0,1,e);break;case EASE_LINEAR:a=s_oTweenController.easeLinear(d,0,1,e);break;case EASE_QUART_BACKIN:a=s_oTweenController.easeBackInQuart(d,0,1,e);break;default:a=s_oTweenController.easeLinear(d,0,1,e)}a=s_oTweenController.tweenValue(m,b,a);for(var c=0;c<v.length;c++)a>v[c].step&&!v[c].flag&&
(v[c].flag=!0,null!==q[ON_CONTROLLER_ROLL]&&q[ON_CONTROLLER_ROLL].call(r[ON_CONTROLLER_ROLL],c));t.text=a.toFixed(0);null!==u&&(u.text=a.toFixed(0))}};this._init(a,g,c,f,h)}
function CStar(a,g,c,f,h){var d,e,m=1,b=1,p;this._init=function(a,b,c,f){var g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});d=f;e=createSprite(g,"state_"+d,c.width/2/2,c.height/2,c.width/2,c.height);e.x=a;e.y=b;e.stop();p.addChild(e)};this.unload=function(){p.removeChild(e)};this.setActive=function(a){d=a;e.gotoAndStop("state_"+d)};this.setPosition=function(a,b){e.x=a;e.y=b};this.setScale=
function(a){b=m=a;e.scaleX=a;e.scaleY=a};this.pulseAnimation=function(a,c){createjs.Tween.get(e).to({scaleX:m*c,scaleY:b*c},a+200,createjs.Ease.quadOut).to({scaleX:m,scaleY:b},a,createjs.Ease.quadIn)};p=h;this._init(a,g,c,f)};
