var CANVAS_WIDTH = 640;
var CANVAS_HALF_WIDTH = CANVAS_WIDTH/2;
var CANVAS_HEIGHT = 960;

var FONT = "diogenesregular";

var EDGEBOARD_X = 20;
var EDGEBOARD_Y = 95;

var FPS_TIME              = 1000/24;
var DISABLE_SOUND_MOBILE  = false;

var GAMMA_RANGE_ACCEPTED;
var CANVAS_WIDTH_RANGE_ACCEPTED;

var PLAYER_X_START        = CANVAS_WIDTH/2;
var PLAYER_Y_START        = CANVAS_HEIGHT-200;

var PLAYER_WIDTH          = 84;
var PLAYER_HEIGHT         = 107;

var PLAYER_GOD_WIDTH      = 282;
var PLAYER_GOD_HEIGHT     = 283;
var PLAYER_FALLING_WIDTH  = 78;
var PLAYER_FALLING_HEIGHT = 102;
var PLAYER_STUNNED_WIDTH  = 102;
var PLAYER_STUNNED_HEIGHT = 97;

var MAX_PLATFORM_FOR_TYPE = 26;
var PLATFORM_WIDTH        = 152;
var PLATFORM_HEIGHT       = 52;
var PLATFORM2_WIDTH       = 177;
var PLATFORM2_HEIGHT      = 127;
var PLATFORM3_WIDTH       = 117;
var PLATFORM3_HEIGHT      = 74;
var WINGS_WIDTH           = 120;
var WINGS_HEIGHT          = 106;
var NUM_ELEMENTS          = 5;

var NUM_PLATFORM_CREATED_FOR_SPRING;
var SPRING_WIDTH          = 45;
var SPRING_HEIGHT         = 33;

var COIN_WIDTH            = 31;
var COIN_HEIGHT           = 31;
var COIN_RECTANGLE_WIDTH  = 50;
var COIN_RECTANGLE_HEIGHT = 50;

var PLATFORM = 1;
var SPRING   = 2;
var COIN     = 3;
var WINGS    = 4;

var PLAYER_SPD_MAX;
var PLAYER_SPD_MIN;
var PLAYER_ACCELERATION_NO_GIROSCOPE;
var PLAYER_ACCELERATION_GIROSCOPE;
var PLAYER_DECELERATION;
var OBJECT_SPD;
var OBJECT_SPD_ORIZZONTAL;
var ACCELERATION;
var DECELERATION;
var DECELERATION_BG_GAME_OVER;
var OBJECT_SPD_MAX;
var OBJECT_SPD_MIN;
var BONUS_OCCUR;
var COIN_OCCUR;

var HEIGHT_BETWEEN_OBJECT;

var BG_INDEX       = 1;

var GOING_RIGHT    = 0;
var GOING_LEFT     = 1;

var STATE_LOADING  = 0;
var STATE_MENU     = 1;
var STATE_HELP     = 1;
var STATE_GAME     = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;