var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(d){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(d)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(d.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(d){console.log(d)}function isIOS(){for(var d="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");d.length;)if(navigator.platform===d.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(d){var m=d.toLowerCase(),h=window.document,n=h.documentElement;if(void 0===window["inner"+d])d=n["client"+d];else if(window["inner"+d]!=n["client"+d]){var f=h.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var k=h.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+m+":"+n["client"+d]+"px){body#vpw-test-b div#vpw-test-d{"+m+":7px!important}}</style>";f.appendChild(k);n.insertBefore(f,h.head);
d=7==k["offset"+d]?n["client"+d]:window["inner"+d];n.removeChild(f)}else d=window["inner"+d];return d}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var d=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<d?d:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var d;d=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var m=getSize("Width"),h=Math.min(d/CANVAS_HEIGHT,m/CANVAS_WIDTH),n=CANVAS_WIDTH*h,h=CANVAS_HEIGHT*h,f=0;h<d?(f=d-h,h+=f,n+=CANVAS_WIDTH/CANVAS_HEIGHT*f):n<m&&(f=m-n,n+=f,h+=CANVAS_HEIGHT/CANVAS_WIDTH*f);var f=d/2-h/2,k=m/2-n/2,b=CANVAS_WIDTH/n;if(k*b<-EDGEBOARD_X||f*b<-EDGEBOARD_Y)h=Math.min(d/(CANVAS_HEIGHT-2*EDGEBOARD_Y),m/(CANVAS_WIDTH-2*
EDGEBOARD_X)),n=CANVAS_WIDTH*h,h*=CANVAS_HEIGHT,f=(d-h)/2,k=(m-n)/2,b=CANVAS_WIDTH/n;s_iOffsetX=-1*k*b;s_iOffsetY=-1*f*b;0<=f&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oHelpPanel&&s_oHelpPanel.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",n+"px");$("#canvas").css("height",h+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");
$("#canvas").css("left",k+"px")}}function createBitmap(d,m,h){var n=new createjs.Bitmap(d),f=new createjs.Shape;m&&h?f.graphics.beginFill("#fff").drawRect(0,0,m,h):f.graphics.beginFill("#ff0").drawRect(0,0,d.width,d.height);n.hitArea=f;return n}function createSprite(d,m,h,n,f,k){d=null!==m?new createjs.Sprite(d,m):new createjs.Sprite(d);m=new createjs.Shape;m.graphics.beginFill("#000000").drawRect(-h,-n,f,k);d.hitArea=m;return d}
function randomFloatBetween(d,m,h){"undefined"===typeof h&&(h=2);return parseFloat(Math.min(d+Math.random()*(m-d),m).toFixed(h))}function formatTime(d){d/=1E3;var m=Math.floor(d/60);d=Math.floor(d-60*m);var h="",h=10>m?h+("0"+m+":"):h+(m+":");return 10>d?h+("0"+d):h+d}function NoClickDelay(d){this.element=d;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(d){for(var m=d.length,h,n;0<m;)n=Math.floor(Math.random()*m),m--,h=d[m],d[m]=d[n],d[n]=h;return d}
NoClickDelay.prototype={handleEvent:function(d){switch(d.type){case "touchstart":this.onTouchStart(d);break;case "touchmove":this.onTouchMove(d);break;case "touchend":this.onTouchEnd(d)}},onTouchStart:function(d){d.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(d){this.moved=!0},onTouchEnd:function(d){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){d=document.elementFromPoint(d.changedTouches[0].clientX,d.changedTouches[0].clientY);3==d.nodeType&&(d=d.parentNode);var m=document.createEvent("MouseEvents");m.initEvent("click",!0,!0);d.dispatchEvent(m)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(d){for(var m=window.location.search.substring(1).split("&"),h=0;h<m.length;h++){var n=m[h].split("=");if(n[0]==d)return n[1]}}function stopSound(d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||d.stop()}function playSound(d,m,h){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(d,{loop:h,volume:m}):null}function setVolume(d,m){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.volume=m}
function setMute(d,m){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||d.setMute(m)}function easeLinear(d,m,h,n){return h*d/n+m}function collisionWithCircle(d,m,h){var n=d.getX()-m.getX(),f=d.getY()-m.getY();return Math.sqrt(n*n+f*f)<d.getCollision()*h+m.getCollision()*h?!0:!1}function saveItem(d,m){localStorage.setItem(d,m)}function getItem(d){return localStorage.getItem(d)}function clearAllItem(){localStorage.clear()}
function CSpriteLibrary(){var d,m,h,n,f,k;this.init=function(b,g,l){h=m=0;n=b;f=g;k=l;d={}};this.addSprite=function(b,g){d.hasOwnProperty(b)||(d[b]={szPath:g,oSprite:new Image},m++)};this.getSprite=function(b){return d.hasOwnProperty(b)?d[b].oSprite:null};this._onSpritesLoaded=function(){f.call(k)};this._onSpriteLoaded=function(){n.call(k);++h===m&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in d)d[b].oSprite.oSpriteLibrary=this,d[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
d[b].oSprite.src=d[b].szPath};this.getNumSprites=function(){return m}}
var CANVAS_WIDTH=960,CANVAS_HEIGHT=1440,EDGEBOARD_X=50,EDGEBOARD_Y=130,FPS_TIME=1E3/30,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="rocks__gregular",TOT_LEVEL=10,OUTLINE_TEXT=4,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,CONFIRMATION_EXIT=0,CONFIRMATION_RESET=1,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_TWEEN_ENDED=6,ON_BUT_NO_DOWN=7,ON_BUT_YES_DOWN=8,TYPES_OF_OBJECT=19,TYPES_OF_FLOOR=12,TYPES_OF_ENEMY=1,URL_LEVELS_SETTINGS="json/levels_settings.json",
MAX_VELOCITY_LIMIT=1.5,MIN_VELOCITY_LIMIT=.5,START_SCALE_NUGGET=.6,MAX_SCALE_NUGGET=.9,BLINK_BEFORE_EXPLOSION=5,BORROW_EXPLOSION_RANGE=100,DISPLAY_SHOCK_X=80,DISPLAY_SHOCK_Y=100,MAX_TIME_SHOT_BONUS=100,OBJECTS_TYPE_PROPERTY,ENEMY_LEVEL,NODE_LEVEL,MAX_FRAME=1E3,OFFSET_OBJECTS_SECTION_X=0,OFFSET_OBJECTS_SECTION_Y=0,OFFSET_SCROLL,OFFSET_LEVEL_MAP_RIGHT=-438,OFFSET_LEVEL_MAP_LEFT=0,OFFSET_LEVEL_MAP_DOWN=-30,OFFSET_LEVEL_MAP_UP=0,TIME_REFLECT_IRON_BRICK=100,DIR_DELAY=0,OFFSET_CHARACTER=-20,OFFSET_COLLLISION_ENEMY=
-30,DIE_RESTART_LEVEL_TIME=1.5,SPAWN_BONUS_PROBABILITY,SHOW_CELL=!1,SHOW_ID_OBJ=!1,CELL_SIZE=80,CELL_HALF_SIZE=40,OFFSET_COLLISION_ENEMY,OBJECT_COLLISION,OFFSET_REG_OBJECT,OFFSET_COLLISION_OBJECT,SHOW_FPS=!1,OFFSET_COLLISION=0,STAGE_POSITION_LEVEL,WALKABLE_CELL,OBJECT_SPRITESHEET_NUM,CHARACTER_OFFSET_REG,COLLISION_DETECTION_OFFSET=.1,ITERATIONS_PER_CALCULATION=1E3,RANGE_ENEMY_DETECTION,ENEMY_OFFSET_REG;RANGE_ENEMY_DETECTION=[];OFFSET_REG_OBJECT=[];OFFSET_COLLISION_OBJECT=[];ENEMY_OFFSET_REG=[];
OFFSET_COLLISION_ENEMY=[];OFFSET_SCROLL=[];STAGE_POSITION_LEVEL=[];ENEMY_LEVEL=[];for(var i=0;i<TOT_LEVEL;i++)ENEMY_LEVEL[i]=[];OFFSET_SCROLL[0]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[0]={x:0,y:0};OFFSET_SCROLL[1]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[1]={x:0,y:0};
OFFSET_SCROLL[2]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[2]={x:0,y:0};OFFSET_SCROLL[3]={left:CANVAS_WIDTH/2+340,right:CANVAS_WIDTH/2+540,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[3]={x:-440,y:0};OFFSET_SCROLL[4]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[4]={x:0,y:0};
OFFSET_SCROLL[5]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[5]={x:0,y:0};OFFSET_SCROLL[6]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[6]={x:0,y:0};OFFSET_SCROLL[7]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-60,down:CANVAS_HEIGHT/2+140};STAGE_POSITION_LEVEL[7]={x:0,y:-40};
OFFSET_SCROLL[8]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[8]={x:0,y:0};OFFSET_SCROLL[9]={left:CANVAS_WIDTH/2-100,right:CANVAS_WIDTH/2+100,up:CANVAS_HEIGHT/2-100,down:CANVAS_HEIGHT/2+100};STAGE_POSITION_LEVEL[9]={x:0,y:0};CHARACTER_OFFSET_REG={x:-10,y:30};ENEMY_OFFSET_REG[0]={x:0,y:30};WALKABLE_CELL=[0,1,2,3,4,5,6,7,8,9,10];
OFFSET_REG_OBJECT=[{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0},{x:0,y:0}];OFFSET_COLLISION_OBJECT=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];OFFSET_COLLISION_ENEMY[0]=-40;RANGE_ENEMY_DETECTION[0]=500;
OBJECT_SPRITESHEET_NUM=[{width:0,height:0},{width:0,height:0},{width:0,height:0},{width:8,height:5,animations:{normal:[0],blink:[1,9],explosion:[10,39]}},{width:0,height:0},{width:0,height:0},{width:0,height:0},{width:10,height:2,animations:{normal:[0,19]}}];ENEMY_LEVEL[0][0]={type:0,start_cell:207};ENEMY_LEVEL[0][1]={type:0,start_cell:204};ENEMY_LEVEL[0][2]={type:0,start_cell:194};ENEMY_LEVEL[1][0]={type:0,start_cell:82};ENEMY_LEVEL[1][1]={type:0,start_cell:153};ENEMY_LEVEL[1][2]={type:0,start_cell:222};
ENEMY_LEVEL[2][0]={type:0,start_cell:220};ENEMY_LEVEL[2][1]={type:0,start_cell:223};ENEMY_LEVEL[2][2]={type:0,start_cell:247};ENEMY_LEVEL[3][0]={type:0,start_cell:152};ENEMY_LEVEL[3][1]={type:0,start_cell:206};ENEMY_LEVEL[3][2]={type:0,start_cell:200};ENEMY_LEVEL[4][0]={type:0,start_cell:176};ENEMY_LEVEL[4][1]={type:0,start_cell:261};ENEMY_LEVEL[5][0]={type:0,start_cell:159};ENEMY_LEVEL[5][1]={type:0,start_cell:211};ENEMY_LEVEL[5][2]={type:0,start_cell:244};ENEMY_LEVEL[6][0]={type:0,start_cell:84};
ENEMY_LEVEL[6][1]={type:0,start_cell:264};ENEMY_LEVEL[6][2]={type:0,start_cell:246};ENEMY_LEVEL[6][3]={type:0,start_cell:239};ENEMY_LEVEL[7][0]={type:0,start_cell:102};ENEMY_LEVEL[7][1]={type:0,start_cell:140};ENEMY_LEVEL[7][2]={type:0,start_cell:111};ENEMY_LEVEL[7][3]={type:0,start_cell:208};ENEMY_LEVEL[7][4]={type:0,start_cell:148};ENEMY_LEVEL[8][0]={type:0,start_cell:260};ENEMY_LEVEL[8][1]={type:0,start_cell:261};ENEMY_LEVEL[8][2]={type:0,start_cell:262};ENEMY_LEVEL[8][3]={type:0,start_cell:224};
ENEMY_LEVEL[8][4]={type:0,start_cell:226};ENEMY_LEVEL[8][5]={type:0,start_cell:243};ENEMY_LEVEL[8][6]={type:0,start_cell:103};ENEMY_LEVEL[9][0]={type:0,start_cell:68};ENEMY_LEVEL[9][1]={type:0,start_cell:66};ENEMY_LEVEL[9][2]={type:0,start_cell:104};ENEMY_LEVEL[9][3]={type:0,start_cell:102};ENEMY_LEVEL[9][4]={type:0,start_cell:267};ENEMY_LEVEL[9][5]={type:0,start_cell:266};ENEMY_LEVEL[9][6]={type:0,start_cell:249};ENEMY_LEVEL[9][7]={type:0,start_cell:176};TEXT_SCORE="SCORE";TEXT_SCORE_CASE="Score";
TEXT_SCORE_GAMEOVER="Total Score";TEXT_LEVEL="Level";TEXT_LEVEL_UPPERCASE="LEVEL";TEXT_GAMEOVER="GAME OVER";TEXT_COMPLETE="Complete";TEXT_GAME_COMPLETED="GAME COMPLETED";TEXT_HOW_TO_PLAY="HOW TO PLAY";TEXT_HELP_PAGE_1_PC="Use the arrow keys to move your character and dig!";TEXT_HELP_PAGE_1_MOBILE="Swipe your finger to move the character and dig!";TEXT_HELP_ENEMY="Escape from him";TEXT_SELECT_A_LEVEL="SELECT A LEVEL";TEXT_PAUSE="Pause";TEXT_HELP_TNT="Touch this to trigger an explosion";
TEXT_HELP_COIN_PART1="Collect all nuggets to complete the level and earn";TEXT_HELP_COIN_PART2="PT for each one";TEXT_HELP_SWORD="Take this to get rid of all enemies";TEXT_CONGRATULATIONS="CONGRATULATIONS!";TEXT_FINAL_SCORE="FINAL SCORE";TEXT_YOU_ARE_DEAD="YOU'RE DEAD";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_LINK1="www.codethislab.com";TEXT_RESET="ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";
TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var d,m,h,n,f,k,b;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();b=new createjs.Container;s_oStage.addChild(b)};this.unload=function(){b.removeAllChildren()};this.hide=function(){var b=this;setTimeout(function(){createjs.Tween.get(k).to({alpha:1},500).call(function(){b.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));b.addChild(g);g=s_oSpriteLibrary.getSprite("progress_bar");n=createBitmap(g);n.x=CANVAS_WIDTH/2-g.width/2;n.y=CANVAS_HEIGHT-240;b.addChild(n);d=g.width;m=g.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(n.x,n.y,1,m);b.addChild(f);n.mask=
f;h=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT-250;h.shadow=new createjs.Shadow("#000",2,2,2);h.textBaseline="alphabetic";h.textAlign="center";b.addChild(h);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;b.addChild(k)};this.refreshLoader=function(b){h.text=b+"%";f.graphics.clear();b=Math.floor(b*d/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(n.x,n.y,b,m)};this._init()}
function CMain(d){var m,h=0,n=0,f=STATE_LOADING,k,b,g;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(b){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;b=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this.loadJSON();this._loadImages();m=!0};this.soundLoaded=function(){h++;b.refreshLoader(Math.floor(h/n*100));if(h===n){b.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||
0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/game_completed.ogg","game_completed"),createjs.Sound.registerSound("./sounds/but_press.ogg","click"),createjs.Sound.registerSound("./sounds/nugget.ogg","nugget"),createjs.Sound.registerSound("./sounds/hero_death.ogg",
"hero_death"),createjs.Sound.registerSound("./sounds/dig_0.ogg","dig_0"),createjs.Sound.registerSound("./sounds/dig_1.ogg","dig_1"),createjs.Sound.registerSound("./sounds/barrel_activate.ogg","barrel_activate"),createjs.Sound.registerSound("./sounds/barrel_explosion.ogg","barrel_explosion")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/game_over.mp3",
"game_over"),createjs.Sound.registerSound("./sounds/game_completed.mp3","game_completed"),createjs.Sound.registerSound("./sounds/but_press.mp3","click"),createjs.Sound.registerSound("./sounds/nugget.mp3","nugget"),createjs.Sound.registerSound("./sounds/hero_death.mp3","hero_death"),createjs.Sound.registerSound("./sounds/dig_0.mp3","dig_0"),createjs.Sound.registerSound("./sounds/dig_1.mp3","dig_1"),createjs.Sound.registerSound("./sounds/barrel_activate.mp3","barrel_activate"),createjs.Sound.registerSound("./sounds/barrel_explosion.mp3",
"barrel_explosion")),n+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_gameover","./sprites/bg_gameover.png");s_oSpriteLibrary.addSprite("bg_win","./sprites/bg_win.png");s_oSpriteLibrary.addSprite("bg_level_0","./sprites/bg_level_0.jpg");s_oSpriteLibrary.addSprite("bg_level_1","./sprites/bg_level_1.jpg");s_oSpriteLibrary.addSprite("bg_level_2","./sprites/bg_level_2.jpg");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("icon_audio","./sprites/icon_audio.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");s_oSpriteLibrary.addSprite("but_home",
"./sprites/but_home.png");s_oSpriteLibrary.addSprite("hero_bottom","./sprites/hero_bottom.png");s_oSpriteLibrary.addSprite("hero_left","./sprites/hero_left.png");s_oSpriteLibrary.addSprite("hero_right","./sprites/hero_right.png");s_oSpriteLibrary.addSprite("hero_top","./sprites/hero_top.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("bg_level","./sprites/bg_level.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("cell",
"./sprites/cell.png");s_oSpriteLibrary.addSprite("keyboard","./sprites/keyboard.png");s_oSpriteLibrary.addSprite("hand_touch","./sprites/hand_touch.png");s_oSpriteLibrary.addSprite("swipe","./sprites/swipe.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("nugget","./sprites/nugget.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("enemy_death_back_0",
"./sprites/enemy_death_back_0.png");s_oSpriteLibrary.addSprite("enemy_death_front_0","./sprites/enemy_death_front_0.png");s_oSpriteLibrary.addSprite("but_continue_big","./sprites/but_continue_big.png");for(var b=0;b<TYPES_OF_OBJECT;b++)s_oSpriteLibrary.addSprite("object_"+b,"./sprites/object_"+b+".png");for(b=0;b<TYPES_OF_FLOOR;b++)s_oSpriteLibrary.addSprite("floor_"+b,"./sprites/floor_"+b+".png");for(b=0;b<TYPES_OF_ENEMY;b++)s_oSpriteLibrary.addSprite("enemy_bottom_"+b,"./sprites/enemy_bottom_"+
b+".png"),s_oSpriteLibrary.addSprite("enemy_top_"+b,"./sprites/enemy_top_"+b+".png"),s_oSpriteLibrary.addSprite("enemy_left_right_"+b,"./sprites/enemy_left_right_"+b+".png");n+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){h++;b.refreshLoader(Math.floor(h/n*100));if(h===n){b.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onLoadedJSON=
function(b){s_aLevelDiagram=b};this.loadJSON=function(){jQuery.getJSON(URL_LEVELS_SETTINGS,this.onLoadedJSON)};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(b){g=new CGame(k,b);f=STATE_GAME;$(s_oMain).trigger("start_session")};this.gotoLevelMenu=function(){new CLevelMenu;f=STATE_MENU};this.stopUpdate=function(){m=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=
(new Date).getTime();m=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(b){if(!1!==m){var a=(new Date).getTime();s_iTimeElaps=a-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&g.update();s_oStage.update(b)}};s_oMain=this;k=d;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iAdsLevel=1,s_iLevelReached=1,s_aScores=[],s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_oSpriteSheetLora,s_aLevelDiagram;
function CTextButton(d,m,h,n,f,k,b){var g,l,a,e,c;this._init=function(b,p,d,k,f,h,D){g=[];l=[];f=createBitmap(d);var n=Math.ceil(D/20);c=new createjs.Text(k,"bold "+D+"px "+PRIMARY_FONT,"#000000");c.textAlign="center";c.textBaseline="alphabetic";var m=c.getBounds();c.x=d.width/2+n;c.y=Math.floor(d.height/2)+m.height/3+n;e=new createjs.Text(k,"bold "+D+"px "+PRIMARY_FONT,h);e.textAlign="center";e.textBaseline="alphabetic";m=e.getBounds();e.x=d.width/2;e.y=Math.floor(d.height/2)+m.height/3;a=new createjs.Container;
a.x=b;a.y=p;a.regX=d.width/2;a.regY=d.height/2;a.addChild(f,c,e);s_oStage.addChild(a);s_bMobile||(a.cursor="pointer");this._initListener()};this.unload=function(){a.off("mousedown");a.off("pressup");s_oStage.removeChild(a)};this.setVisible=function(b){a.visible=b};this._initListener=function(){oParent=this;a.on("mousedown",this.buttonDown);a.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;l[a]=c};this.buttonRelease=function(){a.scaleX=1;a.scaleY=1;g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};
this.buttonDown=function(){a.scaleX=.9;a.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setTextPosition=function(a){e.y=a;c.y=a+2};this.setPosition=function(b,c){a.x=b;a.y=c};this.setX=function(b){a.x=b};this.setY=function(b){a.y=b};this.getButtonImage=function(){return a};this.getX=function(){return a.x};this.getY=function(){return a.y};this._init(d,m,h,n,f,k,b);return this}
function CTextToggle(d,m,h,n,f,k,b,g,l){var a=1,e,c=!1,t,p,u,w,v,x;this._init=function(a,b,c,d,k,l,f,g,h){e=!1;t=[];p=[];x=createBitmap(c);var n=Math.ceil(f/20);v=new createjs.Text(d," "+f+"px "+k,"#000000");v.textAlign="center";v.textBaseline="alphabetic";var m=v.getBounds();v.x=c.width/2+n;v.y=Math.floor(c.height/2)+m.height/3+n-7;w=new createjs.Text(d," "+f+"px "+k,l);w.textAlign="center";w.textBaseline="alphabetic";m=w.getBounds();w.x=c.width/2;w.y=Math.floor(c.height/2)+m.height/3-7;u=new createjs.Container;
u.x=a;u.y=b;u.regX=c.width/2;u.regY=c.height/2;g||(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),x=createSprite(a,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),v.x=n,v.y=n+17,w.x=0,w.y=17,u.regX=0,u.regY=0);u.addChild(x,v,w);s_bMobile||(u.cursor="pointer");h.addChild(u);this._initListener()};this.unload=function(){u.off("mousedown");u.off("pressup");l.removeChild(u)};this.setVisible=
function(a){u.visible=a};this._initListener=function(){oParent=this;u.on("mousedown",this.buttonDown);u.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){t[a]=c;p[a]=b};this.buttonRelease=function(){e||c||(u.scaleX=1*a,u.scaleY=1*a,t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(p[ON_MOUSE_UP]))};this.buttonDown=function(){e||c||(u.scaleX=.9*a,u.scaleY=.9*a,t[ON_MOUSE_DOWN]&&t[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN]))};this.enable=function(){e=!1;g||x.gotoAndStop("state_true")};this.disable=
function(){e=!0;g||x.gotoAndStop("state_false")};this.setTextPosition=function(a,c){var e=Math.ceil(b/20);v.x=a+e;v.y=c+e;w.x=a;w.y=c};this.setText=function(a){w.text=a;v.text=a};this.setPosition=function(a,c){u.x=a;u.y=c};this.setX=function(a){u.x=a};this.setY=function(a){u.y=a};this.getButtonImage=function(){return u};this.getX=function(){return u.x};this.getY=function(){return u.y};this.block=function(a){c=a};this.setScale=function(c){a=c;u.scaleX=c;u.scaleY=c};this.setScaleX=function(a){x.scaleX=
a};this._init(d,m,h,n,f,k,b,g,l);return this}
function CToggle(d,m,h,n){var f,k,b,g=[],l;this._init=function(a,e,c,d){k=[];b=[];var p=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=d;l=createSprite(p,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);l.mouseEnabled=!0;l.x=a;l.y=e;l.stop();s_bMobile||(l.cursor="pointer");s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",
this.buttonRelease);l.mouseEnabled=!1;s_oStage.removeChild(l)};this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,c){k[a]=e;b[a]=c};this.addEventListenerWithParams=function(a,e,c,d){k[a]=e;b[a]=c;g=d};this.setActive=function(a){f=a;l.gotoAndStop("state_"+f)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("click",1,0);f=!f;l.gotoAndStop("state_"+f);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(b[ON_MOUSE_UP],g)};
this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(b[ON_MOUSE_DOWN],g)};this.setPosition=function(a,b){l.x=a;l.y=b};this.setVisible=function(a){l.visible=a};this._init(d,m,h,n)}
function CNumToggle(d,m,h,n){var f,k,b,g,l,a,e,c=[];this._init=function(c,d,h,n){k=!1;b=[];g=[];l=new createjs.Container;l.x=c;l.y=d;n.addChild(l);c=s_oSpriteLibrary.getSprite("num_button");d={images:[c],framerate:5,frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}};d=new createjs.SpriteSheet(d);f=!1;a=createSprite(d,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);a.stop();c=s_oSpriteLibrary.getSprite("ball");d={images:[c],
frames:{width:c.width/NUM_DIFFERENT_BALLS,height:c.height,regX:c.width/NUM_DIFFERENT_BALLS/2,regY:c.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}};d=new createjs.SpriteSheet(d);e=createSprite(d,"red",c.width/NUM_DIFFERENT_BALLS/2,c.height/2,c.width/NUM_DIFFERENT_BALLS,c.height);e.gotoAndStop(0);e.visible=!1;l.addChild(a,e);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);n.removeChild(l)};this._initListener=
function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,e){b[a]=c;g[a]=e};this.addEventListenerWithParams=function(a,e,d,k){b[a]=e;g[a]=d;c=k};this.setActive=function(c){f=c;a.gotoAndStop("state_"+f)};this.buttonRelease=function(){k||(playSound("click",1,0),f=!f,a.gotoAndStop("state_"+f),b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(g[ON_MOUSE_UP],c))};this.buttonDown=function(){k||b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],c)};this.setPosition=
function(a,c){l.x=a;l.y=c};this.getGlobalPosition=function(){return{x:l.localToGlobal(0,0).x,y:l.localToGlobal(0,0).y}};this.block=function(a){k=a};this.setExtracted=function(a,c){e.visible=a;e.gotoAndStop(c)};this.highlight=function(){a.gotoAndPlay(0)};this.stopHighlight=function(){a.gotoAndStop(1)};this._init(d,m,h,n)}
function CGfxButton(d,m,h,n){var f,k,b,g,l=[],a,e,c,t;this._init=function(e,d,l,h){f=k=1;b=[];g=[];a=createBitmap(l);a.x=e;a.y=d;a.regX=l.width/2;a.regY=l.height/2;s_bMobile||(a.cursor="pointer");c?c.addChild(a):s_oStage.addChild(a);t=!1;this._initListener()};this.unload=function(){a.off("mousedown",this.buttonDown);a.off("pressup",this.buttonRelease);c?c.removeChild(a):s_oStage.removeChild(a)};this.setVisible=function(c){a.visible=c};this._initListener=function(){a.on("mousedown",this.buttonDown);
a.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,e){b[a]=c;g[a]=e};this.addEventListenerWithParams=function(a,c,e,d){b[a]=c;g[a]=e;l=d};this.buttonRelease=function(){t||(a.scaleX=k,a.scaleY=f,b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(g[ON_MOUSE_UP],l))};this.buttonDown=function(){t||(a.scaleX=.9*k,a.scaleY=.9*f,b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],l))};this.setScale=function(c){f=k=c;a.scaleX=c;a.scaleY=c};this.setScaleX=function(c){k=c;a.scaleX=c};this.setPosition=
function(c,b){a.x=c;a.y=b};this.setX=function(c){a.x=c};this.setY=function(c){a.y=c};this.getButtonImage=function(){return a};this.getX=function(){return a.x};this.getY=function(){return a.y};this.block=function(a){t=a};this.pulseAnimation=function(){createjs.Tween.get(a).to({scaleX:.9*k,scaleY:.9*f},850,createjs.Ease.quadOut).to({scaleX:k,scaleY:f},650,createjs.Ease.quadIn).call(function(){e.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(a).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},
140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){e.trebleAnimation()})};c=n;e=this;this._init(d,m,h,n);return this}
function CMenu(){var d,m,h,n,f,k,b,g,l,a,e=null;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var c=s_oSpriteLibrary.getSprite("icon_audio");h=CANVAS_WIDTH-c.width/2+45;n=c.height/2+15;a=new CToggle(h,n,c,s_bAudioActive);a.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}c=s_oSpriteLibrary.getSprite("but_play");k=new CGfxButton(CANVAS_WIDTH/2,584,c);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,
this);null!==getItem("LevelReached")?(s_iLevelReached=getItem("LevelReached"),s_aScores=JSON.parse(getItem("Scores")),k.setPosition(CANVAS_WIDTH/2-200,584),c=s_oSpriteLibrary.getSprite("but_continue_big"),b=new CGfxButton(CANVAS_WIDTH/2+200,584,c),b.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this),b.pulseAnimation()):(k.setPosition(CANVAS_WIDTH/2,584),this.resetArrayScores());c=s_oSpriteLibrary.getSprite("but_info");d=c.width/2+20;m=c.height/2+20;g=new CGfxButton(d,m,c);g.addEventListener(ON_MOUSE_UP,
this._onCredits,this);l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){s_oStage.removeChild(l)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){k.unload();k=null;b&&(b.unload(),b=null);s_oStage.removeChild(f);f=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),a=null;s_oMenu=null};this.exitFromCredits=function(){};this.refreshButtonPos=function(c,
b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setPosition(h-c,n+b);g.setPosition(d+c,m+b)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){new CCreditsPanel;playSound("click",1,0)};this._onButPlayRelease=function(){null===localStorage.getItem("LevelReached")?(this.unload(),playSound("click",1,0),s_oMain.gotoLevelMenu()):null===e&&(e=new CConfirmPanel(TEXT_RESET,CONFIRMATION_RESET),e.addEventListener(ON_BUT_NO_DOWN,
this._onButNo,this),e.addEventListener(ON_BUT_YES_DOWN,this._onButYes,this))};this._onButNo=function(){e.unload();e=null};this._onButYes=function(){clearAllItem();this.unload();s_iLevelReached=1;this.resetArrayScores();s_oMain.gotoLevelMenu()};this._onButContinueRelease=function(){this.unload();playSound("click",1,0);s_oMain.gotoLevelMenu()};this.resetArrayScores=function(){s_aScores=[];for(var a=0;a<s_aLevelDiagram.length;a++)s_aScores[a]=0};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(d,m){var h,n,f,k;function b(c){if(!H){37===c.keyCode?(Q="left",H=!0):39===c.keyCode?(Q="right",H=!0):38===c.keyCode?(Q="up",H=!0):40===c.keyCode&&(Q="down",H=!0);if(80===c.keyCode)if(H=!0,S)a.onContinuePauseRelease();else a.onButPauseRelease();U&&32===c.keyCode&&(s_oGame.nextLevelSpaceBar(!1),a._onButSpaceBarRelease(),H=!0)}c.preventDefault();return!1}function g(a){H&&(37===a.keyCode?H=!1:39===a.keyCode?H=!1:38===a.keyCode?H=!1:40===a.keyCode?H=!1:80===a.keyCode?H=!1:32===a.keyCode&&
(H=!1));a.preventDefault();return!1}var l,a,e=new EasyStar.js,c,t,p,u,w,v=0,x,D,E,G,P,y,B,C,z,L,M,A,N,J,R,H,V,O,S,U,T,K,I,r,Y,q,W,Q="",F,X=null;this._init=function(){setVolume(s_oSoundTrack,.4);this.setPause(!0);s_oScrollStage=new createjs.Container;s_oStage.addChild(s_oScrollStage);p=m;s_oScrollStage.x=STAGE_POSITION_LEVEL[p].x;s_oScrollStage.y=STAGE_POSITION_LEVEL[p].y;for(var c=0;c<p;c++)v+=s_aScores[c];y=LIVES;M=J=0;R=U=!1;N=L=0;O=!1;q=[];r=[];I=[];Y=[];K=[];A=0;P=DIE_RESTART_LEVEL_TIME;s_oSpriteLibrary.getSprite("object_0");
w=0;V=!0;z=B=0;this.setLevel();this.createCharacter();this.layerCharacter();I.left=!1;I.right=!1;I.up=!1;I.down=!1;!1===s_bMobile?(document.onkeydown=b,document.onkeyup=g):(t=new Hammer(s_oCanvas),t.get("swipe").set({direction:Hammer.DIRECTION_ALL}),t.get("swipe").set({velocity:.005}),t.get("swipe").set({threshold:.1}),t.on("swipeleft",function(){Q="left"}),t.on("swiperight",function(){Q="right"}),t.on("swipeup",function(){Q="up"}),t.on("swipedown",function(){Q="down"}));H=!1;x=OFFSET_SCROLL[p].left;
D=OFFSET_SCROLL[p].right;G=OFFSET_SCROLL[p].down;E=OFFSET_SCROLL[p].up;a=new CInterface;C=CELL_HALF_SIZE-2;F="";a.setTotCoin(A);a.refreshTokenMoney(J);a.refreshScore(v);0===p?a.showHelpPanel(p):a.showLevelNum(p);$(s_oMain).trigger("start_level",p)};this.setPause=function(a){S=a};this.onExit=function(){setVolume(s_oSoundTrack,1);s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",p);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad")};this.unload=function(){s_bMobile?
(t.off("swipeleft",function(){_oParent._swipeControl("left")}),t.off("swiperight",function(){_oParent._swipeControl("right")}),t.off("swipeup",function(){_oParent._swipeControl("up")}),t.off("swipedown",function(){_oParent._swipeControl("down")})):(document.onkeydown=null,document.onkeyup=null);this.unloadLevel();a.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.insertWalkableCell=function(a,c,b){for(var e=0;e<WALKABLE_CELL.length;e++)a===WALKABLE_CELL[e]&&Y.push({x:c,
y:b})};this.textIdObj=function(a,c,b){var e;e=new createjs.Text(b,"normal 32px "+PRIMARY_FONT,"#fff");e.textAlign="center";e.textBaseline="alphabetic";e.x=a;e.y=c;b=new createjs.Text(b,"normal 32px "+PRIMARY_FONT,"#000");b.textAlign="center";b.textBaseline="alphabetic";b.x=a;b.y=c;b.outline=OUTLINE_TEXT;s_oScrollStage.addChild(b,e)};this.setLevel=function(){var a=s_aLevelDiagram[p].floor,c=s_aLevelDiagram[p].object;u=c.length;z=c[0].length;var b=0,d,k;W=[];d=s_oSpriteLibrary.getSprite("bg_level_"+
s_aLevelDiagram[p].background);l?l.image=d:(l=createBitmap(d),s_oScrollStage.addChild(l));for(var f=0;f<u;f++){q[f]=[];W[f]=[];for(var g=0;g<z;g++){d=CELL_SIZE*g+CELL_HALF_SIZE;k=CELL_SIZE*f+CELL_HALF_SIZE;if(-1!==c[f][g]){var h=s_oSpriteLibrary.getSprite("object_"+c[f][g]);q[f][g]=new CCell(d,k,h,c[f][g],b,g,f);7===c[f][g]?(A++,q[f][g].setTag("item"),q[f][g].setOccupied(!0)):3===c[f][g]?(q[f][g].setTag("borrow"),q[f][g].setOccupied(!0)):q[f][g].setTag("object");q[f][g].setCollision(CELL_SIZE+OFFSET_COLLISION_OBJECT[c[f][g]])}else q[f][g]=
new CCell(d,k,null,c[f][g],b,g,f),q[f][g].setCollision(CELL_SIZE);-1!==a[f][g]&&(q[f][g].floor(a[f][g]),!0===SHOW_ID_OBJ&&this.textIdObj(d,k,b),this.insertWalkableCell(a[f][g],d,k));b++;W[f][g]=a[f][g]}}e.setGrid(W);e.setAcceptableTiles(WALKABLE_CELL);e.setIterationsPerCalculation(ITERATIONS_PER_CALCULATION);this.enemyCreation();this.stopAllEnemy()};this.canInput=function(a){R=a};this.createCharacter=function(){for(var a=0;a<u;a++)for(var b=0;b<z;b++)s_aLevelDiagram[p].character_cell_position===q[a][b].getID()&&
(c=new CCharacter(q[a][b].getX(),q[a][b].getY(),q[a][b].getRow(),q[a][b].getCol()),c.setCollision(CELL_SIZE+OFFSET_CHARACTER),f=q[a][b].getX(),k=q[a][b].getY(),h=q[a][b].getRow(),n=q[a][b].getCol(),this.layerCharacter())};this.enemyCreation=function(){for(var a=ENEMY_LEVEL[p],c=0;c<a.length;c++)for(var b=0;b<u;b++)for(var e=0;e<z;e++)if(q[b][e].getID()===a[c].start_cell){var d=q[b][e].getX(),f=q[b][e].getY();r[c]=new CEnemy(d,f,a[c].type,q[b][e].getCol(),q[b][e].getRow(),q[b+1][0].getObjectID());
r[c].setID(c);r[c].setCell(a[c].start_cell);r[c].setCollision(CELL_SIZE+OFFSET_COLLISION_ENEMY[a[c].type]);r[c].setMatrix(e,b);this.layerEnemy(c,b);this.enemyAI(c)}};this.enemyAI=function(a){var c=r[a].getMatrix(),b=Math.floor(Math.random()*Y.length);e.findPath(c.r,c.c,Math.floor(Y[b].x/CELL_SIZE),Math.floor(Y[b].y/CELL_SIZE),function(c){null===c?s_oGame.enemyAI(a):2<c.length?r[a].setTrajectory(c):s_oGame.enemyAI(a)});e.calculate()};this.displayShock=function(){var a=DISPLAY_SHOCK_X,c=DISPLAY_SHOCK_Y;
createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a),y:Math.round(Math.random()*c)},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a*.8),y:-Math.round(Math.random()*c*.8)},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a*.6),y:Math.round(Math.random()*c*.6)},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a*.4),y:-Math.round(Math.random()*c*.4)},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*
a*.2),y:Math.round(Math.random()*c*.2)},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a),y:-Math.round(Math.random()*c)},50).call(function(){createjs.Tween.get(s_oStage).to({y:0,x:0},50).call(function(){})})})})})})})};this.borrowExplosion=function(a,b){if(!S){this.displayShock();playSound("barrel_explosion",1,0);for(var e=0;e<r.length;e++){var d=r[e].getX()-a,f=r[e].getY()-b,d=Math.sqrt(d*d+f*f);d<.5*r[e].getCollision()+BORROW_EXPLOSION_RANGE&&(r[e].dead(),this.addEffectScore(r[e].getX(),
r[e].getY(),ENEMY_SCORE_COMBO[L]),this.addScoreEnemy())}d=c.getX()-a;f=c.getY()-b;d=Math.sqrt(d*d+f*f);d<.5*c.getCollision()+BORROW_EXPLOSION_RANGE&&this.characterDead();L=0}};this.addScoreEnemy=function(){this.refreshScore(ENEMY_SCORE_COMBO[L]);L<ENEMY_SCORE_COMBO.length-1&&L++};this.addEffectScore=function(a,c,b){var e,d;d=new createjs.Text("+"+b,"normal 50px "+PRIMARY_FONT,"#ffd100");d.textAlign="center";d.textBaseline="alphabetic";d.x=0;d.y=0;b=new createjs.Text("+"+b,"normal 50px "+PRIMARY_FONT,
"#000000");b.textAlign="center";b.textBaseline="alphabetic";b.x=2;b.y=2;e=new createjs.Container;e.addChild(b,d);e.alpha=0;e.x=a;e.y=c;s_oScrollStage.addChild(e);createjs.Tween.get(e).to({alpha:1,y:c-50},1E3,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(e).to({alpha:0,y:c-100},1E3,createjs.Ease.cubicIn).call(function(){s_oScrollStage.removeChild(e)})})};this._control=function(a){if(F!==a&&R&&V)switch(a){case "right":this.setCharacterState(1,"walk","right",1);break;case "left":this.setCharacterState(2,
"walk","left",-1);break;case "up":this.setCharacterState(3,"walk","up",-1);break;case "down":this.setCharacterState(0,"walk","down",1)}};this.setCharacterState=function(a,b,e,d){F=e;w=d;c.switchHero(a);c.playState(b)};this.nextLevel=function(){this.unloadLevel();p++;this.resetParamForNewLevel();this.setLevel();this.createCharacter();this.layerCharacter();a.setTotCoin(A);a.refreshTokenMoney(J);a.showLevelNum(p);$(s_oMain).trigger("start_level",p)};this.resetParamForNewLevel=function(){O=!1;M=-1;w=
0;F=null;Q="";A=J=N=0;s_oScrollStage.x=STAGE_POSITION_LEVEL[p].x;s_oScrollStage.y=STAGE_POSITION_LEVEL[p].y;x=OFFSET_SCROLL[p].left;D=OFFSET_SCROLL[p].right;G=OFFSET_SCROLL[p].down;E=OFFSET_SCROLL[p].up;a.refreshTokenMoney(J)};this.manageObjects=function(){for(var a=-1;2>a;a++)for(var b=B+a,e=-1;2>e;e++){var d=c.getRow()+e;if((!0===q[b][d].getOccupied()&&"item"===q[b][d].getTag()||"borrow"===q[b][d].getTag())&&!0===collisionWithCircle(q[b][d],c,.5)){this.collisionObject(d,b,F);break}}};this.prevDirection=
function(){var a=c.getRow()-1,b=c.getRow()+1,e=c.getCol()-1,d=c.getCol()+1;"object"!==q[c.getCol()][a].getTag()?(I.left=!0,this.prevAction("left"),K.left=q[c.getCol()][a]):(I.left=!1,this.prevCollision("left"),K.left=null);"object"!==q[c.getCol()][b].getTag()?(I.right=!0,this.prevAction("right"),K.right=q[c.getCol()][b]):(I.right=!1,this.prevCollision("right"),K.right=null);"object"!==q[e][c.getRow()].getTag()?(I.up=!0,this.prevAction("up"),K.up=q[e][c.getRow()]):(I.up=!1,this.prevCollision("up"),
K.up=null);"object"!==q[d][c.getRow()].getTag()?(I.down=!0,this.prevAction("down"),K.down=q[d][c.getRow()]):(I.down=!1,this.prevCollision("down"),K.down=null)};this.prevAction=function(a){Q===a&&(this._control(Q),Q="")};this.prevCollision=function(a){F===a&&(w=0,c.playState("idle"),F="")};this.collisionObject=function(a,b,e){if(!(0<T)){T=COLLISION_DETECTION_OFFSET;var d=q[b][a].getX(),f=q[b][a].getY(),g=q[b][a].getType();if(3===g){switch(e){case "left":c.getX()>d&&c.setPosition(q[b][a+1].getX(),c.getY());
break;case "right":c.getX()<d&&c.setPosition(q[b][a-1].getX(),c.getY());break;case "up":c.getY()>f&&c.setPosition(c.getX(),q[b+1][a].getY());break;case "down":c.getY()<f&&c.setPosition(c.getX(),q[b-1][a].getY())}w=0;c.playState("idle");q[b][a].activeExplosive()}else 7===g&&(this.addEffectCoin(q[b][a]),this.refreshScore(COIN_SCORE),A--,this.unloadObject(b,a),playSound("nugget",1,0),this.totCoins())}};this.totCoins=function(){J++;a.refreshTokenMoney(J);0<A||(this.setPause(!0),this.canInput(!1),a.levelComplete(p,
v,N),c.playState("idle"),this.stopAllEnemy(),s_iLevelReached<p+2&&(s_iLevelReached=p+2),N>s_aScores[p]&&(s_aScores[p]=N),saveItem("LevelReached",s_iLevelReached),saveItem("Scores",JSON.stringify(s_aScores)),$(s_oMain).trigger("end_level",p))};this.nextLevelSpaceBar=function(a){U=a};this.stopAllEnemy=function(){for(var a=0;a<r.length;a++)r[a].pauseAnimation()};this.scrollWorld=function(a,c){a<x&&"left"===F?s_oScrollStage.x<OFFSET_LEVEL_MAP_LEFT?(s_oScrollStage.x+=CHARACTER_SPEED,x-=CHARACTER_SPEED,
D-=CHARACTER_SPEED):x=OFFSET_SCROLL[p].left:a>D&&"right"===F?s_oScrollStage.x>OFFSET_LEVEL_MAP_RIGHT&&(s_oScrollStage.x-=CHARACTER_SPEED,x+=CHARACTER_SPEED,D+=CHARACTER_SPEED):c<E&&"up"===F?s_oScrollStage.y<OFFSET_LEVEL_MAP_UP&&(s_oScrollStage.y+=CHARACTER_SPEED,E-=CHARACTER_SPEED,G-=CHARACTER_SPEED):c>G&&"down"===F&&s_oScrollStage.y>OFFSET_LEVEL_MAP_DOWN&&(s_oScrollStage.y-=CHARACTER_SPEED,E+=CHARACTER_SPEED,G+=CHARACTER_SPEED)};this.restartLevelFromGameOver=function(){y=LIVES;a.refreshLife(y);for(var b=
v=0;b<p;b++)v+=s_aScores[b];J=0;a.refreshScore(v);$(s_oMain).trigger("restart_level",p);for(b=0;b<q.length;b++)for(var e=0;e<q[b].length;e++)q[b][e].unload(),q[b][e].unloadFloor();for(b=e=0;b<r.length;b++)r[b].unload(),e++;r.splice(0,e);c.switchHero(0);c.playState("idle");c.setPosition(f,k);c.setRow(h);c.setCol(n);F=null;Q="";a.refreshTokenMoney(J);s_oScrollStage.x=STAGE_POSITION_LEVEL[p].x;s_oScrollStage.y=STAGE_POSITION_LEVEL[p].y;x=OFFSET_SCROLL[p].left;D=OFFSET_SCROLL[p].right;G=OFFSET_SCROLL[p].down;
E=OFFSET_SCROLL[p].up;q=[];r=[];W=[];M=-1;A=w=N=0;this.setLevel();this.layerCharacter();a.showLevelNum(p)};this.startAnimEnemy=function(a){for(var c=0;c<r.length;c++)r[c].changeState(a)};this.characterDead=function(){this.setPause(!0);O=!0;playSound("hero_death",1,0);c.playState("die");this.canInput(!1)};this.enemyCollision=function(){for(var a=0;a<z;a++)for(var b=0;b<r.length;b++)if(!1===r[b].getDead()&&!0===collisionWithCircle(r[b],c,.5)){r[b].playerKilled(!0);this.characterDead();break}};this.addScoreEnemy=
function(){this.refreshScore(ENEMY_SCORE_COMBO[L]);L<ENEMY_SCORE_COMBO.length-1&&L++};this.enemyMovement=function(){for(var a=0;a<r.length;a++){var c=!1;if(!1===r[a].getDead()){for(var b=0;b<u;b++)for(var e=0;e<z;e++){if(!0===collisionWithCircle(r[a],q[b][e],.5)){if(!1===q[b][e].getOccupied()&&"item"!==q[b][e].getTag()||"object"!==q[b][e].getTag())r[a].getMatrix().c!==b&&this.layerEnemy(a,b),r[a].setCell(q[b][e].getID()),r[a].setMatrix(e,b),c=!0,this.checkNextCell(b,e,"",11);break}else"enemy"===q[b][e].getTag()&&
(q[b][e].setOccupied(!1),q[b][e].setTag("nothing"));if(c)break}this.canEnemyAttackThePlayer(a);r[a].update();r[a].getEscape()&&(r[a].setEscape(!1),r[a].changeState("walk"));r[a].getFollowMode()&&this.targetMovement(a);!0===r[a].pathFinished()&&!1===r[a].getFollowMode()&&this.enemyAI(a)}}};this.layerEnemy=function(a,c){for(var b=0;b<q[c].length;b++)if("object"===q[c][b].getTag()&&!1===q[c][b].onlyCollision()){r[a].setChildIndex(q[c][b].getObjectID());break}};this.canEnemyAttackThePlayer=function(a){r[a].getIgnorePlayer()?
r[a].canFollow(!1):r[a].canFollow(!0)};this.findTarget=function(a,b){var d=r[a].getCurrentCell(),f=r[a].getX()-c.getX(),g=r[a].getY()-c.getY();if(!0===(Math.sqrt(f*f+g*g)<.5*c.getCollision()+.5*RANGE_ENEMY_DETECTION[r[a].getType()]?!0:!1)){var f=d.r,d=d.c,k=c.getRow(),l=c.getCol();e.findPath(f,d,k,l,function(c){null===c||1>c.length?(r[a].existingPath(!1),r[a].ignorePlayer(!0),r[a].canFollow(!1),r[a].followMode(!1),s_oGame.enemyAI(a)):(r[a].existingPath(!0),!0===b&&r[a].setTrajectory(c),r[a].setTargetCoordinate(k,
l),r[a].setTargetMove(!1))})}else r[a].existingPath(!1),r[a].followMode(!1)};this.targetMovement=function(a){var b=r[a].getTargetCoordinate(),e=b.r,b=b.c;c.getCol()===b&&c.getRow()===e||r[a].targetMoved(!0)};this.timeRestartLevel=function(){P-=1/createjs.Ticker.framerate;0>=P&&(O=!1,s_oGame.restartLevel(),P=DIE_RESTART_LEVEL_TIME)};this.life=function(c){y+=c;a.refreshLife(y)};this.restartLevel=function(){if(0<y){s_oGame.life(-1);for(var b=0,e=0;e<r.length;e++)r[e].unload(),b++;r.splice(0,b);this.enemyCreation();
c.switchHero(0);c.playState("idle");c.setPosition(f,k);c.setRow(h);c.setCol(n);M=-1;this.layerCharacter();w=0;F=null;Q="";a.showLevelNum(p);this.stopAllEnemy();s_oScrollStage.x=STAGE_POSITION_LEVEL[p].x;s_oScrollStage.y=STAGE_POSITION_LEVEL[p].y;x=OFFSET_SCROLL[p].left;D=OFFSET_SCROLL[p].right;G=OFFSET_SCROLL[p].down;E=OFFSET_SCROLL[p].up}else a.refreshScore(v),a.gameOver(v),this.stopAllEnemy(),playSound("game_over",1,0)};this.layerCharacter=function(){for(var a=0;a<u;a++)if(c.getY()>q[a][0].getY()-
C&&c.getY()<q[a][0].getY()+C){B=a;for(a=0;a<q[c.getCol()].length;a++)if("object"===q[c.getCol()][a].getTag()&&!1===q[c.getCol()][a].onlyCollision()&&B!==M){c.setChildIndex(q[c.getCol()][a].getObjectID());M=c.getCol();break}break}};this.characterCell=function(){for(var a=!1,b=-1;2>b;b++){var e=c.getCol()+b;if(0<e&&e<u)for(var d=0;d<z;d++)if(!0===collisionWithCircle(c,q[e][d],.05)){a=!0;c.setCol(q[e][d].getCol());c.setRow(q[e][d].getRow());!1===q[e][d].getOccupied()&&"object"!==q[e][d].getTag()&&(c.setCell(q[e][d].getID()),
c.setCellObject(q[e][d]),"item"!==q[e][d].getTag()&&(q[e][d].setOccupied(!0),q[e][d].setTag("player")));break}else"player"===q[e][d].getTag()&&(q[e][d].setOccupied(!1),q[e][d].setTag("nothing"),this.minningFloor(c.getCellObject()))}a?(V=!0,this.prevDirection()):V=!1===I[F]?!1:!0};this.minningFloor=function(a){if(""!==F&&null!==F){var c=a.getTypeFloor(),b=Math.round(1*Math.random());"borrow"!==K[F].getTag()&&(11===K[F].getTypeFloor()?(this.setCellTypeFloor(c,F,a),this.setNextCellFloor(K[F],F),this.setNewGridAI(K[F]),
null===X&&(X=playSound("dig_"+b,.5,0),X.addEventListener("complete",this._onDigSfxComplete))):this.changeTilesCells(K[F],F,a,b))}};this.setNewGridAI=function(a){var c=a.getRow(),b=a.getCol();W[b][c]=a.getTypeFloor();e.setGrid(W)};this.checkNextCell=function(a,c,b,e){if("object"!==q[a][c].getTag()&&q[a][c].getTypeFloor()!==e)return q[a][c].setTypeFloor(4),!0};this.changeTilesCells=function(a,c,b,e){var d=b.getTypeFloor(),f=a.getTypeFloor();if(4!==d||4!==f){var g=!1;if("left"===c){switch(d){case 0:b.setTypeFloor(7);
break;case 2:b.setTypeFloor(10);break;case 6:b.setTypeFloor(9);break;case 8:b.setTypeFloor(4)}switch(f){case 1:a.setTypeFloor(7);g=!0;break;case 3:a.setTypeFloor(10);g=!0;break;case 6:a.setTypeFloor(8);g=!0;break;case 9:a.setTypeFloor(4),g=!0}}else if("right"===c){switch(d){case 1:b.setTypeFloor(7);break;case 3:b.setTypeFloor(10);break;case 6:b.setTypeFloor(8);break;case 9:b.setTypeFloor(4)}switch(f){case 0:a.setTypeFloor(7);g=!0;break;case 2:a.setTypeFloor(10);g=!0;break;case 6:a.setTypeFloor(9);
g=!0;break;case 8:a.setTypeFloor(4),g=!0}}else if("up"===c){switch(d){case 2:b.setTypeFloor(7);break;case 5:b.setTypeFloor(7);break;case 10:b.setTypeFloor(4)}switch(f){case 0:a.setTypeFloor(8);g=!0;break;case 1:a.setTypeFloor(9);g=!0;break;case 5:a.setTypeFloor(10);g=!0;break;case 7:a.setTypeFloor(4),g=!0}}else{switch(d){case 0:b.setTypeFloor(8);break;case 1:b.setTypeFloor(9);break;case 5:b.setTypeFloor(10);break;case 7:b.setTypeFloor(4)}2===f?(a.setTypeFloor(8),g=!0):3===f?(a.setTypeFloor(9),g=!0):
5===f?(a.setTypeFloor(7),g=!0):10===f&&(a.setTypeFloor(4),g=!0)}!0===g&&null===X&&(X=playSound("dig_"+e,.5,0),X.addEventListener("complete",this._onDigSfxComplete))}};this._onDigSfxComplete=function(){X=null};this.setNextCellFloor=function(a,b){"left"===b||"right"===b?a.setTypeFloor(5):"up"!==b&&"down"!==b||a.setTypeFloor(6)};this.setCellTypeFloor=function(a,b,c){if("left"===b)switch(a){case 0:c.setTypeFloor(7);break;case 2:c.setTypeFloor(10);break;case 6:c.setTypeFloor(9);break;case 8:c.setTypeFloor(4)}else if("right"===
b)switch(a){case 1:c.setTypeFloor(7);break;case 3:c.setTypeFloor(10);break;case 6:c.setTypeFloor(8);break;case 9:c.setTypeFloor(4)}else if("up"===b)switch(a){case 2:c.setTypeFloor(8);break;case 3:c.setTypeFloor(9);break;case 5:c.setTypeFloor(7);break;case 10:c.setTypeFloor(4)}else switch(a){case 0:c.setTypeFloor(8);break;case 1:c.setTypeFloor(9);break;case 5:c.setTypeFloor(10);break;case 7:c.setTypeFloor(4)}};this.refreshScore=function(c){v+=c;N+=c;a.refreshScore(v)};this.unloadLevel=function(){for(var a=
0;a<q.length;a++)for(var b=0;b<q[a].length;b++)q[a][b].unload(),q[a][b].unloadFloor();for(a=b=0;a<r.length;a++)r[a].unload(),b++;r.splice(0,b);c.unload();q=[];r=[];I=[];Y=[]};this.addEffectCoin=function(b){var c=a.getCoinSpriteCoordinate();b.addEventListenerWithParams(ON_TWEEN_ENDED,this._applyNuggetInterfaceEffect,this);b.setObjectPosition(b.getX()+s_oScrollStage.x,b.getY()+s_oScrollStage.y);b.moveToGUI(c.x,c.y)};this._applyNuggetInterfaceEffect=function(){a.applyScaleToTarget()};this.resumeEnemyAnimation=
function(){for(var a=0;a<r.length;a++)r[a].resumeAnimation()};this.stopHeroAnim=function(){c.pauseAnimation()};this.resumeHeroAnim=function(){c.playAnimation()};this.unloadObject=function(a,b){q[a][b].setOccupied(!1);q[a][b].setTag("nothing");q[a][b].unload()};this.unloadEnemy=function(a){r[a].unload();r.splice(a,1);for(a=0;a<r.length;a++)r[a].setID(a)};this.update=function(){var b=createjs.Ticker.framerate;if(!1===S){var d=c.getX(),f=c.getY();this.scrollWorld(d,f);this.layerCharacter();this.characterCell();
this.enemyMovement();this.enemyCollision();this.manageObjects();c.update(w,F);e.calculate()}!0===O&&this.timeRestartLevel();0<T&&(T-=1/b);!0===SHOW_FPS&&a.refreshFPS()};s_oGame=this;CHARACTER_SPEED=d.character_speed;ENEMY_SPEED=d.enemy_speed;LIVES=d.life_character;COIN_SCORE=d.coin_score;NUM_LEVEL_FOR_ADS=d.num_levels_for_ads;ENEMY_SCORE_COMBO=d.score_kill_enemy;this._init()}var s_oGame,s_oScrollStage;
function CInterface(){var d,m,h,n,f,k,b,g,l,a,e,c,t,p,u,w,v,x,D,E,G,P,y,B,C,z,L,M,A,N,J,R=!1;this._init=function(){var c=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-c.width/2-15;k=c.height/2+15;p=new CGfxButton(f,k,c);p.addEventListener(ON_MOUSE_UP,this._onExit,this);var C=s_oSpriteLibrary.getSprite("but_pause");l=CANVAS_WIDTH-C.width/2-c.width-15;a=C.height/2+15;t=new CGfxButton(l,a,C);t.addEventListener(ON_MOUSE_UP,this.onButPauseRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var B=
s_oSpriteLibrary.getSprite("icon_audio");b=CANVAS_WIDTH-B.width/2-C.width-c.width/2-15;g=B.height/2+15;e=new CToggle(b,g,B,s_bAudioActive);e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}G=new createjs.Container;d=CANVAS_WIDTH/2-100;m=CANVAS_HEIGHT/2+670;G.x=d;G.y=m;u=new createjs.Text(TEXT_SCORE+" 0","normal 60px "+PRIMARY_FONT,"#ffb400");u.textAlign="left";u.textBaseline="alphabetic";u.x=0;u.y=0;w=new createjs.Text(TEXT_SCORE+" 0","normal 60px "+PRIMARY_FONT,"#000000");w.textAlign="left";
w.textBaseline="alphabetic";w.x=2;w.y=2;G.addChild(w,u);s_oStage.addChild(G);h=CANVAS_WIDTH/2;n=CANVAS_HEIGHT/2-630;E=new createjs.Container;E.x=h;E.y=n;c=s_oSpriteLibrary.getSprite("life");v=createBitmap(c);v.x=0;v.y=30;v.regX=c.width;v.regY=c.height;x=new createjs.Text("x"+LIVES,"normal 60px "+PRIMARY_FONT,"#ffb400");x.textAlign="center";x.textBaseline="alphabetic";x.x=50;x.y=0;D=new createjs.Text("x"+LIVES,"normal 60px "+PRIMARY_FONT,"#000000");D.textAlign="center";D.textBaseline="alphabetic";
D.x=52;D.y=2;E.addChild(D,v,x);s_oStage.addChild(E);!0===SHOW_FPS&&(P=new createjs.Text("","normal 60px "+PRIMARY_FONT,"#ffb400"),P.textAlign="center",P.textBaseline="alphabetic",P.x=.5*CANVAS_WIDTH+-330,P.y=.5*CANVAS_HEIGHT+550,y=new createjs.Text("","normal 60px "+PRIMARY_FONT,"#000000"),y.textAlign="center",y.textBaseline="alphabetic",y.x=.5*CANVAS_WIDTH+-328,y.y=.5*CANVAS_HEIGHT+552,s_oStage.addChild(y,P));this.moneyCount();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(d,
h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||e.setPosition(b-d,g+h);t.setPosition(l-d,a+h);p.setPosition(f-d,k+h);E.y=n+h;z.y=c.y+h;G.y=m-h};this.levelComplete=function(a,b,c){a+=1;setVolume(s_oSoundTrack,.1);if(a<s_aLevelDiagram.length){var e=s_oSpriteLibrary.getSprite("bg_win");L=new CWinPanel(e,a,b,c)}else this.finishGame(b)};this.moneyCount=function(){B=new createjs.Text("0/10","normal 70px "+PRIMARY_FONT,"#ffb400");B.textAlign="center";B.textBaseline="alphabetic";B.x=.5*CANVAS_WIDTH+-280;B.y=
.5*CANVAS_HEIGHT+-630;C=new createjs.Text("0/10","normal 70px "+PRIMARY_FONT,"#000000");C.textAlign="center";C.textBaseline="alphabetic";C.x=.5*CANVAS_WIDTH+-278;C.y=.5*CANVAS_HEIGHT+-628;var a=s_oSpriteLibrary.getSprite("nugget");A=createBitmap(a);A.x=.5*CANVAS_WIDTH-390;A.y=.5*CANVAS_HEIGHT-657;A.regX=.5*a.width;A.regY=.5*a.height;A.scaleX=START_SCALE_NUGGET;A.scaleY=START_SCALE_NUGGET;z=new createjs.Container;z.x=0;z.y=0;z.addChild(C,B,A);c={x:0,y:0};s_oStage.addChild(z)};this.getCoinSpriteCoordinate=
function(){return{x:A.x+z.x,y:A.y+z.y}};this.finishGame=function(a){var b=s_oSpriteLibrary.getSprite("msg_box");M=new CCongratulations(b,a)};this._onButNextLevelRelease=function(){setVolume(s_oSoundTrack,.4);L=null;s_oGame.nextLevel()};this._onButSpaceBarRelease=function(){L&&L._onContinue()};this._onButMenuRelease=function(){M&&(M.unload(),M=null);playSound("click",1,0);s_oGame.onExit()};this.refreshScore=function(a){u.text=TEXT_SCORE+" "+a;w.text=TEXT_SCORE+" "+a};this.refreshTokenMoney=function(a){B.text=
a+"/"+J;C.text=a+"/"+J};this.setTotCoin=function(a){J=a};this.unloadPause=function(){N.unload();N=null};this.onButPauseRelease=function(){playSound("click",1,0);N=new CPause};this.onContinuePauseRelease=function(){N&&N._onLeavePause()};this.showHelpPanel=function(a){var b=s_oSpriteLibrary.getSprite("msg_box");new CHelpPanel(b,a)};this.gameOver=function(a){var b=s_oSpriteLibrary.getSprite("bg_gameover");new CGameOver(b,a)};this.unloadHelp=function(a){s_oInterface.showLevelNum(a)};this._onButRestartLevelRelease=
function(){s_oGame.restartLevelFromGameOver();p.block(!1)};this.showLevelNum=function(a){var b=a+1,c;a=new createjs.Text(TEXT_LEVEL+" "+b,"normal 90px "+PRIMARY_FONT,"#ffffff");a.textAlign="left";a.textBaseline="alphabetic";a.x=-90;a.y=0;b=new createjs.Text(TEXT_LEVEL+" "+b,"normal 90px "+PRIMARY_FONT,"#000000");b.textAlign="left";b.textBaseline="alphabetic";b.x=-90;b.y=0;b.outline=OUTLINE_TEXT+1;c=new createjs.Container;c.addChild(b,a);c.scaleX=0;c.scaleY=0;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;
s_oStage.addChild(c);createjs.Tween.get(c).to({scaleX:1,scaleY:1},1E3,createjs.Ease.elasticOut).call(function(){createjs.Tween.get(c).wait(500).to({scaleX:0,scaleY:0},1E3,createjs.Ease.elasticIn).call(function(){s_oStage.removeChild(c);s_oGame.setPause(!1);s_oGame.canInput(!0);s_oGame.startAnimEnemy("walk")})})};this.refreshLife=function(a){x.text="x"+a;D.text="x"+a};this.numLevel=function(a){};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oInterface=null};
this.applyScaleToTarget=function(){R||(R=!0,createjs.Tween.get(A).to({scaleX:MAX_SCALE_NUGGET,scaleY:MAX_SCALE_NUGGET},200).call(function(){createjs.Tween.get(A).to({scaleX:START_SCALE_NUGGET,scaleY:START_SCALE_NUGGET},200).call(function(){R=!1})}))};this.refreshFPS=function(){var a=Math.ceil(createjs.Ticker.getMeasuredFPS());P.text="FPS:"+a;y.text="FPS:"+a};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show();playSound("click",1,0)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CWinPanel(d,m,h,n){var f,k,b,g,l;this._init=function(a,e,c,d){f=new createjs.Container;k=new createjs.Container;k.y=-a.width;b=createBitmap(a);b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-100;b.regX=.5*a.width;b.regY=.5*a.height;k.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;g.on("click",function(){});f.addChild(g);a=new createjs.Text(TEXT_CONGRATULATIONS,"80px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.textBaseline="alphabetic";
a.lineWidth=500;a.lineHeight=60;a.x=CANVAS_WIDTH/2;a.y=650;a.outline=OUTLINE_TEXT;k.addChild(a);var h;h=new createjs.Text(TEXT_CONGRATULATIONS,"80px "+PRIMARY_FONT,"#ffd100");h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=500;h.lineHeight=60;h.x=CANVAS_WIDTH/2;h.y=a.y;k.addChild(h);a=new createjs.Text(TEXT_LEVEL+" "+e+" "+TEXT_COMPLETE,"normal 70px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=700;a.lineHeight=60;a.x=CANVAS_WIDTH/2;a.y=741;a.outline=
OUTLINE_TEXT;k.addChild(a);e=new createjs.Text(TEXT_LEVEL+" "+e+" "+TEXT_COMPLETE,"normal 70px "+PRIMARY_FONT,"#ffd100");e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=700;e.lineHeight=60;e.x=CANVAS_WIDTH/2;e.y=a.y;k.addChild(e);e=new createjs.Text(TEXT_LEVEL+" "+TEXT_SCORE_CASE+" "+d,"normal 60px "+PRIMARY_FONT,"#000000");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=850;e.outline=OUTLINE_TEXT;k.addChild(e);d=new createjs.Text(TEXT_LEVEL+" "+TEXT_SCORE_CASE+
" "+d,"normal 60px "+PRIMARY_FONT,"#ffd100");d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2;d.y=e.y;k.addChild(d);d=new createjs.Text(TEXT_SCORE_GAMEOVER+"  "+c,"normal 60px "+PRIMARY_FONT,"#000000");d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2;d.y=920;d.outline=OUTLINE_TEXT;k.addChild(d);e=new createjs.Text(TEXT_SCORE_GAMEOVER+"  "+c,"normal 60px "+PRIMARY_FONT,"#ffd100");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=d.y;k.addChild(e);
f.addChild(k);d=s_oSpriteLibrary.getSprite("but_continue");l=new CGfxButton(CANVAS_WIDTH/2,1196,d,k);l.addEventListener(ON_MOUSE_UP,this._onContinue,this);l.pulseAnimation();s_oStage.addChild(f);createjs.Tween.get(g).to({alpha:.5},750,createjs.Ease.cubicOut);createjs.Tween.get(k).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++});$(s_oMain).trigger("save_score",c);$(s_oMain).trigger("share_event",
c);s_oGame.nextLevelSpaceBar(!0)};this.unload=function(){b.off("click",function(){});l&&(l.unload(),l=null);s_oStage.removeChild(f)};this._onContinue=function(){var a=this;createjs.Tween.removeTweens(g);createjs.Tween.removeTweens(k);createjs.Tween.get(g).to({alpha:0},750,createjs.Ease.cubicOut);createjs.Tween.get(k).to({y:CANVAS_HEIGHT+b.regY},750,createjs.Ease.quartIn).call(function(){a.unload()});l.block(!0);s_oInterface._onButNextLevelRelease()};this._init(d,m,h,n);return this}
function CCongratulations(d,m){var h,n,f,k,b;this._init=function(d,l){s_oGame.setPause(!0);h=new createjs.Container;n=new createjs.Container;n.y=-d.height;k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;k.on("click",function(){});h.addChild(k);f=createBitmap(d);f.x=.5*CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT-100;f.regX=.5*d.width;f.regY=.5*d.height;n.addChild(f);var a;a=new createjs.Text(TEXT_CONGRATULATIONS,"normal 60px "+PRIMARY_FONT,"#000000");a.textAlign=
"center";a.textBaseline="alphabetic";a.lineWidth=300;a.lineHeight=60;a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT-120;a.outline=OUTLINE_TEXT;n.addChild(a);var e;e=new createjs.Text(TEXT_CONGRATULATIONS,"normal 60px "+PRIMARY_FONT,"#ffd100");e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=300;e.lineHeight=60;e.x=.5*CANVAS_WIDTH;e.y=a.y;n.addChild(e);a=new createjs.Text(TEXT_GAME_COMPLETED,"normal 50px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=500;
a.lineHeight=60;a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT+50;a.outline=OUTLINE_TEXT;n.addChild(a);e=new createjs.Text(TEXT_GAME_COMPLETED,"normal 50px "+PRIMARY_FONT,"#ffd100");e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;e.lineHeight=60;e.x=.5*CANVAS_WIDTH;e.y=a.y;n.addChild(e);a=new createjs.Text(TEXT_FINAL_SCORE+"\n"+l,"normal 50px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.textBaseline="alphabetic";a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT+200;a.outline=OUTLINE_TEXT;n.addChild(a);
e=new createjs.Text(TEXT_FINAL_SCORE+"\n"+l,"normal 50px "+PRIMARY_FONT,"#ffd100");e.textAlign="center";e.textBaseline="alphabetic";e.x=.5*CANVAS_WIDTH;e.y=a.y;n.addChild(e);h.addChild(n);s_oStage.addChild(h);a=s_oSpriteLibrary.getSprite("but_home");b=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+480,a,n);b.addEventListener(ON_MOUSE_UP,this._onEnd,this);createjs.Tween.get(k).to({alpha:.5},750,createjs.Ease.cubicOut);createjs.Tween.get(n).to({y:0},1500,createjs.Ease.bounceOut);playSound("game_completed",
1,0);$(s_oMain).trigger("save_score",l);$(s_oMain).trigger("share_event",l)};this.unload=function(){k.off("click",function(){});b&&(b.unload(),b=null);s_oStage.removeChild(h)};this._onEnd=function(){b.block(!0);s_oInterface._onButMenuRelease()};this._init(d,m);return this}
function CHelpPanel(d,m){var h,n,f,k=!1,b,g,l,a=null,e=null,c=null,t,p,u,w,v,x;this._init=function(d,f){x=500;v=f;b=new createjs.Container;s_oStage.addChild(b);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=.5;b.addChild(p);t=d;this.page1();w=CANVAS_WIDTH+.5*d.width;b.on("pressup",function(){var b={container:g,next_page:3};!0!==g.visible&&!0===l.visible&&(b.container=l);a?a.block(!0):e&&(e.block(!0),c.block(!0));s_oHelpPanel.onButPress(b)},null,
!0);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.page1=function(){if(g)g.visible=!0,createjs.Tween.get(g).to({x:0,alpha:1},x,createjs.Ease.cubicOut);else{g=new createjs.Container;g.x=-t.width;g.alpha=0;var b=createBitmap(d);b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT;b.regX=.5*t.width;b.regY=.5*t.height;g.addChild(b);b=new createjs.Text(TEXT_HOW_TO_PLAY,"90px "+PRIMARY_FONT,"#000000");b.textAlign="center";b.lineWidth=600;b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-100;b.outline=5;g.addChild(b);b=
new createjs.Text(TEXT_HOW_TO_PLAY,"90px "+PRIMARY_FONT,"#ffd100");b.textAlign="center";b.lineWidth=600;b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-100;g.addChild(b);if(s_bMobile){var b=TEXT_HELP_PAGE_1_MOBILE,c,e;c=s_oSpriteLibrary.getSprite("swipe");e=createBitmap(c);e.regX=.5*e.width;e.regY=.5*e.height;e.x=.5*CANVAS_WIDTH;e.y=.5*CANVAS_HEIGHT-10;g.addChild(e);var f=s_oSpriteLibrary.getSprite("hand_touch");c=createBitmap(f);c.regX=.5*f.width;c.regY=.5*f.height;c.x=.5*CANVAS_WIDTH-120;c.y=.5*CANVAS_HEIGHT+
110;g.addChild(c);u=c.x;this.handMovement(c,e)}else b=TEXT_HELP_PAGE_1_PC,c=s_oSpriteLibrary.getSprite("keyboard"),e=createBitmap(c),e.regX=.5*c.width,e.regY=.5*c.height,e.x=.5*CANVAS_WIDTH,e.y=.5*CANVAS_HEIGHT+120,g.addChild(e);c=new createjs.Text(b,"normal 40px "+PRIMARY_FONT,"#000000");c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=500;c.lineHeight=50;c.x=.5*CANVAS_WIDTH+2;c.y=.5*CANVAS_HEIGHT+302;g.addChild(c);b=new createjs.Text(b,"normal 40px "+PRIMARY_FONT,"#ffd100");b.textAlign=
"center";b.textBaseline="alphabetic";b.lineWidth=500;b.lineHeight=50;b.x=c.x-2;b.y=c.y-2;g.addChild(b);createjs.Tween.get(g).to({x:0,alpha:1},x,createjs.Ease.cubicOut);h={x:.5*CANVAS_WIDTH+340,y:.5*CANVAS_HEIGHT+330};a=this.createButtonSwitchPage(h,g,this.onButPress,1,{container:g,next_page:2});a.pulseAnimation();s_oStage.addChild(g)}};this.page2=function(){if(l)l.visible=!0,createjs.Tween.get(l).to({x:0,alpha:1},x,createjs.Ease.cubicOut);else{l=new createjs.Container;l.alpha=0;l.x=.5*-t.width;var a=
createBitmap(t);a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT;a.regX=.5*t.width;a.regY=.5*t.height;l.addChild(a);s_oStage.addChild(l);a=new createjs.Text(TEXT_HOW_TO_PLAY,"90px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.lineWidth=600;a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT-100;a.outline=5;l.addChild(a);a=new createjs.Text(TEXT_HOW_TO_PLAY,"90px "+PRIMARY_FONT,"#ffd100");a.textAlign="center";a.lineWidth=600;a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT-100;l.addChild(a);var b=.5*CANVAS_WIDTH-200,d=.5*
CANVAS_HEIGHT+70,a=new createjs.Text(TEXT_HELP_ENEMY,"normal 40px "+PRIMARY_FONT,"#000000");a.textAlign="left";a.textBaseline="alphabetic";a.lineWidth=500;a.lineHeight=50;a.x=b+2;a.y=d+2;l.addChild(a);a=new createjs.Text(TEXT_HELP_ENEMY,"normal 40px "+PRIMARY_FONT,"#ffd100");a.textAlign="left";a.textBaseline="alphabetic";a.lineWidth=500;a.lineHeight=50;a.x=b;a.y=d;l.addChild(a);var a=0,g=s_oSpriteLibrary.getSprite("enemy_left_right_"+a),k={images:[g],frames:{width:g.width/8,height:g.height/4,regX:g.width/
2/8+ENEMY_OFFSET_REG[a].x,regY:g.height/2/4+ENEMY_OFFSET_REG[a].y},animations:{walk:[0,24,"walk",1]}},k=new createjs.SpriteSheet(k),a=createSprite(k,"walk",g.width/2/8+ENEMY_OFFSET_REG[a].x,g.height/2/4+ENEMY_OFFSET_REG[a].y,g.width/8,g.height/4);a.x=b-50;a.y=d+30;l.addChild(a);b=.5*CANVAS_WIDTH-200;d=.5*CANVAS_HEIGHT+150;a=new createjs.Text(TEXT_HELP_COIN_PART1+" "+COIN_SCORE+" "+TEXT_HELP_COIN_PART2,"normal 40px "+PRIMARY_FONT,"#000000");a.textAlign="left";a.textBaseline="alphabetic";a.lineWidth=
570;a.lineHeight=50;a.x=b+2;a.y=d+2;l.addChild(a);a=new createjs.Text(TEXT_HELP_COIN_PART1+" "+COIN_SCORE+" "+TEXT_HELP_COIN_PART2,"normal 40px "+PRIMARY_FONT,"#ffd100");a.textAlign="left";a.textBaseline="alphabetic";a.lineWidth=570;a.lineHeight=50;a.x=b;a.y=d;l.addChild(a);a=7;g=s_oSpriteLibrary.getSprite("object_"+a);k={images:[g],frames:{width:g.width/OBJECT_SPRITESHEET_NUM[a].width,height:g.height/OBJECT_SPRITESHEET_NUM[a].height,regX:g.width/2/OBJECT_SPRITESHEET_NUM[a].width+OFFSET_REG_OBJECT[a].x,
regY:g.height/2/OBJECT_SPRITESHEET_NUM[a].height+OFFSET_REG_OBJECT[a].y},animations:OBJECT_SPRITESHEET_NUM[a].animations};k=new createjs.SpriteSheet(k);a=createSprite(k,"normal",g.width/2/OBJECT_SPRITESHEET_NUM[a].width+OFFSET_REG_OBJECT[a].x,g.height/2/OBJECT_SPRITESHEET_NUM[a].height+OFFSET_REG_OBJECT[a].y,g.width/OBJECT_SPRITESHEET_NUM[a].width,g.height/OBJECT_SPRITESHEET_NUM[a].height);a.x=b-70;a.y=d+60;l.addChild(a);createjs.Tween.get(l).to({x:0,alpha:1},x,createjs.Ease.cubicOut);n={x:.5*CANVAS_WIDTH-
340,y:.5*CANVAS_HEIGHT+330};e=this.createButtonSwitchPage(n,l,this.onButPress,-1,{container:l,next_page:1});f={x:.5*CANVAS_WIDTH+340,y:.5*CANVAS_HEIGHT+330};c=this.createButtonSwitchPage(f,l,this.onButPress,1,{container:l,next_page:3});c.pulseAnimation();s_oStage.addChild(l);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)}};this.onButPress=function(b){var d=w;1===b.next_page?(d=-t.width,c.block(!0),e.block(!0),a.block(!1)):2===b.next_page?(a.block(!0),e&&(c.block(!1),e.block(!1))):3===b.next_page&&(e&&
(c.block(!0),e.block(!0)),a.block(!0));playSound("click",1,0);createjs.Tween.get(b.container).to({x:d,alpha:0},x).call(function(){b.container.visible=!1;1===b.next_page?s_oHelpPanel.page1():2===b.next_page?s_oHelpPanel.page2():3!==b.next_page||k||s_oHelpPanel._onExitHelp()})};this.handMovement=function(a,b){b.x=u-10;b.scaleX=1;b.alpha=1;var c=this;createjs.Tween.get(b).to({alpha:0},500);createjs.Tween.get(a).to({x:u+240},1E3,createjs.Ease.cubicOut).call(function(){b.x=u+300;b.scaleX=-1;b.alpha=1;
createjs.Tween.get(b).to({alpha:0},500);createjs.Tween.get(a).to({x:u},1E3,createjs.Ease.cubicOut).call(function(){c.handMovement(a,b)})})};this.createButtonSwitchPage=function(a,b,c,e,d){var g=s_oSpriteLibrary.getSprite("but_continue");a=new CGfxButton(a.x,a.y,g,b);a.addEventListenerWithParams(ON_MOUSE_UP,c,this,d);a.setScaleX(e);return a};this.refreshButtonPos=function(a,b){};this.unload=function(){createjs.Tween.get(b).to({alpha:0},700,createjs.Ease.cubicOut).call(function(){a.unload();a=null;
e&&(e.unload(),e=null);c&&(c.unload(),c=null);s_oStage.removeChild(b)})};this._onExitHelp=function(){this.unload();k=!0;s_oStage.removeChild(g);s_oStage.removeChild(l);s_oInterface.unloadHelp(v)};s_oHelpPanel=this;this._init(d,m)}var s_oHelpPanel=null;
function CGameOver(d,m){var h,n,f,k,b,g;this._init=function(d,a){s_oGame.setPause(!0);h=new createjs.Container;n=new createjs.Container;n.y=-d.width;f=createBitmap(d);f.x=.5*CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT-100;f.regX=.5*d.width;f.regY=.5*d.height;n.addChild(f);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;k.on("click",function(){});h.addChild(k);var e=.5*CANVAS_WIDTH,c=.5*CANVAS_HEIGHT,m,p;p=new createjs.Text(TEXT_YOU_ARE_DEAD,"bold 40px "+
PRIMARY_FONT,"#000000");p.textAlign="center";p.textBaseline="alphabetic";p.x=e;p.y=c-50;p.outline=OUTLINE_TEXT;n.addChild(p);m=new createjs.Text(TEXT_YOU_ARE_DEAD,"bold 40px "+PRIMARY_FONT,"#ffd100");m.textAlign="center";m.textBaseline="alphabetic";m.x=e;m.y=p.y;n.addChild(m);p=new createjs.Text(TEXT_GAMEOVER,"bold 50px "+PRIMARY_FONT,"#000000");p.textAlign="center";p.textBaseline="alphabetic";p.x=e;p.y=c+50;p.outline=OUTLINE_TEXT;n.addChild(p);m=new createjs.Text(TEXT_GAMEOVER,"bold 50px "+PRIMARY_FONT,
"#ffd100");m.textAlign="center";m.textBaseline="alphabetic";m.x=e;m.y=p.y;n.addChild(m);m=new createjs.Text(TEXT_SCORE_GAMEOVER+"\n\n"+a,"bold 40px "+PRIMARY_FONT,"#000000");m.textAlign="center";m.textBaseline="alphabetic";m.x=e;m.y=c+150;m.outline=4;n.addChild(m);c=new createjs.Text(m.text,"bold 40px "+PRIMARY_FONT,"#ffd100");c.textAlign="center";c.textBaseline="alphabetic";c.x=e;c.y=m.y;n.addChild(c);h.addChild(n);h.x=0;h.y=0;s_oStage.addChild(h);e=s_oSpriteLibrary.getSprite("but_restart");c=s_oSpriteLibrary.getSprite("but_home");
b=new CGfxButton(CANVAS_WIDTH/2-250,CANVAS_HEIGHT/2+200,c,n);b.addEventListener(ON_MOUSE_UP,this._onMenu,this);g=new CGfxButton(CANVAS_WIDTH/2+250,CANVAS_HEIGHT/2+200,e,n);g.addEventListener(ON_MOUSE_UP,this._onRestart,this);g.pulseAnimation();createjs.Tween.get(k).to({alpha:.5},750,createjs.Ease.cubicOut);createjs.Tween.get(n).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++});$(s_oMain).trigger("save_score",
a);$(s_oMain).trigger("share_event",a)};this.unload=function(){k.off("click",function(){});b&&(b.unload(),b=null);s_oStage.removeChild(h)};this._onMenu=function(){this.unload();s_oInterface._onButMenuRelease()};this._onRestart=function(){this.unload();s_oInterface._onButRestartLevelRelease()};this._init(d,m);return this}
function CPause(){var d,m;this._init=function(){d=new createjs.Container;d.alpha=0;m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=.5;m.on("click",function(){});d.addChild(m);var h=new createjs.Text(TEXT_PAUSE,"120px "+PRIMARY_FONT,"#000000");h.x=.5*CANVAS_WIDTH;h.y=.5*CANVAS_HEIGHT-160;h.textAlign="center";h.outline=5;d.addChild(h);var n=new createjs.Text(TEXT_PAUSE,"120px "+PRIMARY_FONT,"#ffd100");n.x=h.x;n.y=h.y;n.textAlign="center";d.addChild(n);
h=s_oSpriteLibrary.getSprite("but_continue");(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,h,d)).addEventListener(ON_MOUSE_UP,this._onLeavePause,this);s_oStage.addChild(d);this.onPause(!0);createjs.Tween.get(d).to({alpha:1},300,createjs.quartOut).call(function(){createjs.Ticker.paused=!0})};this.onPause=function(d){s_oGame.setPause(d);!0===d?(s_oGame.stopAllEnemy(),s_oGame.stopHeroAnim(),s_oGame.canInput(!1)):(s_oGame.resumeEnemyAnimation(),s_oGame.resumeHeroAnim(),s_oGame.canInput(!0))};this.unload=
function(){m.off("click",function(){});s_oStage.removeChild(d)};this._onLeavePause=function(){playSound("click",1,0);createjs.Ticker.paused=!1;createjs.Tween.removeTweens(d);var h=this;createjs.Tween.get(d).to({alpha:0},300,createjs.quartIn).call(function(){h.onPause(!1);s_oInterface.unloadPause()})};this._init();return this}
function CAreYouSurePanel(d){var m,h,n,f,k,b,g;this._init=function(){b=new createjs.Container;b.visible=!1;g.addChild(b);k=createBitmap(s_oSpriteLibrary.getSprite("bg_level"));b.addChild(k);k.on("click",function(){});m=new createjs.Text(TEXT_ARE_SURE,"80px "+PRIMARY_FONT,"#000");m.x=CANVAS_WIDTH/2;m.y=.5*CANVAS_HEIGHT+40;m.textAlign="center";m.textBaseline="middle";m.outline=5;b.addChild(m);h=new createjs.Text(m.text,"80px "+PRIMARY_FONT,"#ffd100");h.x=m.x;h.y=m.y;h.textAlign="center";h.textBaseline=
"middle";b.addChild(h);n=new CGfxButton(CANVAS_WIDTH/2+170,m.y+180,s_oSpriteLibrary.getSprite("but_yes"),b);n.addEventListener(ON_MOUSE_UP,this._onButYes,this);f=new CGfxButton(CANVAS_WIDTH/2-170,m.y+180,s_oSpriteLibrary.getSprite("but_exit"),b);f.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.onPause=function(b){s_oGame.setPause(b);createjs.Ticker.paused=b;!0===b?(s_oGame.stopAllEnemy(),s_oGame.stopHeroAnim(),s_oGame.canInput(!1)):(s_oGame.resumeEnemyAnimation(),s_oGame.resumeHeroAnim(),
s_oGame.canInput(!0))};this.show=function(){this.onPause(!0);b.visible=!0};this.unload=function(){k.off("click",function(){});f.unload();n.unload()};this._onButYes=function(){this.unload();this.onPause(!1);playSound("click",1,0);s_oGame.onExit()};this._onButNo=function(){this.unload();this.onPause(!1);playSound("click",1,0);b.visible=!1};g=d;this._init()}
function CCell(d,m,h,n,f,k,b){var g,l,a,e,c,t,p,u,w,v,x,D,E,G;this._init=function(b,e,d,f,k,h,m){t=f;g=b;l=e;u=h;w=m;G=BLINK_BEFORE_EXPLOSION;-1!==f?(k=OFFSET_REG_OBJECT[f].x,h=OFFSET_REG_OBJECT[f].y,7===f||3===f?(x=[],D=[],E=[],k=new createjs.SpriteSheet({images:[d],frames:{width:d.width/OBJECT_SPRITESHEET_NUM[f].width,height:d.height/OBJECT_SPRITESHEET_NUM[f].height,regX:d.width/2/OBJECT_SPRITESHEET_NUM[f].width+OFFSET_REG_OBJECT[f].x,regY:d.height/2/OBJECT_SPRITESHEET_NUM[f].height+OFFSET_REG_OBJECT[f].y},
animations:OBJECT_SPRITESHEET_NUM[f].animations}),a=createSprite(k,"normal",d.width/2/OBJECT_SPRITESHEET_NUM[f].width+OFFSET_REG_OBJECT[f].x,d.height/2/OBJECT_SPRITESHEET_NUM[f].height+OFFSET_REG_OBJECT[f].y,d.width/OBJECT_SPRITESHEET_NUM[f].width,d.height/OBJECT_SPRITESHEET_NUM[f].height)):(a=createBitmap(d),a.regX=.5*d.width+k,a.regY=.5*d.height+h),v=!0,a.x=b,a.y=e,s_oScrollStage.addChild(a)):-1===f&&(v=!1,c="nothing",p=CELL_SIZE);!0===SHOW_CELL&&(f=s_oSpriteLibrary.getSprite("cell"),d=createBitmap(f),
d.x=b,d.y=e,d.regX=.5*f.width,d.regY=.5*f.height,s_oScrollStage.addChild(d))};this.activeExplosive=function(){a.gotoAndPlay("blink");playSound("barrel_active",1,BLINK_BEFORE_EXPLOSION-2);a.on("animationend",function(){G--;0===G&&(s_oGame.borrowExplosion(a.x,a.y),a.removeAllEventListeners(),s_oScrollStage.setChildIndex(s_oScrollStage.numChildren-1),a.gotoAndPlay("explosion"),a.on("animationend",function(){a.removeAllEventListeners();s_oGame.unloadObject(w,u)}))})};this.getX=function(){return g};this.getY=
function(){return l};this.floor=function(a){var b=s_oSpriteLibrary.getSprite("floor_"+a);e=new CFloor(g,l,b,a);e.setChildIndex(3)};this.getTypeFloor=function(){return e.getType()};this.setTypeFloor=function(a){e.setType(a)};this.setObjectPosition=function(b,c){a&&(a.x=b,a.y=c)};this.onlyCollision=function(){return!1};this.getTag=function(){return c};this.setTag=function(a){c=a};this.getRow=function(){return u};this.getCol=function(){return w};this.getOccupied=function(){return v};this.setOccupied=
function(a){v=a};this.getType=function(){return t};this.setType=function(a){t=a};this.getID=function(){return f};this.getCollision=function(){return p};this.setCollision=function(a){p=a};this.getObjectID=function(){return s_oScrollStage.getChildIndex(a)};this.setPosition=function(b,c){a.x=b;a.y=c};this.getTrapOut=function(){return null};this.setChildIndex=function(b){s_oScrollStage.setChildIndex(a,b)};this.unload=function(){a&&s_oScrollStage.removeChild(a)};this.unloadFloor=function(){e&&e.unload()};
this.addEventListener=function(a,b,c){x[a]=b;D[a]=c};this.addEventListenerWithParams=function(a,b,c,d){x[a]=b;D[a]=c;E=d};this.tweenEnded=function(){x[ON_TWEEN_ENDED]&&x[ON_TWEEN_ENDED].call(D[ON_TWEEN_ENDED],E)};this.moveToGUI=function(b,c,d){s_oStage.addChild(a);var e=this;createjs.Tween.get(a).to({x:a.x+50,y:a.y+50},600,createjs.Ease.quadOut).call(function(){createjs.Tween.get(a).to({x:b,y:c},700,createjs.Ease.quadOut).call(function(){s_oStage.removeChild(a);e.tweenEnded(d)})})};this.update=function(){};
this._init(d,m,h,n,f,k,b);return this}
function CCharacter(d,m,h,n){var f,k,b,g,l,a,e,c,t,p,u,w;this._init=function(a,b,d,e){var g=s_oSpriteLibrary.getSprite("hero_bottom"),k=new createjs.SpriteSheet({images:[g],frames:{width:g.width/10,height:g.height/4,regX:g.width/2/10+CHARACTER_OFFSET_REG.x,regY:g.height/2/4+CHARACTER_OFFSET_REG.y},animations:{idle:[0,11,"idle",.5],walk:[12,23,"walk",1],die:[24,37]}});p=d;u=e;f=createSprite(k,"idle",g.width/2/10+CHARACTER_OFFSET_REG.x,g.height/2/4+CHARACTER_OFFSET_REG.y,g.width/10,g.height/4);c=0;
this.createHeroLeft();this.createHeroRight();this.createHeroTop();f.x=a;f.y=b;l=CHARACTER_SPEED;s_oScrollStage.addChild(f)};this.getX=function(){switch(c){case 0:return f.x;case 1:return k.x;case 2:return b.x;case 3:return g.x}};this.getY=function(){switch(c){case 0:return f.y;case 1:return k.y;case 2:return b.y;case 3:return g.y}};this.setPosition=function(a,d){switch(c){case 0:f.x=a;f.y=d;break;case 1:k.x=a;k.y=d;break;case 2:b.x=a;b.y=d;break;case 3:g.x=a,g.y=d}};this.setCell=function(b){a=b};
this.getCell=function(){return a};this.setCellObject=function(a){w=a};this.getCellObject=function(){return w};this.getRow=function(){return p};this.getCol=function(){return u};this.setRow=function(a){p=a};this.setCol=function(a){u=a};this.setCollision=function(a){e=a};this.getCollision=function(){return e};this.playState=function(a){switch(c){case 0:f.gotoAndPlay(a);if("die"===a)f.on("animationend",this.stopStateDie);break;case 1:k.gotoAndPlay(a);if("die"===a)k.on("animationend",this.stopStateDie);
break;case 2:b.gotoAndPlay(a);if("die"===a)b.on("animationend",this.stopStateDie);break;case 3:if(g.gotoAndPlay(a),"die"===a)g.on("animationend",this.stopStateDie)}};this.stopStateDie=function(){switch(c){case 0:f.gotoAndStop(37);f.removeAllEventListeners();break;case 1:k.gotoAndStop(37);k.removeAllEventListeners();break;case 2:b.gotoAndStop(37);b.removeAllEventListeners();break;case 3:g.gotoAndStop(37),g.removeAllEventListeners()}};this.setChildIndex=function(a){t=a;switch(c){case 0:s_oScrollStage.setChildIndex(f,
t);break;case 1:s_oScrollStage.setChildIndex(k,t);break;case 2:s_oScrollStage.setChildIndex(b,t);break;case 3:s_oScrollStage.setChildIndex(g,t)}s_oScrollStage.setChildIndex(f,a)};this.unload=function(){s_oScrollStage.removeChild(f);s_oScrollStage.removeChild(k);s_oScrollStage.removeChild(b);s_oScrollStage.removeChild(g);s_oCharacter=null};this.setSpeed=function(a){l=a};this.pauseAnimation=function(){switch(c){case 0:f.stop();break;case 1:k.stop();break;case 2:b.stop();break;case 3:g.stop()}};this.playAnimation=
function(){switch(c){case 0:f.play();break;case 1:k.play();break;case 2:b.play();break;case 3:g.play()}};this.switchHero=function(a){switch(a){case 0:0!==c&&(1===c?(f.x=k.x,f.y=k.y,s_oScrollStage.removeChild(k)):2===c?(f.x=b.x,f.y=b.y,s_oScrollStage.removeChild(b)):3===c&&(f.x=g.x,f.y=g.y,s_oScrollStage.removeChild(g)),s_oScrollStage.addChild(f),s_oScrollStage.setChildIndex(f,t),c=a);break;case 1:1!==c&&(0===c?(k.x=f.x,k.y=f.y,s_oScrollStage.removeChild(f)):2===c?(k.x=b.x,k.y=b.y,s_oScrollStage.removeChild(b)):
3===c&&(k.x=g.x,k.y=g.y,s_oScrollStage.removeChild(g)),s_oScrollStage.addChild(k),s_oScrollStage.setChildIndex(k,t),c=a);break;case 2:2!==c&&(0===c?(b.x=f.x,b.y=f.y,s_oScrollStage.removeChild(f)):1===c?(b.x=k.x,b.y=k.y,s_oScrollStage.removeChild(k)):3===c&&(b.x=g.x,b.y=g.y,s_oScrollStage.removeChild(g)),s_oScrollStage.addChild(b),s_oScrollStage.setChildIndex(b,t),c=a);break;case 3:3!==c&&(0===c?(g.x=f.x,g.y=f.y,s_oScrollStage.removeChild(f)):1===c?(g.x=k.x,g.y=k.y,s_oScrollStage.removeChild(k)):2===
c&&(g.x=b.x,g.y=b.y,s_oScrollStage.removeChild(b)),s_oScrollStage.addChild(g),s_oScrollStage.setChildIndex(g,t),c=a)}};this.createHeroLeft=function(){var a=s_oSpriteLibrary.getSprite("hero_left"),b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/10,height:a.height/4,regX:a.width/2/10+CHARACTER_OFFSET_REG.x,regY:a.height/2/4+CHARACTER_OFFSET_REG.y},animations:{idle:[0,11,"idle",.5],walk:[12,23,"walk",1],die:[24,37]}});k=createSprite(b,"idle",a.width/2/10+CHARACTER_OFFSET_REG.x,a.height/
2/4+CHARACTER_OFFSET_REG.y,a.width/10,a.height/4)};this.createHeroRight=function(){var a=s_oSpriteLibrary.getSprite("hero_right"),c=new createjs.SpriteSheet({images:[a],frames:{width:a.width/10,height:a.height/4,regX:a.width/2/10+CHARACTER_OFFSET_REG.x,regY:a.height/2/4+CHARACTER_OFFSET_REG.y},animations:{idle:[0,11,"idle",.5],walk:[12,23,"walk",1],die:[24,37]}});b=createSprite(c,"idle",a.width/2/10+CHARACTER_OFFSET_REG.x,a.height/2/4+CHARACTER_OFFSET_REG.y,a.width/10,a.height/4)};this.createHeroTop=
function(){var a=s_oSpriteLibrary.getSprite("hero_top"),b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/10,height:a.height/4,regX:a.width/2/10+CHARACTER_OFFSET_REG.x,regY:a.height/2/4+CHARACTER_OFFSET_REG.y},animations:{idle:[0,11,"idle",.5],walk:[12,23,"walk",1],die:[24,37]}});g=createSprite(b,"idle",a.width/2/10+CHARACTER_OFFSET_REG.x,a.height/2/4+CHARACTER_OFFSET_REG.y,a.width/10,a.height/4)};this.update=function(a,d){switch(c){case 0:"right"===d||"left"===d?f.x+=l*a:f.y+=l*a;break;
case 1:"right"===d||"left"===d?k.x+=l*a:k.y+=l*a;break;case 2:"right"===d||"left"===d?b.x+=l*a:b.y+=l*a;break;case 3:"right"===d||"left"===d?g.x+=l*a:g.y+=l*a}};s_oCharacter=this;this._init(d,m,h,n)}var s_oCharacter;
function CEnemy(d,m,h,n,f,k){var b,g,l,a,e,c=null,t,p,u,w,v,x=!1,D=!1,E=!1,G=!0,P,y,B=!0,C=!1,z=!1,L=!1,M,A,N,J,R,H=!1,V=1,O=0,S=0,U=ENEMY_SPEED[h],T=0,K=!1,I=0,r=0;this._init=function(a,c,d,e,f,g){y=d;A=g;d=s_oSpriteLibrary.getSprite("enemy_bottom_"+d);g=new createjs.SpriteSheet({images:[d],frames:{width:d.width/8,height:d.height/4,regX:d.width/2/8+ENEMY_OFFSET_REG[y].x,regY:d.height/2/4+ENEMY_OFFSET_REG[y].y},animations:{walk:[0,24,"walk",1]}});b=createSprite(g,0,d.width/2/8+ENEMY_OFFSET_REG[y].x,
d.height/2/4+ENEMY_OFFSET_REG[y].y,d.width/8,d.height/4);this.createEnemyTop();this.createEnemyLeftRight();this.createEnemyDeathTop();this.createEnemyDeathBack();b.x=a;b.y=c;w={r:e,c:f};R=0;J=v=!1;s_oScrollStage.addChild(b);s_oScrollStage.setChildIndex(b,A);M="walk"};this.getX=function(){if(!0===B)return b.x;if(!0===C)return g.x;if(z)return l.x};this.getY=function(){if(!0===B)return b.y;if(!0===C)return g.y;if(z)return l.y};this.setPosition=function(a,c){!0===B?(b.x=a,b.y=c):!0===C?(g.x=a,g.y=c):
!0===z&&(l.x=a,l.y=c)};this.setID=function(a){t=a};this.getID=function(){return t};this.setCell=function(a){p=a};this.setChildIndex=function(a){A=a;B?s_oScrollStage.setChildIndex(b,A):C?s_oScrollStage.setChildIndex(g,A):z&&s_oScrollStage.setChildIndex(l,A)};this.getCell=function(){return p};this.createEnemyTop=function(){var a=s_oSpriteLibrary.getSprite("enemy_top_"+h),b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/8,height:a.height/4,regX:a.width/2/8+ENEMY_OFFSET_REG[y].x,regY:a.height/
2/4+ENEMY_OFFSET_REG[y].y},animations:{walk:[0,24,"walk",1]}});g=createSprite(b,0,a.width/2/8+ENEMY_OFFSET_REG[y].x,a.height/2/4+ENEMY_OFFSET_REG[y].y,a.width/8,a.height/4)};this.createEnemyLeftRight=function(){var a=s_oSpriteLibrary.getSprite("enemy_left_right_"+h),b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/8,height:a.height/4,regX:a.width/2/8+ENEMY_OFFSET_REG[y].x,regY:a.height/2/4+ENEMY_OFFSET_REG[y].y},animations:{walk:[0,24,"walk",1]}});l=createSprite(b,0,a.width/2/8+ENEMY_OFFSET_REG[y].x,
a.height/2/4+ENEMY_OFFSET_REG[y].y,a.width/8,a.height/4)};this.createEnemyDeathBack=function(){var a=s_oSpriteLibrary.getSprite("enemy_death_back_"+h),b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/8,height:a.height/3,regX:a.width/2/8+ENEMY_OFFSET_REG[y].x,regY:a.height/2/3+ENEMY_OFFSET_REG[y].y},animations:{die:[0,8,"stay",1],stay:[8],"continue":[9,22,"continue",1]}});e=createSprite(b,0,a.width/2/8+ENEMY_OFFSET_REG[y].x,a.height/2/3+ENEMY_OFFSET_REG[y].y,a.width/8,a.height/3);e.visible=
!1};this.createEnemyDeathTop=function(){var b=s_oSpriteLibrary.getSprite("enemy_death_front_"+h),c=new createjs.SpriteSheet({images:[b],frames:{width:b.width/8,height:b.height/3,regX:b.width/2/8+ENEMY_OFFSET_REG[y].x,regY:b.height/2/3+ENEMY_OFFSET_REG[y].y},animations:{die:[0,8,"stay",1],stay:[8],"continue":[9,22,"continue",1]}});a=createSprite(c,0,b.width/2/8+ENEMY_OFFSET_REG[y].x,b.height/2/3+ENEMY_OFFSET_REG[y].y,b.width/8,b.height/3);a.visible=!1};this.setCollision=function(a){u=a};this.setFound=
function(a){v=a};this.getFound=function(){return v};this.getCollision=function(){return u};this.getMatrix=function(){return w};this.pauseAnimation=function(){B?b.stop():C?g.stop():z&&l.stop()};this.resumeAnimation=function(){B?b.play():C?g.play():z&&l.play()};this.setMatrix=function(a,b){w={r:a,c:b}};this.getType=function(){return y};this.unload=function(){s_oScrollStage.removeChild(b);s_oScrollStage.removeChild(g);s_oScrollStage.removeChild(l);s_oScrollStage.removeChild(e);s_oScrollStage.removeChild(a);
s_oEnemy=c=null};this.setSpeed=function(a){};this.getCurrentCell=function(){if(null!==c)return c[O]};this.setTrajectory=function(a,b){this.newPath();c=[];for(var d=0;d<a.length;d++)c.push({r:a[d].x,c:a[d].y,y:a[d].y*CELL_SIZE+CELL_HALF_SIZE,x:a[d].x*CELL_SIZE+CELL_HALF_SIZE})};this.setPlayerKilled=function(a){};this.newPath=function(){V=1;S=O=0;U=ENEMY_SPEED[h];r=I=T=0;H=K=!1};this.pathFinished=function(){return K};this.__moveEnemy=function(){if(!0===K)H=!1;else{var a=T+s_iTimeElaps;a>=U?(a=U,H=!1,
T=a-U):T=a;var a=easeLinear(a,0,CELL_SIZE,U),d=0,e=0,d=c[O].x+I*a,e=c[O].y+r*a;!0===B?(b.x=d,b.y=e):!0===C?(g.x=d,g.y=e):!0===z&&(l.x=d,l.y=e);!1===H&&(O=S)}};this.getTargetCoordinate=function(){return P};this.setTargetCoordinate=function(a){P={r:a.r,c:a.c}};this.__followNextCellPath=function(){O+V===c.length?K=!0:(S=O+V,T=0,I=c[O].x<c[S].x?1:c[O].x>c[S].x?-1:0,r=c[O].y<c[S].y?1:c[O].y>c[S].y?-1:0,this.changeAnimDirection())};this.changeAnimDirection=function(){var a,c;if(!1===B&&1===r)!0===C?(a=
g.x,c=g.y,s_oScrollStage.removeChild(g),C=!1):!0===z&&(a=l.x,c=l.y,s_oScrollStage.removeChild(l),z=!1),B=!0,b.x=a,b.y=c,s_oScrollStage.addChild(b),s_oScrollStage.setChildIndex(b,A),b.gotoAndPlay(M);else if(!1===C&&-1===r)!0===B?(a=b.x,c=b.y,s_oScrollStage.removeChild(b),B=!1):!0===z&&(a=l.x,c=l.y,s_oScrollStage.removeChild(l),z=!1),C=!0,g.x=a,g.y=c,s_oScrollStage.addChild(g),s_oScrollStage.setChildIndex(g,A),g.gotoAndPlay(M);else if(1===I||-1===I)!1===z&&(!0===B?(a=b.x,c=b.y,s_oScrollStage.removeChild(b),
B=!1):!0===C&&(a=g.x,c=g.y,s_oScrollStage.removeChild(g),C=!1),z=!0,l.x=a,l.y=c,s_oScrollStage.addChild(l),s_oScrollStage.setChildIndex(l,A),l.gotoAndPlay(M)),l.scaleX=1===I?1:-1};this.changeState=function(a){!0===B?b.gotoAndPlay(a):!0===C?g.gotoAndPlay(a):!0===z&&l.gotoAndPlay(a);M=a};this.getChildIndex=function(){return A};this.setTargetMove=function(a){G=a};this.canFollow=function(a){x=a};this.getIgnorePlayer=function(){return J};this.ignorePlayer=function(a){J=a;!0===a&&(R=3)};this.existingPath=
function(a){D=a};this.followMode=function(a){E=a};this.getFollowMode=function(){return E};this.getEscape=function(){return N};this.setEscape=function(a){N=a};this.targetMoved=function(a){G=a};this.playerKilled=function(){};this.dead=function(){var c=!0;if(!0===B)s_oScrollStage.addChild(e),s_oScrollStage.setChildIndex(e,A),b.visible=!1,e.visible=!0,e.x=b.x,e.y=b.y,e.gotoAndPlay("die"),c=!1;else if(!0===C||z)g.visible=!1,l.visible=!1,s_oScrollStage.addChild(a),s_oScrollStage.setChildIndex(a,A),a.visible=
!0,z?(a.x=l.x,a.y=l.y):(a.x=g.x,a.y=g.y),a.gotoAndPlay("die");this.die(c);L=!0};this.die=function(b){if(b)a.on("animationend",function(){a.removeAllEventListeners();createjs.Tween.get(a).wait(500).call(function(){a.gotoAndPlay("continue");a.on("animationend",function(){createjs.Tween.removeTweens(a);s_oGame.unloadEnemy(t);a.removeAllEventListeners()})})});else e.on("animationend",function(){e.removeAllEventListeners();createjs.Tween.get(e).wait(500).call(function(){e.gotoAndPlay("continue");e.on("animationend",
function(){createjs.Tween.removeTweens(a);s_oGame.unloadEnemy(t);e.removeAllEventListeners()})})})};this.getDead=function(){return L};this.update=function(){0<R?R-=1/createjs.Ticker.framerate:J=!1;null!==c&&(!0!==H&&(!1===J&&(!0===x&&!1===E&&s_oGame.findTarget(t,!1),!0===D&&!0===x&&this.followMode(!0),!0===E&&!0===G&&s_oGame.findTarget(t,!0)),this.__followNextCellPath(),H=!0),this.__moveEnemy(),!0===E&&this.playerKilled())};s_oEnemy=this;this._init(d,m,h,n,f,k)}var s_oEnemy;
function CFloor(d,m,h,n){var f=0,k;this._init=function(b,d,h,a){f=a;k=createBitmap(h);k.regX=.5*h.width;k.regY=.5*h.height;k.x=b;k.y=d;s_oScrollStage.addChild(k)};this.getType=function(){return f};this.setType=function(b){f=b;b=s_oSpriteLibrary.getSprite("floor_"+f);k.image=b};this.setChildIndex=function(b){s_oScrollStage.setChildIndex(k,b)};this.unload=function(){s_oScrollStage.removeChild(k);k=null};this._init(d,m,h,n)}
function CLevelMenu(){var d,m,h,n,f,k=[],b,g,l,a;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));b.x=0;b.y=0;s_oStage.addChild(b);b=createBitmap(s_oSpriteLibrary.getSprite("bg_level"));s_oStage.addChild(b);f=new createjs.Container;f.x=0;f.y=0;var e;e=new createjs.Text(TEXT_SELECT_A_LEVEL," 70px "+PRIMARY_FONT,"#ffd100");e.x=CANVAS_WIDTH/2;e.y=712;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=1E3;var c;c=new createjs.Text(TEXT_SELECT_A_LEVEL," 70px "+PRIMARY_FONT,
"#000000");c.x=CANVAS_WIDTH/2;c.y=712;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=1E3;c.outline=OUTLINE_TEXT;f.addChild(c,e);s_oStage.addChild(f);for(var t=c=e=0;t<s_aLevelDiagram.length;t++,e+=135)550<e&&(e=0,c+=120),t<s_iLevelReached?(k[t]=new CLevelBut(220+e,810+c,s_oSpriteLibrary.getSprite("but_level"),!0,t+1),k[t].addEventListenerWithParams(ON_MOUSE_DOWN,this._onClick,this,t)):k[t]=new CLevelBut(220+e,810+c,s_oSpriteLibrary.getSprite("but_level"),!1,t+1),s_bFirstTime=!0;e=s_oSpriteLibrary.getSprite("but_exit");
h=CANVAS_WIDTH-e.width/2-15;n=e.height/2+15;g=new CGfxButton(h,n,e);g.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=s_oSpriteLibrary.getSprite("icon_audio"),d=CANVAS_WIDTH-c.width/2-e.width/2-15,m=c.height/2+15,l=new CToggle(d,m,c,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(a);createjs.Tween.get(a).to({alpha:0},
1E3).call(function(){s_oStage.removeChild(a)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<s_aLevelDiagram.length;a++)k[a].unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(d-a,m+b);g.setPosition(h-a,n+b)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClick=function(a){k[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoGame(a))};this._onExit=function(){playSound("click",1,0);s_oLevelMenu.unload();s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(d,m,h,n,f){var k,b,g,l=[],a=[],e;this._init=function(a,d,h,m){b=[];g=[];var n=new createjs.SpriteSheet({images:[h],frames:{width:h.width/2,height:h.height,regX:h.width/2/2,regY:h.height/2},animations:{state_true:[0],state_false:[1]}});k=m;e=createSprite(n,"state_"+k,h.width/2/2,h.height/2,h.width/2,h.height);e.mouseEnabled=m;e.x=a;e.y=d;e.stop();s_bMobile||(e.cursor="pointer");s_oStage.addChild(e);l.push(e);h=new createjs.Text(f,"bold 70px "+PRIMARY_FONT,"#000000");h.x=a;h.y=d+
20;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=200;h.outline=6;s_oStage.addChild(h);h=new createjs.Text(f,"bold 70px "+PRIMARY_FONT,"#6a3006");h.x=a;h.y=d+20;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=200;s_oStage.addChild(h);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};
this.viewBut=function(a){s_oStage.addChild(a)};this.addEventListener=function(a,d,e){b[a]=d;g[a]=e};this.addEventListenerWithParams=function(c,d,e,f){b[c]=d;g[c]=e;a=f};this.ifClickable=function(){return!0===e.mouseEnabled?1:0};this.setActive=function(a,b){k=b;l[a].gotoAndStop("state_"+k);l[a].mouseEnabled=!0};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;playSound("click",1,0);k=!k;e.gotoAndStop("state_"+k);b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(g[ON_MOUSE_UP],a)};this.buttonDown=function(){e.scaleX=
.9;e.scaleY=.9;b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],a)};this.setPosition=function(a,b){e.x=a;e.y=b};this.setVisible=function(a){e.visible=a};this._init(d,m,h,n)}
function CCreditsPanel(){var d,m,h,n,f,k,b,g,l;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);var a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.8;l.addChild(a);a=s_oSpriteLibrary.getSprite("msg_box");d=createBitmap(a);l.addChild(d);d.x=.5*CANVAS_WIDTH;d.y=680;d.regX=.5*a.width;d.regY=.5*a.height;k=new createjs.Shape;k.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.01;k.on("click",this._onLogoButRelease);
s_bMobile||(k.cursor="pointer");l.addChild(k);a=s_oSpriteLibrary.getSprite("but_exit");h=new CGfxButton(820,634,a,l);h.addEventListener(ON_MOUSE_UP,this.unload,this);f=new createjs.Text(TEXT_CREDITS_DEVELOPED,"60px "+PRIMARY_FONT,"#000");f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/2;f.y=770;f.outline=OUTLINE_TEXT;l.addChild(f);n=new createjs.Text(TEXT_CREDITS_DEVELOPED,"60px "+PRIMARY_FONT,"#ffd100");n.textAlign="center";n.textBaseline="alphabetic";n.x=CANVAS_WIDTH/2;n.y=f.y;
l.addChild(n);a=s_oSpriteLibrary.getSprite("logo_ctl");m=createBitmap(a);m.regX=a.width/2;m.regY=a.height/2;m.x=CANVAS_WIDTH/2;m.y=850;l.addChild(m);g=new createjs.Text(TEXT_LINK1,"60px "+PRIMARY_FONT,"#000");g.textAlign="center";g.textBaseline="alphabetic";g.x=CANVAS_WIDTH/2;g.y=980;g.outline=OUTLINE_TEXT;l.addChild(g);b=new createjs.Text(TEXT_LINK1,"60px "+PRIMARY_FONT,"#ffd100");b.textAlign="center";b.textBaseline="alphabetic";b.x=CANVAS_WIDTH/2;b.y=g.y;l.addChild(b);this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.refreshButtonPos=function(a,b){};this.unload=function(){playSound("click",1,0);k.off("click",this._onLogoButRelease);h.unload();h=null;s_oStage.removeChild(l);s_oMenu.exitFromCredits()};this._onLogoButRelease=function(){playSound("click",1,0);window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CConfirmPanel(d){var m=this,h=[],n=[],f=[],k,b,g=CANVAS_WIDTH/2,l=CANVAS_HEIGHT/2,a,e,c,t;this._init=function(){b=new createjs.Container;b.x=g;b.y=1.5*CANVAS_HEIGHT;e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=.7;e.on("mousedown",this._onClick);s_oStage.addChild(e);var f=s_oSpriteLibrary.getSprite("msg_box");k=createBitmap(f);k.regX=f.width/2;k.regY=f.height/2;b.addChild(k);a=new createjs.Text(d," 60px "+PRIMARY_FONT,"#000");a.x=2;
a.y=32;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=500;b.addChild(a);a=new createjs.Text(d," 60px "+PRIMARY_FONT,"#ffd100");a.x=0;a.y=30;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=500;b.addChild(a);c=new CGfxButton(-200,320,s_oSpriteLibrary.getSprite("but_exit"),b);c.pulseAnimation();t=new CGfxButton(200,320,s_oSpriteLibrary.getSprite("but_yes"),b);s_oStage.addChild(b);this.show()};this._initListener=function(){c.addEventListener(ON_MOUSE_DOWN,this.buttonNoDown,
this);t.addEventListener(ON_MOUSE_DOWN,this.buttonYesDown,this)};this.addEventListener=function(a,b,c){h[a]=b;n[a]=c};this.buttonNoDown=function(){playSound("click",1,0);h[ON_BUT_NO_DOWN]&&h[ON_BUT_NO_DOWN].call(n[ON_BUT_NO_DOWN],f)};this.buttonYesDown=function(){playSound("click",1,0);h[ON_BUT_YES_DOWN]&&h[ON_BUT_YES_DOWN].call(n[ON_BUT_YES_DOWN],f)};this._onClick=function(){};this.show=function(){createjs.Tween.get(b).to({y:l},500,createjs.Ease.quadOut).call(function(){m._initListener()})};this.unload=
function(){createjs.Tween.get(b).to({y:1.5*CANVAS_HEIGHT},500).call(function(){s_oStage.removeChild(b)});createjs.Tween.get(e).to({alpha:0},500).call(function(){s_oStage.removeChild(e)})};this._init();s_oVariousHelp=this;return this}var s_oVariousHelp=null;
