TEXT_START_GAME = "CLICK ON THE SCREEN TO START THE GAME";

TEXT_GAMEOVER  = "GAME OVER";
TEXT_SCORE     = "YOUR SCORE IS: ";
TEXT_PAUSE      = "PAUSE";

TEXT_DESKTOP = "MOVE YOUR MOUSE LEFT OR RIGHT TO CONTROL THE HERO. THE FURTHER THE CURSOR WILL BE FROM THE CENTRE OF THE SCREEN, THE FASTER THE HERO WILL FLY";
TEXT_MOBILE = "SWIPE LEFT OR RIGHT TO CONTROL THE HERO. THE FURTHER YOUR FINGER WILL BE FROM THE CENTER OF THE SCREEN, THE FASTER THE HERO WILL FLY";
TEXT_ORIENTATION = "TURN YOUR PHONE LEFT OR RIGHT TO CONTROL THE HERO. THE MORE YOU'LL ROTATE THE PHONE, THE FASTER THE HERO WILL FLY";

TEXT_PLATFORM0 = "FIXED PLATFORM";
TEXT_PLATFORM1 = "MOVING PLATFORM";
TEXT_PLATFORM2 = "CRASHING PLATFOMR";
TEXT_PLATFORM3 = "VANISHING PLATFORM";

TEXT_SPRING = "MEGA JUMP PLATFORM";

TEXT_COIN = "EXTRA SCORE COINS";
TEXT_WINGS = "SUPER SPEED POWERUP";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";