function CTextButton(a,d,b,c,g,e,k){var f,p,l,m,n;this._init=function(a,b,d,c,e,g,k){f=[];p=[];e=createBitmap(d);var z=Math.ceil(k/20);n=new createjs.Text(c,"bold "+k+"px "+PRIMARY_FONT,"#000000");n.textAlign="center";n.textBaseline="alphabetic";var A=n.getBounds();n.x=d.width/2+z;n.y=Math.floor(d.height/2)+A.height/3+z;m=new createjs.Text(c,"bold "+k+"px "+PRIMARY_FONT,g);m.textAlign="center";m.textBaseline="alphabetic";A=m.getBounds();m.x=d.width/2;m.y=Math.floor(d.height/2)+A.height/3;l=new createjs.Container;
l.x=a;l.y=b;l.regX=d.width/2;l.regY=d.height/2;l.addChild(e,n,m);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){f[a]=b;p[a]=d};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(p[ON_MOUSE_UP])};
this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;n.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,d,b,c,g,e,k);return this}
function CSettingsLevel(){this.createAlienOccurance=function(a){var d=[],d=a;a=[];for(var b=0;b<d.length;b++)for(var c=0;c<d[b];c++)a.push(b);return a};this.createBonusOccurance=function(a){var d=[],d=BONUS_OCCURENCE_PER_LEVEL[a];a=[];for(var b=0;b<d.length;b++)for(var c=0;c<d[b];c++)a.push(b);return a};this.unload=function(){s_oAlienSettings=null};s_oAliensSettings=this}var s_oAliensSettings;
function CPreloader(){var a,d,b,c,g,e,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("time_bar_fill","./sprites/time_bar_fill.png");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));k.addChild(f);f=s_oSpriteLibrary.getSprite("time_bar_fill");c=createBitmap(f);c.x=CANVAS_WIDTH/2-f.width/2;c.y=CANVAS_HEIGHT-140;k.addChild(c);a=f.width;d=f.height;g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);k.addChild(g);c.mask=
g;b=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-115;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";k.addChild(b);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;k.addChild(e)};this.refreshLoader=function(e){b.text=e+"%";g.graphics.clear();e=Math.floor(e*a/100);g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,e,d)};this._init()}
function CMenu(){var a,d,b,c,g,e;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var k=s_oSpriteLibrary.getSprite("but_play");c=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+250,k);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("icon_audio"),a=CANVAS_WIDTH-k.height/2-20,d=k.height/2+20,e=new CToggle(a,d,k,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(g);createjs.Tween.get(g).to({alpha:0},1E3).call(function(){g.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){c.unload();c=null;g.visible=!1;s_oStage.removeChild(b);b=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oMenu=null};this.refreshButtonPos=function(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||e.setPosition(a-b,c+d)};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");$(s_oMain).trigger("start_session");s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var d,b=0,c=0,g=STATE_LOADING,e,k,f;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;k.refreshLoader(Math.floor(b/c*100));b===c&&(k.unload(),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1}))};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?
(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over_theme.ogg","game_over"),createjs.Sound.registerSound("./sounds/astronaut1.ogg","astronaut1"),createjs.Sound.registerSound("./sounds/astronaut2.ogg","astronaut2"),createjs.Sound.registerSound("./sounds/boing.ogg",
"boing"),createjs.Sound.registerSound("./sounds/combo.ogg","combo"),createjs.Sound.registerSound("./sounds/energy_lost.ogg","energy_lost"),createjs.Sound.registerSound("./sounds/evil_pig.ogg","evil_pig"),createjs.Sound.registerSound("./sounds/evil1.ogg","evil1"),createjs.Sound.registerSound("./sounds/evil2.ogg","evil2"),createjs.Sound.registerSound("./sounds/evil3.ogg","evil3"),createjs.Sound.registerSound("./sounds/evil8.ogg","evil8"),createjs.Sound.registerSound("./sounds/explosion.ogg","explosion"),
createjs.Sound.registerSound("./sounds/bomb.ogg","bomb"),createjs.Sound.registerSound("./sounds/pigMode.ogg","pigMode"),createjs.Sound.registerSound("./sounds/power_up.ogg","power_up"),createjs.Sound.registerSound("./sounds/shot.ogg","shot")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),
createjs.Sound.registerSound("./sounds/game_over_theme.mp3","game_over"),createjs.Sound.registerSound("./sounds/astronaut1.mp3","astronaut1"),createjs.Sound.registerSound("./sounds/astronaut2.mp3","astronaut2"),createjs.Sound.registerSound("./sounds/boing.mp3","boing"),createjs.Sound.registerSound("./sounds/combo.mp3","combo"),createjs.Sound.registerSound("./sounds/energy_lost.mp3","energy_lost"),createjs.Sound.registerSound("./sounds/evil_pig.mp3","evil_pig"),createjs.Sound.registerSound("./sounds/evil1.mp3",
"evil1"),createjs.Sound.registerSound("./sounds/evil2.mp3","evil2"),createjs.Sound.registerSound("./sounds/evil3.mp3","evil3"),createjs.Sound.registerSound("./sounds/evil8.mp3","evil8"),createjs.Sound.registerSound("./sounds/explosion.mp3","explosion"),createjs.Sound.registerSound("./sounds/bomb.mp3","bomb"),createjs.Sound.registerSound("./sounds/pigMode.mp3","pigMode"),createjs.Sound.registerSound("./sounds/power_up.mp3","power_up"),createjs.Sound.registerSound("./sounds/shot.mp3","shot")),c+=18)};
this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("life_bar_fill","./sprites/life_bar_fill.png");s_oSpriteLibrary.addSprite("time_bar_fill","./sprites/time_bar_fill.png");s_oSpriteLibrary.addSprite("life_bar_box","./sprites/life_bar_box.png");s_oSpriteLibrary.addSprite("time_bar_box","./sprites/time_bar_box.png");s_oSpriteLibrary.addSprite("bg_level_bonus","./sprites/bg_level_bonus.jpg");
s_oSpriteLibrary.addSprite("bg_level_1","./sprites/bg_level_1.jpg");s_oSpriteLibrary.addSprite("bg_level_2","./sprites/bg_level_2.jpg");s_oSpriteLibrary.addSprite("bg_level_3","./sprites/bg_level_3.jpg");s_oSpriteLibrary.addSprite("help_bg","./sprites/help_bg.jpg");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("icon_audio","./sprites/icon_audio.png");s_oSpriteLibrary.addSprite("explosion_sprite","./sprites/explosion_sprite.png");s_oSpriteLibrary.addSprite("zap_flash",
"./sprites/zap_flash.png");s_oSpriteLibrary.addSprite("game_over_panel","./sprites/game_over_panel.png");s_oSpriteLibrary.addSprite("alien0","./sprites/alien0.png");s_oSpriteLibrary.addSprite("alien1","./sprites/alien1.png");s_oSpriteLibrary.addSprite("alien2","./sprites/alien2.png");s_oSpriteLibrary.addSprite("alien3","./sprites/alien3.png");s_oSpriteLibrary.addSprite("alien4","./sprites/alien4.png");s_oSpriteLibrary.addSprite("alien5","./sprites/alien5.png");s_oSpriteLibrary.addSprite("alien6",
"./sprites/alien6.png");s_oSpriteLibrary.addSprite("alien7","./sprites/alien7.png");s_oSpriteLibrary.addSprite("alien8","./sprites/alien8.png");s_oSpriteLibrary.addSprite("alien9","./sprites/alien9.png");s_oSpriteLibrary.addSprite("alien10","./sprites/alien10.png");s_oSpriteLibrary.addSprite("alien11","./sprites/alien11.png");s_oSpriteLibrary.addSprite("helmet","./sprites/helmet.png");s_oSpriteLibrary.addSprite("helmet_explosion","./sprites/helmet_explosion.png");s_oSpriteLibrary.addSprite("but_skip",
"./sprites/but_skip.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("item_bomb_sprite","./sprites/item_bomb_sprite.png");s_oSpriteLibrary.addSprite("item_medikit_sprite","./sprites/item_medikit_sprite.png");s_oSpriteLibrary.addSprite("item_pig_mode_sprite","./sprites/item_pig_mode_sprite.png");s_oSpriteLibrary.addSprite("item_time_sprite","./sprites/item_time_sprite.png");s_oSpriteLibrary.addSprite("item_assault_sprite","./sprites/item_assault_sprite.png");
s_oSpriteLibrary.addSprite("item_evil_horde_sprite","./sprites/item_evil_horde_sprite.png");s_oSpriteLibrary.addSprite("icon_extra_speed","./sprites/icon_extra_speed.png");s_oSpriteLibrary.addSprite("icon_astronaut_assault","./sprites/icon_astronaut_assault.png");s_oSpriteLibrary.addSprite("icon_evil_horde","./sprites/icon_evil_horde.png");s_oSpriteLibrary.addSprite("icon_pig_mode","./sprites/icon_pig_mode.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("bonus_assault","./sprites/bonus_assault.png");s_oSpriteLibrary.addSprite("bonus_evil_horde","./sprites/bonus_evil_horde.png");s_oSpriteLibrary.addSprite("bonus_pig_mode","./sprites/bonus_pig_mode.png");s_oSpriteLibrary.addSprite("bonus_speed_down","./sprites/bonus_speed_down.png");s_oSpriteLibrary.addSprite("gui_panel","./sprites/gui_panel.png");c+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;k.refreshLoader(Math.floor(b/c*100))};this._onAllImagesLoaded=function(){k.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoGame=function(){f=new CGame(e);g=STATE_GAME;$(s_oMain).trigger("game_start")};this.stopUpdate=function(){d=!1;
createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&f.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_iLanguageSelected,s_oSpriteSheetLora,s_aQuestions;TEXT_TIME="TIME";TEXT_BONUS="BONUS";TEXT_SCORE="SCORE";TEXT_LIFE="LIFE";TEXT_WAVE="WAVE";TEXT_PAUSE="Pause";TEXT_HELP1="Don't let evil aliens";TEXT_HELP2="reach the botton of the stage!";TEXT_HELP3="Hit astronauts for increase";TEXT_HELP4="the multiplier of score!!";TEXT_HELP5="Catch this guy";
TEXT_HELP6="to get a Bonus!!";TEXT_MISSION="Mission";TEXT_COMPLETED="Completed";TEXT_ALIENS_KILLED="Aliens Killed";TEXT_GOOD_HIT="Good Hit";TEXT_PERCENTAGE="Percentage";TEXT_FINAL_SCORE="Final Score";TEXT_CONGRATULATIONS="Congratulations!";TEXT_COMPLETE_ROW_1="You did it, now planet Earth";TEXT_COMPLETE_ROW_2="can sleep quietly...";TEXT_TOTAL_SCORE="Total Score";TEXT_BONUS_TIME="Remove 3 seconds to your time";TEXT_BONUS_ASSAULT="Increase aliens on stage of 300%";TEXT_BONUS_BOMB="Zaps all aliens on the stage";
TEXT_BONUS_SPEED="Decrease alien speed";TEXT_BONUS_EVIL_HORDE="More Evil Aliens on the stage";TEXT_BONUS_PIG_1="Pig Mode: All aliens become pigs!";TEXT_BONUS_PIG_2="More Score for you!";TEXT_BONUS_LIFE="Heal you Energy Bar";TEXT_COMBO="COMBO";TEXT_GAME_OVER="The evil horde is still there but at least you will have a delicius fried alien for dinner!";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CInterface(a){var d,b,c,g,e,k,f,p,l,m,n,r,t,v,x,w,y,u,z,A,D,H,E,B,F,P,M,Q,V,J,O,K,I,R,N,G,S,h,W,Y,L,T,U,X,Z,ba,da,ea,aa,ca;this._init=function(){var q;r=[];t=[];ca=0;q=s_oSpriteLibrary.getSprite("gui_panel");w=createBitmap(q);w.x=q.width;w.y=q.height;w.rotation=180;w.on("click",function(){});s_oStage.addChild(w);q=s_oSpriteLibrary.getSprite("gui_panel");y=createBitmap(q);y.x=0;y.y=CANVAS_HEIGHT-q.height;s_oStage.addChild(y);y.on("click",function(){});if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var C=
s_oSpriteLibrary.getSprite("icon_audio");q=CANVAS_WIDTH-C.width/2-100;c=q+45;g=C.height/2+895;f=new CToggle(c,g,C,s_bAudioActive);f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}C=s_oSpriteLibrary.getSprite("but_pause");q=CANVAS_WIDTH-C.width/2-100;e=q+85;k=C.height/2+895;h=new CGfxButton(e,k,C);h.addEventListener(ON_MOUSE_UP,this._onButPauseRelease,this);C=s_oSpriteLibrary.getSprite("but_exit");q=CANVAS_WIDTH-C.width/2-100;d=q-50;b=C.height/2+895;W=new CGfxButton(d,b,C);W.addEventListener(ON_MOUSE_UP,
this._onExit,this);h.block(!0);W.block(!0);q=s_oSpriteLibrary.getSprite("time_bar_box");B=createBitmap(q);B.x=CANVAS_WIDTH/2-100-q.width/2/1.5;B.y=CANVAS_HEIGHT/2-367;B.scaleX=.6;B.scaleY=.6;s_oStage.addChild(B);q=s_oSpriteLibrary.getSprite("life_bar_box");O=createBitmap(q);O.x=-(q.width/2)-38;O.y=-3;M=new createjs.Text(TEXT_TIME+"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"+TEXT_BONUS,"bold 36px "+PRIMARY_FONT,"#d4d503");M.x=CANVAS_WIDTH/2+20;M.y=CANVAS_HEIGHT/2-385;M.textAlign="center";M.textBaseline=
"alphabetic";s_oStage.addChild(M);z=new createjs.Text(TEXT_SCORE,"bold 36px "+PRIMARY_FONT,"#d4d503");z.x=CANVAS_WIDTH/2-190;z.y=CANVAS_HEIGHT/2+400;z.textAlign="center";z.textBaseline="alphabetic";s_oStage.addChild(z);u=new createjs.Text("0","bold 36px "+PRIMARY_FONT,"#ffffff");u.x=CANVAS_WIDTH/2-120;u.y=CANVAS_HEIGHT/2+400;u.textAlign="left";u.textBaseline="alphabetic";s_oStage.addChild(u);q=s_oSpriteLibrary.getSprite("icon_evil_horde");C={images:[q],frames:{width:q.width/2,height:q.height,regX:q.width/
2/2,regY:q.height/2},animations:{state_false:0,state_true:1}};C=new createjs.SpriteSheet(C);A=createSprite(C,"state_false",q.width/2/2,q.height/2,q.width/2,q.height);A.x=CANVAS_WIDTH/2+50;A.y=CANVAS_HEIGHT/2-345;s_oStage.addChild(A);q=s_oSpriteLibrary.getSprite("icon_astronaut_assault");C={images:[q],frames:{width:q.width/2,height:q.height,regX:q.width/2/2,regY:q.height/2},animations:{state_false:0,state_true:1}};C=new createjs.SpriteSheet(C);D=createSprite(C,"state_false",q.width/2/2,q.height/2,
q.width/2,q.height);D.x=CANVAS_WIDTH/2+100;D.y=CANVAS_HEIGHT/2-345;s_oStage.addChild(D);q=s_oSpriteLibrary.getSprite("icon_pig_mode");C={images:[q],frames:{width:q.width/2,height:q.height,regX:q.width/2/2,regY:q.height/2},animations:{state_false:0,state_true:1}};C=new createjs.SpriteSheet(C);H=createSprite(C,"state_false",q.width/2/2,q.height/2,q.width/2,q.height);H.x=CANVAS_WIDTH/2+150;H.y=CANVAS_HEIGHT/2-345;s_oStage.addChild(H);q=s_oSpriteLibrary.getSprite("icon_extra_speed");C={images:[q],frames:{width:q.width/
2,height:q.height,regX:q.width/2/2,regY:q.height/2},animations:{state_false:0,state_true:1}};C=new createjs.SpriteSheet(C);E=createSprite(C,"state_false",q.width/2/2,q.height/2,q.width/2,q.height);E.x=CANVAS_WIDTH/2+200;E.y=CANVAS_HEIGHT/2-345;s_oStage.addChild(E);q=s_oSpriteLibrary.getSprite("time_bar_fill");F=createBitmap(q);F.x=CANVAS_WIDTH/2-100-q.width/2/1.5;F.y=CANVAS_HEIGHT/2-365;F.scaleX=.6;F.scaleY=.6;s_oStage.addChild(F);V=q.height;Q=q.width/1-5;P=new createjs.Shape;P.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(F.x,
F.y,Q,V);F.mask=P;J=new createjs.Text(TIME_FINISH_GAME,"bold 32px "+PRIMARY_FONT,"#ff0000");J.textAlign="center";J.textBaseline="alphabetic";J.x=CANVAS_WIDTH/2-110;J.y=CANVAS_HEIGHT/2-315;s_oStage.addChild(J);q=s_oSpriteLibrary.getSprite("life_bar_fill");K=createBitmap(q);K.x=-(q.width/2)-40;N=q.height;R=q.width;I=new createjs.Shape;I.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(K.x,K.y,R,N);K.mask=I;S=new createjs.Text(TEXT_LIFE,"bold 32px "+PRIMARY_FONT,"#d4d503");S.y=17;S.x=-270;S.textAlign=
"center";S.textBaseline="alphabetic";da=CANVAS_WIDTH/2+70;ea=CANVAS_HEIGHT/2+330;aa=new createjs.Container;aa.x=da;aa.y=ea;aa.addChild(S,O,K);s_oStage.addChild(aa);G=new createjs.Text(TEXT_WAVE+" "+a,"bold 36px "+PRIMARY_FONT,"#d4d503");G.x=CANVAS_WIDTH/2;G.y=CANVAS_HEIGHT/2-420;G.textAlign="center";G.textBaseline="alphabetic";s_oStage.addChild(G);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=.5;p.visible=!1;s_oStage.addChild(p)};this.refreshButtonPos=
function(a,C){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(c-a,g-C);h.setPosition(e-a,k-C);W.setPosition(d-a,b-C)};this._onButPauseRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oGame.setPause(!0);p.visible=!0;Y=new createjs.Text(TEXT_PAUSE,"bold 48px "+PRIMARY_FONT,"#ffffff");Y.textAlign="center";Y.textBaseline="alphabetic";Y.x=CANVAS_WIDTH/2;Y.y=CANVAS_HEIGHT/2-250;s_oStage.addChild(Y);h.block(!0);W.block(!0);createjs.Ticker.paused=!0;var a=
s_oSpriteLibrary.getSprite("but_continue");L=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,a);L.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this)};this._onButContinueRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");p.visible=!1;L.unload();L=null;s_oStage.removeChild(Y);Y=null;h.block(!1);W.block(!1);createjs.Ticker.paused=!1;s_oGame.setPause(!1)};this.refreshBonusToggleAssault=function(a){D.gotoAndStop("state_"+a)};this.refreshBonusToggleSpeedDown=
function(a){E.gotoAndStop("state_"+a)};this.refreshBonusToggleEvilHorde=function(a){A.gotoAndStop("state_"+a)};this.refreshBonusTogglePigMode=function(a){H.gotoAndStop("state_"+a)};this.refreshScore=function(a){u.text=a};this.refreshMissionNumber=function(a){G.text="WAVE "+a};this.refreshTime=function(a){J.text=Math.round(a);P.graphics.clear();a=Math.floor(a*Q/100);P.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(F.x,F.y,a,V)};this.refreshLifeBar=function(a){I.graphics.clear();a=Math.floor(a*
R/100);I.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(K.x,K.y,a,N)};this.help=function(a,b){var h=s_oSpriteLibrary.getSprite("help_bg");l=createBitmap(h);l.on("click",function(){});s_oStage.addChild(l);m=new createjs.Text(TEXT_HELP1+"\n"+TEXT_HELP2+"\n\n\n\n\n\n\n\n\n\n\n\n"+TEXT_HELP3+"\n"+TEXT_HELP4,"bold 36px "+PRIMARY_FONT,"#99cc00");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-390;s_oStage.addChild(m);n=new createjs.Text(TEXT_HELP5+"              "+
TEXT_HELP6,"bold 36px "+PRIMARY_FONT,"#d4d503");n.textAlign="center";n.textBaseline="alphabetic";n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2+180;s_oStage.addChild(n);for(var d=h=0,c,e=0;e<a.length-4;e++){c={images:[a[e]],frames:{width:a[e].width/4,height:a[e].height,regX:a[e].width/2/2,regY:a[e].height/2},animations:{normal:[0,1,"normal",.2],pig:[2,3,"pig",.2]}};c=new createjs.SpriteSheet(c);var g;r[e]=new createjs.Container;c=createSprite(c,"normal",a[e].width/2/2,a[e].height/2,a[e].width/2,a[e].height);
r[e].regX=c.width/2/2;r[e].regY=c.height/2;g=new createjs.Text("+"+ALIENS_SETTINGS[e][0],"bold 32px "+PRIMARY_FONT,"#ffcc00");g.y=40;g.x=-70;4===e&&(d=0);r[e].x=CANVAS_WIDTH/2-100+100*d;r[e].y=4>e?CANVAS_HEIGHT/2-310:CANVAS_HEIGHT/2-180;d++;r[e].addChild(c,g);s_oStage.addChild(r[e]);h++}d=s_oSpriteLibrary.getSprite("helmet");x=createBitmap(d);x.regX=d.width/2;x.regY=d.height/2;x.x=CANVAS_WIDTH/2+160;x.y=CANVAS_HEIGHT/2-200;s_oStage.addChild(x);c={images:[a[h]],frames:{width:a[h].width/4,height:a[h].height,
regX:a[h].width/2/2,regY:a[h].height/2},animations:{normal:[0,1,"normal",.2],pig:[2,3,"pig",.2]}};c=new createjs.SpriteSheet(c);r[h]=new createjs.Container;c=createSprite(c,"normal",a[h].width/2/2,a[h].height/2,a[h].width/2,a[h].height);r[h].regX=c.width/2/2;r[h].regY=c.height/2;r[h].x=CANVAS_WIDTH/2+25;r[h].y=CANVAS_HEIGHT/2+160;r[h].addChild(c);s_oStage.addChild(r[h]);h++;d=0;for(e=h;e<a.length;e++)c={images:[a[e]],frames:{width:a[e].width/2,height:a[e].height,regX:a[e].width/2/2,regY:a[e].height/
2},animations:{normal:[0,1,"normal",.2]}},c=new createjs.SpriteSheet(c),r[e]=new createjs.Container,c=createSprite(c,"normal",a[e].width/2/2,a[e].height/2,a[e].width/2,a[e].height),r[e].regX=c.width/2/2,r[e].regY=c.height/2,g=new createjs.Text("+"+ALIENS_SETTINGS[e][0],"bold 32px "+PRIMARY_FONT,"#ffcc00"),g.y=55,g.x=-40,r[e].addChild(c,g),r[e].x=CANVAS_WIDTH/2-140+140*d,r[e].y=CANVAS_HEIGHT/2+30,s_oStage.addChild(r[e]),d++;h=0;c={images:[b[h]],frames:{width:b[h].width/5,height:b[h].height/2,regX:b[h].width/
2/5,regY:b[h].height/2/2},animations:{normal:[0,9,"normal",1]}};c=new createjs.SpriteSheet(c);t[h]=createSprite(c,"normal",b[h].width/2/5,b[h].height/2/2,b[h].width/5,b[h].height/2);t[h].x=CANVAS_WIDTH/2-210;t[h].y=CANVAS_HEIGHT/2+250;s_oStage.addChild(t[h]);h++;c={images:[b[h]],frames:{width:b[h].width/8,height:b[h].height/2,regX:b[h].width/2/8,regY:b[h].height/2/2},animations:{normal:[0,14,"normal",1]}};c=new createjs.SpriteSheet(c);t[h]=createSprite(c,"normal",b[h].width/2/8,b[h].height/2/2,b[h].width/
8,b[h].height/2);t[h].x=CANVAS_WIDTH/2-150;t[h].y=CANVAS_HEIGHT/2+250;s_oStage.addChild(t[h]);h++;c={images:[b[h]],frames:{width:b[h].width/2,height:b[h].height,regX:b[h].width/2/2,regY:b[h].height/2},animations:{normal:[0,1,"normal",.2]}};c=new createjs.SpriteSheet(c);t[h]=createSprite(c,"normal",b[h].width/2/2,b[h].height/2,b[h].width/2,b[h].height);t[h].x=CANVAS_WIDTH/2-80;t[h].y=CANVAS_HEIGHT/2+250;s_oStage.addChild(t[h]);h++;c={images:[b[h]],frames:{width:b[h].width/2,height:b[h].height,regX:b[h].width/
2/2,regY:b[h].height/2},animations:{normal:[0,1,"normal",.2]}};c=new createjs.SpriteSheet(c);t[h]=createSprite(c,"normal",b[h].width/2/2,b[h].height/2,b[h].width/2,b[h].height);t[h].x=CANVAS_WIDTH/2-10;t[h].y=CANVAS_HEIGHT/2+250;s_oStage.addChild(t[h]);h++;c={images:[b[h]],frames:{width:b[h].width/5,height:b[h].height/2,regX:b[h].width/2/5,regY:b[h].height/2/2},animations:{normal:[0,9,"normal",1]}};c=new createjs.SpriteSheet(c);t[h]=createSprite(c,"normal",b[h].width/2/7,b[h].height/2/2,b[h].width/
7,b[h].height/2);t[h].x=CANVAS_WIDTH/2+60;t[h].y=CANVAS_HEIGHT/2+250;s_oStage.addChild(t[h]);h++;c={images:[b[h]],frames:{width:b[h].width/7,height:b[h].height,regX:b[h].width/2/7,regY:b[h].height/2},animations:{normal:{frames:[0,1,2,3,4,5,6,6,5,4,3,2,1,0]}}};c=new createjs.SpriteSheet(c);t[h]=createSprite(c,"normal",b[h].width/2/7,b[h].height/2,b[h].width/7,b[h].height);t[h].x=CANVAS_WIDTH/2+130;t[h].y=CANVAS_HEIGHT/2+250;s_oStage.addChild(t[h]);h++;c={images:[b[h]],frames:{width:b[h].width/2,height:b[h].height,
regX:b[h].width/2/2,regY:b[h].height/2},animations:{normal:[0,1,"normal",.2]}};c=new createjs.SpriteSheet(c);t[h]=createSprite(c,"normal",b[h].width/2/2,b[h].height/2,b[h].width/2,b[h].height);t[h].x=CANVAS_WIDTH/2+200;t[h].y=CANVAS_HEIGHT/2+250;s_oStage.addChild(t[h]);h=s_oSpriteLibrary.getSprite("but_skip");v=new CGfxButton(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2+350,h);v.addEventListener(ON_MOUSE_UP,this._onButNextRelease,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this._onButFinishRelease=
function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");for(var a=0;a<r.length;a++)s_oStage.removeChild(r[a]),r[a]=null;p.visible=!1;L.unload();L=null;s_oStage.removeChild(n);n=null;s_oStage.removeChild(m);m=null;s_oStage.removeChild(x);x=null;s_oStage.removeChild(T);T=null;s_oStage.removeChild(U);U=null;s_oStage.removeChild(X);X=null;ca++;ca===NUM_WAVES_FOR_ADS&&(ca=0,$(s_oMain).trigger("show_interlevel_ad"));s_oGame.nextLevel()};this.animWave=function(){createjs.Tween.get(G).to({y:CANVAS_HEIGHT/
2,scaleX:2,scaleY:2},1E3,createjs.Ease.bounceOut).call(function(){createjs.Tween.get(G).wait(500).to({y:CANVAS_HEIGHT/2-420,scaleX:1,scaleY:1},1E3,createjs.Ease.circInOut).call(function(){s_oGame.setPause(!1)})})};this.missionComplete=function(a,b,h,c,d){p.visible=!0;n=new createjs.Text(TEXT_MISSION+h+TEXT_COMPLETED+"!!","bold 36px "+PRIMARY_FONT,"#d4d503");n.textAlign="center";n.textBaseline="alphabetic";n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2-340;s_oStage.addChild(n);m=new createjs.Text(TEXT_ALIENS_KILLED,
"bold 32px "+PRIMARY_FONT,"#99cc00");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-300;s_oStage.addChild(m);for(var e=0,g,f=0;f<b.length-4;f++){g={images:[b[f]],frames:{width:b[f].width/4,height:b[f].height,regX:b[f].width/2/2,regY:b[f].height/2},animations:{normal:[0,1,"normal",.2],pig:[2,3,"pig",.2]}};g=new createjs.SpriteSheet(g);var l;r[f]=new createjs.Container;g=createSprite(g,"normal",b[f].width/2/2,b[f].height/2,b[f].width/2,b[f].height);r[f].regX=
g.width/2/2;r[f].regY=g.height/2;l=new createjs.Text(c[f],"bold 40px "+PRIMARY_FONT,"#99cc00");l.textAlign="center";l.textBaseline="alphabetic";l.y=70;l.x=-40;4===f&&(e=0);r[f].x=CANVAS_WIDTH/2-200+150*e;r[f].y=4>f?CANVAS_HEIGHT/2-250:CANVAS_HEIGHT/2-120;e++;r[f].addChild(g,l);s_oStage.addChild(r[f])}f=s_oSpriteLibrary.getSprite("helmet");x=createBitmap(f);x.regX=f.width/2;x.regY=f.height/2;x.x=CANVAS_WIDTH/2+210;x.y=CANVAS_HEIGHT/2-140;s_oStage.addChild(x);for(f=b=0;f<c.length;f++)b+=c[f];T=new createjs.Text(TEXT_GOOD_HIT+
"n\n"+b,"50px "+PRIMARY_FONT,"#ffcc00");T.textAlign="center";T.textBaseline="alphabetic";T.x=CANVAS_WIDTH/2-100;T.y=CANVAS_HEIGHT/2;s_oStage.addChild(T);U=new createjs.Text(TEXT_PERCENTAGE+"\n\n"+Math.floor(d.good/d.tot*100)+"%","50px "+PRIMARY_FONT,"#ffcc00");U.textAlign="center";U.textBaseline="alphabetic";U.x=CANVAS_WIDTH/2+100;U.y=CANVAS_HEIGHT/2;s_oStage.addChild(U);c=new createjs.Text(TEXT_FINAL_SCORE,"50px "+PRIMARY_FONT,"#d3ee10");c.textAlign="center";c.textBaseline="alphabetic";c.y=0;d=new createjs.Text(a,
"50px "+PRIMARY_FONT,"#ffffff");d.textAlign="center";d.textBaseline="alphabetic";d.y=50;X=new createjs.Container;X.x=CANVAS_WIDTH/2;X.y=CANVAS_HEIGHT/2+150;X.addChild(c,d);s_oStage.addChild(X);c=s_oSpriteLibrary.getSprite("but_continue");h<ALIEN_OCCURENCE_PER_LEVEL.length?(L=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,c),L.addEventListener(ON_MOUSE_UP,this._onButFinishRelease,this)):(L=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,c),L.addEventListenerWithParams(ON_MOUSE_UP,this._onCompleteGame,
this,a));$(s_oMain).trigger("end_level",h);$(s_oMain).trigger("save_score",a)};this._onCompleteGame=function(a){var b,h,c,d;b=new createjs.Text(TEXT_CONGRATULATIONS,"bold 90px "+PRIMARY_FONT,"#ffff00");b.textAlign="center";b.textBaseline="alphabetic";h=new createjs.Text(TEXT_CONGRATULATIONS,"bold 90px "+PRIMARY_FONT,"#11cfbc");h.textAlign="center";h.textBaseline="alphabetic";h.outline=1;c=new createjs.Text(TEXT_COMPLETE_ROW_1+"\n"+TEXT_COMPLETE_ROW_2,"40px "+PRIMARY_FONT,"#99cc00");c.textAlign="center";
c.textBaseline="alphabetic";c.y=100;d=new createjs.Text(TEXT_TOTAL_SCORE+"\n"+a,"40px "+PRIMARY_FONT,"#ffffff");d.textAlign="center";d.textBaseline="alphabetic";d.y=200;ba=new createjs.Container;ba.x=CANVAS_WIDTH/2;ba.y=CANVAS_HEIGHT/2-200;ba.addChild(b,h,c,d);s_oStage.addChild(ba);for(b=0;b<r.length;b++)s_oStage.removeChild(r[b]),r[b]=null;L.unload();L=null;s_oStage.removeChild(n);n=null;s_oStage.removeChild(m);m=null;s_oStage.removeChild(x);x=null;s_oStage.removeChild(T);T=null;s_oStage.removeChild(U);
U=null;s_oStage.removeChild(X);X=null;b=s_oSpriteLibrary.getSprite("but_restart");L=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,b);L.addEventListener(ON_MOUSE_DOWN,s_oGame.onExit,this);$(s_oMain).trigger("share_event",a)};this._onButNextRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");for(var a=0;a<r.length;a++)s_oStage.removeChild(r[a]),r[a]=null;s_oStage.removeChild(m);m=null;s_oStage.removeChild(n);n=null;s_oStage.removeChild(x);x=null;this.help2()};
this._onButPlay=function(){v.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");for(var b=0;b<t.length;b++)s_oStage.removeChild(t[b]),t[b]=null;s_oStage.removeChild(m);m=!1;createjs.Tween.get(l).to({alpha:0},500,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(l);l=null;s_oInterface.animWave()});s_oStage.removeChild(Z);Z=null;h.block(!1);W.block(!1);$(s_oMain).trigger("start_level",a)};this.help2=function(){v.addEventListener(ON_MOUSE_UP,this._onButPlay,this);
for(var a=0;a<t.length;a++)t[a].x=CANVAS_WIDTH/2-170,t[a].y=CANVAS_HEIGHT/2-300+100*a;a=new createjs.Text(TEXT_BONUS_TIME,"32px "+PRIMARY_FONT,"#d4d503");a.textAlign="left";a.textBaseline="alphabetic";a.y=-290;a.x=60;var b;b=new createjs.Text(TEXT_BONUS_ASSAULT,"32px "+PRIMARY_FONT,"#d4d503");b.textAlign="left";b.textBaseline="alphabetic";b.y=-190;b.x=60;var h;h=new createjs.Text(TEXT_BONUS_BOMB,"32px "+PRIMARY_FONT,"#d4d503");h.textAlign="left";h.textBaseline="alphabetic";h.y=-90;h.x=60;var c;c=
new createjs.Text(TEXT_BONUS_SPEED,"32px "+PRIMARY_FONT,"#d4d503");c.textAlign="left";c.textBaseline="alphabetic";c.y=10;c.x=60;var d;d=new createjs.Text(TEXT_BONUS_EVIL_HORDE,"32px "+PRIMARY_FONT,"#d4d503");d.textAlign="left";d.textBaseline="alphabetic";d.y=110;d.x=60;var e;e=new createjs.Text(TEXT_BONUS_PIG_1+"\n\n"+TEXT_BONUS_PIG_2,"32px "+PRIMARY_FONT,"#d4d503");e.textAlign="left";e.textBaseline="alphabetic";e.y=190;e.x=60;var f;f=new createjs.Text(TEXT_BONUS_LIFE,"32px "+PRIMARY_FONT,"#d4d503");
f.textAlign="left";f.textBaseline="alphabetic";f.y=310;f.x=60;Z=new createjs.Container;Z.x=CANVAS_WIDTH/2-190;Z.y=CANVAS_HEIGHT/2;Z.addChild(b,h,f,d,e,c,a);s_oStage.addChild(Z)};this.unload=function(){aa=u=z=J=P=B=F=I=O=K=M=n=m=l=p=w=y=null;W.unload();W=null;h.unload();h=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;s_oInterface=null};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
s_oInterface=this;this._init();return this}var s_oInterface=null;
function CGfxButton(a,d,b){var c,g,e,k=[],f,p;this._init=function(a,b,d){c=1;g=[];e=[];f=createBitmap(d);f.x=a;f.y=b;f.regX=d.width/2;f.regY=d.height/2;s_oStage.addChild(f);p=!1;this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=
b;e[a]=c};this.addEventListenerWithParams=function(a,b,c,d){g[a]=b;e[a]=c;k=d};this.buttonRelease=function(){p||(f.scaleX=c,f.scaleY=c,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(e[ON_MOUSE_UP],k))};this.buttonDown=function(){p||(f.scaleX=.9*c,f.scaleY=.9*c,g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],k))};this.setScale=function(a){c=a;f.scaleX=a;f.scaleY=a};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};
this.getX=function(){return f.x};this.getY=function(){return f.y};this.block=function(a){p=a};this._init(a,d,b);return this}
function CGame(a){var d,b,c,g,e,k,f,p,l,m,n,r,t,v,x,w,y,u,z,A,D,H,E,B,F,P,M,Q,V,J,O,K,I={},R,N,G;this._init=function(){y=!0;z=0;v=TIME_FINISH_GAME;D=f=k=0;A=100;G=1;n=[];r=[];K=[];I={good:0,tot:0};J=V=Q=M=!1;m=l=0;O="bg_level_1";d=createBitmap(s_oSpriteLibrary.getSprite(O));s_oStage.addChild(d);s_oStage.setChildIndex(d,0);d.addEventListener("click",function(){D=0;I.tot++});c=[];g=[];for(var a=0;a<TYPES_OF_ALIENS;a++)c[a]=s_oSpriteLibrary.getSprite("alien"+a);g[0]=s_oSpriteLibrary.getSprite("item_time_sprite");
g[1]=s_oSpriteLibrary.getSprite("item_assault_sprite");g[2]=s_oSpriteLibrary.getSprite("item_bomb_sprite");g[3]=s_oSpriteLibrary.getSprite("icon_extra_speed");g[4]=s_oSpriteLibrary.getSprite("item_evil_horde_sprite");g[5]=s_oSpriteLibrary.getSprite("item_pig_mode_sprite");g[6]=s_oSpriteLibrary.getSprite("item_medikit_sprite");b=new CInterface(l+1);b.help(c,g);e=[];u=[];p=new CSettingsLevel;this.setAlienOccuranceStep(1);this.setOccurance(ALIEN_OCCURENCE_PER_LEVEL[l]);this.resetAlienNumberHit();x="normal";
this.setRandomTimeAlien()};this.setPause=function(a){y=a;for(var b=0;b<e.length;b++)e[b].block(a);for(b=0;b<u.length;b++)u[b].block(a)};this.resetAlienNumberHit=function(){for(var a=0;a<TYPES_OF_ALIENS;a++)K[a]=0};this.setOccurance=function(a){n=p.createAlienOccurance(a);r=p.createBonusOccurance(l)};this.setRandomTimeAlien=function(){var a=Math.floor(Math.random()*PER_LEVEL_SPAWN_ALIEN_TIME[l]);w=PER_LEVEL_SPAWN_ALIEN_TIME[l]-a/2};this.setAlienOccuranceStep=function(a){t=a};this.spawnAlien=function(){var a=
Math.floor(Math.random()*n.length),b=this.getRandomAlienCoord();e[k]=7!==n[a]?new CAlien(b,115,c[n[a]],x,n[a],Q,ALIENS_SETTINGS[n[a]][1]):new CAlienHelmet(b,115,c[n[a]],x,n[a],Q,ALIENS_SETTINGS[n[a]][1]);e[k].setInfoData("Type",n[a]);e[k].setInfoData("Score",ALIENS_SETTINGS[n[a]][0]);e[k].setInfoData("State",x);e[k].setInfoData("Max_Frame",ALIENS_MAX_FRAME[l]);e[k].addEventListenerWithParams(ON_MOUSE_DOWN,this._onButAlienPress,this,{alien:e[k],ID:k});k++};this.generateABonus=function(a,b){var c=Math.floor(Math.random()*
r.length);u[f]=new CBonus(a,b,g[r[c]],r[c]);u[f].setInfoData("Type",r[c]);u[f].addEventListenerWithParams(ON_MOUSE_DOWN,this._onButBonusPress,this,{bonus:u[f],ID:f});f++};this.nextLevel=function(){A=100;G=1;$(s_oMain).trigger("start_level",l);this.setAlienOccuranceStep(1);this.setOccurance(ALIEN_OCCURENCE_PER_LEVEL[l]);this.resetAlienNumberHit();2<l&&6>l&&(O="bg_level_2");6<=l&&10>l&&(O="bg_level_3");var a=s_oSpriteLibrary.getSprite(O);this.setBackGround(a);b.refreshBonusToggleAssault(!1);b.refreshBonusToggleEvilHorde(!1);
b.refreshBonusTogglePigMode(!1);b.refreshBonusToggleSpeedDown(!1);b.refreshMissionNumber(l+1);b.refreshLifeBar(A);for(a=0;a<e.length;a++)e[a].unload();for(a=0;a<u.length;a++)u[a].unload();u=e=null;e=[];u=[];v=TIME_FINISH_GAME;b.refreshTime(v);Q=J=M=V=!1;x="normal";I.good=0;f=k=I.tot=0;b.animWave()};this.getLevel=function(){return l};this._onButBonusPress=function(a){switch(a.bonus.getInfoData("Type")){case 0:this.subtractTime(a.bonus.getX(),a.bonus.getY());break;case 1:this.activeAstronautAssault();
break;case 2:this.activeBomb();break;case 3:this.speedDown(!0);break;case 4:this.activeEvilHorde();break;case 5:this.activePigMode();break;case 6:this.activeLife()}this.destroyFromBonusArray(a.ID)};this._onButAlienPress=function(a){var c;9<a.alien.getInfoData("Type")?(D++,I.tot++,I.good++,G+=a.alien.getInfoData("Score")):(K[a.alien.getInfoData("Type")]++,I.good++,I.tot++,D++);if(!1===J)if(9>a.alien.getInfoData("Type")){c=a.alien.getInfoData("Score")*D;z+=c*G;if(0===a.alien.getInfoData("Type")||1===
a.alien.getInfoData("Type")||2===a.alien.getInfoData("Type"))!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("evil1");if(3===a.alien.getInfoData("Type")||4===a.alien.getInfoData("Type")||5===a.alien.getInfoData("Type"))!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("evil2");if(6===a.alien.getInfoData("Type")||7===a.alien.getInfoData("Type"))!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("evil3");8===a.alien.getInfoData("Type")&&(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("evil8"))}else{if(9===a.alien.getInfoData("Type")||10===a.alien.getInfoData("Type"))!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("astronaut1");11===a.alien.getInfoData("Type")&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("astronaut2"));this.addEffect(a.alien.getX(),a.alien.getY(),a.alien.getInfoData("Score"),!0,a.alien.getInfoData("Type"));!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("explosion");this.destroyFromAlienArray(a.ID);
return}else if(9>a.alien.getInfoData("Type"))c=a.alien.getInfoData("Score")*D*2,z+=c*G,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("evil_pig");else{if(9===a.alien.getInfoData("Type")||10===a.alien.getInfoData("Type"))!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("astronaut1");11===a.alien.getInfoData("Type")&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("astronaut2"));this.addEffect(a.alien.getX(),a.alien.getY(),a.alien.getInfoData("Score"),!0,
a.alien.getInfoData("Type"));!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("explosion");this.destroyFromAlienArray(a.ID);return}z=Math.floor(z);b.refreshScore(z);8===a.alien.getInfoData("Type")&&this.generateABonus(a.alien.getX(),a.alien.getY());9>a.alien.getInfoData("Type")&&this.addEffect(a.alien.getX(),a.alien.getY(),c,!0,a.alien.getInfoData("Type"));!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("explosion");this.destroyFromAlienArray(a.ID)};this.subtractTime=
function(a,c){v+=TIME_TO_SUBTRACT;var d;d=new createjs.Text(TIME_TO_SUBTRACT+"''","bold 50px "+PRIMARY_FONT,"#ffcc00");d.textAlign="center";d.textBaseline="alphabetic";d.x=a;d.y=c;s_oStage.addChild(d);b.refreshTime(v);createjs.Tween.get(d).to({y:d.y-200,alpha:0},1500).call(function(){s_oStage.removeChild(d);d=null})};this.activeAstronautAssault=function(){var a,c=s_oSpriteLibrary.getSprite("bonus_assault");E=TIME_FOR_ASTRONAUT_ASSAULT;y=!0;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("power_up");
a=createBitmap(c);a.x=CANVAS_WIDTH/2;a.y=-(c.height/2)+50;a.regX=c.width/2;a.regY=c.height/2;s_oStage.addChild(a);for(var d=0;d<e.length;d++)e[d].block(!0);for(d=0;d<u.length;d++)u[d].block(!0);createjs.Tween.get(a).to({y:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(a).wait(500).to({y:-(c.height/2)+50},700,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(a);a=null;y=!1;M=!0;for(var b=0;b<e.length;b++)e[b].block(!1);for(b=0;b<u.length;b++)u[b].block(!1)})});
this.setOccurance(ALIEN_OCCURENCE_BONUS_ASTRONAUT_ASSAULT);b.refreshBonusToggleAssault(!0)};this.activeBomb=function(){for(var a=0,b=0;b<e.length;b++)125<e[b].getY()&&this.addEffect(e[b].getX(),e[b].getY(),e[b].getInfoData("Score"),!1,e[b].getInfoData("Type")),K[e[b].getInfoData("Type")]++,e[b].unload(),9<e[b].getInfoData("Type")&&(G+=.1),a++;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("bomb");k=0;e.splice(0,a)};this.speedDown=function(a){if(!0===a){B=TIME_FOR_SPEED_DOWN;y=!0;var c,
d=s_oSpriteLibrary.getSprite("bonus_speed_down");c=createBitmap(d);c.x=CANVAS_WIDTH/2;c.y=-(d.height/2)-50;c.regX=d.width/2;c.regY=d.height/2;s_oStage.addChild(c);for(d=0;d<e.length;d++)e[d].block(!0);for(d=0;d<u.length;d++)u[d].block(!0);createjs.Tween.get(c).to({y:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(c).wait(500).to({y:-300},700,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(c);c=null;y=!1;for(var a=0;a<e.length;a++)e[a].block(!1);for(a=0;a<
u.length;a++)u[a].block(!1)})})}for(d=0;d<e.length;d++)e[d].setSpeedDown(a);Q=a;b.refreshBonusToggleSpeedDown(a)};this.activeEvilHorde=function(){var a,c=s_oSpriteLibrary.getSprite("bonus_evil_horde");y=!0;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("power_up");F=TIME_FOR_EVIL_HORDE;a=createBitmap(c);a.x=CANVAS_WIDTH/2;a.y=-(c.height/2)+50;a.regX=c.width/2;a.regY=c.height/2;s_oStage.addChild(a);for(var d=0;d<e.length;d++)e[d].block(!0);for(d=0;d<u.length;d++)u[d].block(!0);this.setAlienOccuranceStep(1.5);
createjs.Tween.get(a).to({y:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(a).wait(500).to({y:-(c.height/2)+50},700,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(a);a=null;y=!1;V=!0;for(var b=0;b<e.length;b++)e[b].block(!1);for(b=0;b<u.length;b++)u[b].block(!1)})});this.setOccurance(ALIEN_OCCURENCE_BONUS_EVIL_HORDE);b.refreshBonusToggleEvilHorde(!0)};this.activePigMode=function(){var a,c=s_oSpriteLibrary.getSprite("bonus_pig_mode"),d=s_oSpriteLibrary.getSprite("bg_level_bonus");
this.setBackGround(d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("pigMode");y=!0;this.setAlienState("pig");P=TIME_FOR_PIG_MODE;a=createBitmap(c);a.x=CANVAS_WIDTH/2;a.y=-(c.height/2)-50;a.regX=c.width/2;a.regY=c.height/2;s_oStage.addChild(a);for(c=0;c<e.length;c++)e[c].block(!0);for(c=0;c<u.length;c++)u[c].block(!0);createjs.Tween.get(a).to({y:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(a).wait(500).to({y:-300},700,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(a);
a=null;y=!1;J=!0;for(var b=0;b<e.length;b++)e[b].block(!1);for(b=0;b<u.length;b++)u[b].block(!1)})});b.refreshBonusTogglePigMode(!0)};this.activeLife=function(){A+=20;100<A&&(A=100);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("power_up");b.refreshLifeBar(A)};this.setBackGround=function(a){s_oStage.removeChild(d);d=null;d=createBitmap(a);d.addEventListener("click",function(){D=0;I.tot++});s_oStage.addChild(d);s_oStage.setChildIndex(d,0)};this.addEffect=function(a,b,c,d,e){var f;
f=s_oSpriteLibrary.getSprite("explosion_sprite");var g={images:[f],frames:{width:f.width/9,height:f.height/2,regX:f.width/2/9,regY:f.height/2/2},animations:{explode:[0,17]}},g=new createjs.SpriteSheet(g);f=createSprite(g,"explode",f.width/2/9,f.height/2/2,f.width/9,f.height/2);f.x=a;f.y=b;s_oStage.addChild(f);f.on("animationend",this.destoyKaboom,null,!0,f);if(!0===d){d=s_oSpriteLibrary.getSprite("zap_flash");g={images:[d],frames:{width:d.width/7,height:d.height,regX:d.width/2/7,regY:0},animations:{zap:[0,
6,"zap",1]}};g=new createjs.SpriteSheet(g);d=createSprite(g,"zap",d.width/2/7,0,d.width/7,d.height);d.x=a;d.y=b;s_oStage.addChild(d);d.on("animationend",this.destroyZapFlash,null,!0,d);if(1<D){var k;k=new createjs.Text(TEXT_COMBO+" "+D,"bold 50px "+PRIMARY_FONT,"#ffcc00");k.textAlign="center";k.textBaseline="alphabetic";k.x=a>CANVAS_WIDTH/2?a-130:a+150;k.y=b;s_oStage.addChild(k);createjs.Tween.get(k).to({y:k.y-200,alpha:0},1500).call(function(){s_oStage.removeChild(k);k=null});!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("combo")}!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("shot")}if(0!==c){var l;d=Math.round(100*G)/100;9>e?0<c&&(l=1.1>G?new createjs.Text("+"+c,"bold 72px "+PRIMARY_FONT,"#ffcc00"):new createjs.Text("+"+Math.floor(c)+"x"+d,"bold 72px "+PRIMARY_FONT,"#ffcc00")):l=new createjs.Text("+X"+c,"bold 72px "+PRIMARY_FONT,"#ffcc00");l.textAlign="center";l.textBaseline="alphabetic";l.x=a;l.y=b;s_oStage.addChild(l);createjs.Tween.get(l).to({y:l.y-200,alpha:0},
1E3).call(function(){s_oStage.removeChild(l);l=null})}};this.alienDamage=function(a){if(9>a){D=1;A-=ALIENS_DAMAGE;b.refreshLifeBar(A);var c;c=new createjs.Shape;c.graphics.beginFill("red").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:.5},200).to({alpha:0},200).call(function(){s_oStage.removeChild(c);c=null});!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("energy_lost");0>=A&&(y=!0,this.gameOver())}else D=G=1};this.destroyZapFlash=
function(a,b){s_oStage.removeChild(b)};this.destoyKaboom=function(a,b){s_oStage.removeChild(b)};this.destroyFromAlienArray=function(a){e[a].unload();e.splice(a,1);k=e.length;for(a=0;a<k;a++)e[a].resetTheIndex(a)};this.destroyFromBonusArray=function(a){u[a].unload();u.splice(a,1);f=u.length;for(a=0;a<f;a++)u[a].resetTheIndex(a)};this.setAlienState=function(a){for(var b=0;b<k;b++)9>e[b].getInfoData("Type")&&e[b].setState(a);x=a};this.getRandomAlienCoord=function(){var a=Math.floor(Math.random()*CANVAS_WIDTH);
a>CANVAS_WIDTH-SPAWN_RANGE_MIN_X&&(a=SPAWN_RANGE_MAX_X);a<CANVAS_WIDTH-SPAWN_RANGE_MAX_X&&(a=SPAWN_RANGE_MIN_X);return a};this.gameOver=function(){var a=s_oSpriteLibrary.getSprite("game_over_panel");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");R=createBitmap(a);R.x=0;R.y=0;R.alpha=0;s_oStage.addChild(R);N=new createjs.Text(TEXT_GAME_OVER,"40px "+PRIMARY_FONT,"#ffffff");N.textAlign="center";N.textBaseline="alphabetic";N.lineWidth="350";N.x=CANVAS_WIDTH/2;N.y=CANVAS_HEIGHT/
2-50;s_oStage.addChild(N);createjs.Tween.get(N).to({alpha:1},1200,createjs.Ease.cubicIn);createjs.Tween.get(R).to({alpha:1},1200,createjs.Ease.cubicIn).call(function(){var a=s_oSpriteLibrary.getSprite("but_restart");H=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+250,a);H.addEventListener(ON_MOUSE_DOWN,s_oGame.onExit,this)});for(a=0;a<e.length;a++)e[a].block(!0);for(a=0;a<u.length;a++)u[a].block(!1);y=!0;$(s_oMain).trigger("share_event",z)};this.onExit=function(){s_oGame.unload();s_oMain.gotoMenu();
$(s_oMain).trigger("end_level",l);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad")};this.unload=function(){void 0!==H&&(H.unload(),H=null);N=R=null;b.unload();p.unload();for(var a=0;a<e.length;a++)e[a].unload();for(a=0;a<u.length;a++)u[a].unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.update=function(){if(!1===y)if(0>v){y=!0;for(var a=0;a<e.length;a++)e[a].block(!0);for(a=0;a<u.length;a++)u[a].block(!0);l++;b.missionComplete(z,c,l,K,I)}else{var d=
createjs.Ticker.getFPS();v-=1/d;b.refreshTime(v);for(a=0;a<k;a++)e[a].update();for(a=0;a<f;a++)u[a].update();!0===M&&(E-=1/d,0>=E&&(M=!1,this.setOccurance(ALIEN_OCCURENCE_PER_LEVEL[l]),b.refreshBonusToggleAssault(!1)));!0===Q&&(B-=1/d,0>=B&&(Q=!1,this.speedDown(!1),b.refreshBonusToggleSpeedDown(!1)));!0===V&&(F-=1/d,0>=F&&(V=!1,this.setAlienOccuranceStep(1),this.setOccurance(ALIEN_OCCURENCE_PER_LEVEL[l]),b.refreshBonusToggleEvilHorde(!1)));!0===J&&(P-=1/d,0>=P&&(J=!1,this.setAlienState("normal"),
d=s_oSpriteLibrary.getSprite(O),this.setBackGround(d),b.refreshBonusTogglePigMode(!1)));m+=t;m>w&&(m=0,this.setRandomTimeAlien(),this.spawnAlien())}};s_oGame=this;ALIENS_SETTINGS=[];for(var S=0;S<TYPES_OF_ALIENS;S++)ALIENS_SETTINGS[S]=[];ALIENS_SETTINGS[0][0]=a.score_alien0;ALIENS_SETTINGS[0][1]=a.speed_alien0;ALIENS_SETTINGS[1][0]=a.score_alien1;ALIENS_SETTINGS[1][1]=a.speed_alien1;ALIENS_SETTINGS[2][0]=a.score_alien2;ALIENS_SETTINGS[2][1]=a.speed_alien2;ALIENS_SETTINGS[3][0]=a.score_alien3;ALIENS_SETTINGS[3][1]=
a.speed_alien3;ALIENS_SETTINGS[4][0]=a.score_alien4;ALIENS_SETTINGS[4][1]=a.speed_alien4;ALIENS_SETTINGS[5][0]=a.score_alien5;ALIENS_SETTINGS[5][1]=a.speed_alien5;ALIENS_SETTINGS[6][0]=a.score_alien6;ALIENS_SETTINGS[6][1]=a.speed_alien6;ALIENS_SETTINGS[7][0]=a.score_alien7;ALIENS_SETTINGS[7][1]=a.speed_alien7;ALIENS_SETTINGS[8][0]=a.score_alien8;ALIENS_SETTINGS[8][1]=a.speed_alien8;ALIENS_SETTINGS[9][0]=a.score_alien9;ALIENS_SETTINGS[9][1]=a.speed_alien9;ALIENS_SETTINGS[10][0]=a.score_alien10;ALIENS_SETTINGS[10][1]=
a.speed_alien10;ALIENS_SETTINGS[11][0]=a.score_alien11;ALIENS_SETTINGS[11][1]=a.speed_alien11;TIME_TO_SUBTRACT=a.bonus_time;TIME_FOR_ASTRONAUT_ASSAULT=a.time_astronaut_assault;TIME_FOR_SPEED_DOWN=a.time_speed_down;TIME_FOR_EVIL_HORDE=a.time_evil_horde;TIME_FOR_PIG_MODE=a.time_pig_mode;ALIENS_DAMAGE=a.aliens_damage;MAX_BONUS_BOUNCE=a.max_bonus_bounces;BONUS_SPEED=a.bonus_speed;NUM_WAVES_FOR_ADS=a.num_waves_for_ads;this._init()}var s_oGame;
function CEasing(){this.easeOutBounce=function(a,d,b,c){return(a/=c)<1/2.75?7.5625*b*a*a+d:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+.75)+d:a<2.5/2.75?b*(7.5625*(a-=2.25/2.75)*a+.9375)+d:b*(7.5625*(a-=2.625/2.75)*a+.984375)+d};this.easeInBounce=function(a,d,b,c){return b-this.easeOutBounce(c-a,0,b,c)+d};this.easeInOutBounce=function(a,d,b,c){return a<c/2?.5*this.easeInBounce(2*a,0,b,c)+d:.5*this.easeOutBounce(2*a-c,0,b,c)+.5*b+d};this.easeInCirc=function(a,d,b,c){return-b*(Math.sqrt(1-(a/=c)*a)-1)+d};this.easeOutCirc=
function(a,d,b,c){return b*Math.sqrt(1-(a=a/c-1)*a)+d};this.easeInOutCirc=function(a,d,b,c){return 1>(a/=c/2)?-b/2*(Math.sqrt(1-a*a)-1)+d:b/2*(Math.sqrt(1-(a-=2)*a)+1)+d};this.easeInCubic=function(a,d,b,c){return b*(a/=c)*a*a+d};this.easeOutCubic=function(a,d,b,c){return b*((a=a/c-1)*a*a+1)+d};this.easeInOutCubic=function(a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a+d:b/2*((a-=2)*a*a+2)+d};this.easeInElastic=function(a,d,b,c,g,e){var k=0;if(0===a)return d;if(1===(a/=c))return d+b;e||(e=.3*c);!g||g<Math.abs(b)?
(g=b,k=e/4):k=e/(2*Math.PI)*Math.asin(b/g);return-(g*Math.pow(2,10*--a)*Math.sin(2*(a*c-k)*Math.PI/e))+d};this.easeOutElastic=function(a,d,b,c,g,e){var k=0;if(0===a)return d;if(1===(a/=c))return d+b;e||(e=.3*c);!g||g<Math.abs(b)?(g=b,k=e/4):k=e/(2*Math.PI)*Math.asin(b/g);return g*Math.pow(2,-10*a)*Math.sin(2*(a*c-k)*Math.PI/e)+b+d};this.easeInOutElastic=function(a,d,b,c,g,e){var k=0;if(0===a)return d;if(1===(a/=c))return d+b;e||(e=.3*c);!g||g<Math.abs(b)?(g=b,k=e/4):k=e/(2*Math.PI)*Math.asin(b/g);
return 1>a?-.5*g*Math.pow(2,10*--a)*Math.sin(2*(a*c-k)*Math.PI/e)+d:g*Math.pow(2,-10*--a)*Math.sin(2*(a*c-k)*Math.PI/e)*.5+b+d};this.easeInExpo=function(a,d,b,c){return 0===a?d:b*Math.pow(2,10*(a/c-1))+d};this.easeOutExpo=function(a,d,b,c){return a===c?d+b:b*(-Math.pow(2,-10*a/c)+1)+d};this.easeInOutExpo=function(a,d,b,c){return 0===a?d:a===c?d+b:1>(a/=c/2)?b/2*Math.pow(2,10*(a-1))+d:b/2*(-Math.pow(2,-10*--a)+2)+d};this.easeLinear=function(a,d,b,c){return b*a/c+d};this.easeInQuad=function(a,d,b,c){return b*
(a/=c)*a+d};this.easeOutQuad=function(a,d,b,c){return-b*(a/=c)*(a-2)+d};this.easeInOutQuad=function(a,d,b,c){return 1>(a/=c/2)?b/2*a*a+d:-b/2*(--a*(a-2)-1)+d};this.easeInQuart=function(a,d,b,c){return b*(a/=c)*a*a*a+d};this.easeOutQuart=function(a,d,b,c){return-b*((a=a/c-1)*a*a*a-1)+d};this.easeInOutQuart=function(a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a*a+d:-b/2*((a-=2)*a*a*a-2)+d};this.easeInQuint=function(a,d,b,c){return b*(a/=c)*a*a*a*a+d};this.easeOutQuint=function(a,d,b,c){return b*((a=a/c-1)*a*
a*a*a+1)+d};this.easeInOutQuint=function(a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a*a*a+d:b/2*((a-=2)*a*a*a*a+2)+d};this.easeInSine=function(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d};this.easeOutSine=function(a,d,b,c){return b*Math.sin(a/c*(Math.PI/2))+d};this.easeInOutSine=function(a,d,b,c){return-b/2*(Math.cos(Math.PI*a/c)-1)+d};this.easeInBack=function(a,d,b,c){return b*(a/=c)*a*(2.70158*a-1.70158)+d};this.easeOutBack=function(a,d,b,c){return b*((a=a/c-1)*a*(2.70158*a+1.70158)+1)+d};this.easeInOutBack=
function(a,d,b,c){var g=1.70158;return 1>(a/=c/2)?b/2*a*a*(((g*=1.525)+1)*a-g)+d:b/2*((a-=2)*a*(((g*=1.525)+1)*a+g)+2)+d};s_oEasing=this}var s_oEasing;
function CBonus(a,d,b,c){var g,e,k=[],f,p={},l,m,n,r,t,v,x,w,y,u,z,A;this._init=function(){g=[];e=[];l=v=!1;r=0;t=MAX_BONUS_BOUNCE;var k,p=Math.random();k=.5<p?1:-1;p=Math.random();m=k;n=.5<p?1:-1;if(0===c||4===c)k={images:[b],frames:{width:b.width/5,height:b.height/2,regX:b.width/2/5,regY:b.height/2/2},animations:{normal:[0,9,"normal",1]}},k=new createjs.SpriteSheet(k),f=createSprite(k,"normal",b.width/2/7,b.height/2/2,b.width/7,b.height/2),x=b.width/2/5,w=b.height/2/2;1===c&&(k={images:[b],frames:{width:b.width/
8,height:b.height/2,regX:b.width/2/8,regY:b.height/2/2},animations:{normal:[0,14,"normal",1]}},k=new createjs.SpriteSheet(k),f=createSprite(k,"normal",b.width/2/8,b.height/2/2,b.width/8,b.height/2),x=b.width/2/8,w=b.height/2/2);if(2===c||3===c||6===c)k={images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{normal:[0,1,"normal",.5]}},k=new createjs.SpriteSheet(k),f=createSprite(k,"normal",b.width/2/2,b.height/2,b.width/2,b.height),x=b.width/2/2,w=b.height/
2;5===c&&(k={images:[b],frames:{width:b.width/7,height:b.height,regX:b.width/2/7,regY:b.height/2},animations:{normal:{frames:[0,1,2,3,4,5,6,6,5,4,3,2,1,0]}}},k=new createjs.SpriteSheet(k),f=createSprite(k,"normal",b.width/2/7,b.height/2,b.width/7,b.height),x=b.width/2/7,w=b.height/2);f.x=a;f.y=d;f.mouseEnabled=!0;f.visible=!0;y=CANVAS_WIDTH-x;u=1+x;z=173+w;A=CANVAS_HEIGHT-173-w;s_oStage.addChild(f);s_oStage.setChildIndex(f,4);this._initListener()};this._initListener=function(){f.on("mousedown",this.buttonDown);
f.on("pressup",this.buttonRelease)};this.block=function(a){l=a};this.setState=function(a){f.gotoAndPlay(a)};this.getX=function(){return f.x};this.getY=function(){return f.y};this.setInfoData=function(a,b){p[a]=b};this.getInfoData=function(a){return p[a]};this.resetTheIndex=function(a){k.ID=a};this.addEventListenerWithParams=function(a,b,c,d){g[a]=b;e[a]=c;k=d};this.buttonRelease=function(){l||g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(e[ON_MOUSE_UP],k)};this.buttonDown=function(){l||g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],
k)};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};this.update=function(){f.x+=BONUS_SPEED*m;f.y+=BONUS_SPEED*n;!1===v&&(f.x>=y?(m*=-1,r++,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("boing")):f.y>=A?(n*=-1,r++,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("boing")):f.x<=1+u?(m*=-1,r++,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("boing")):f.y<=z&&(n*=-1,r++,!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("boing")),r>=t&&(v=!0));!0===v&&(135>=f.y&&s_oGame.destroyFromBonusArray(k.ID),-20>=f.x&&s_oGame.destroyFromBonusArray(k.ID),f.x>=CANVAS_WIDTH+40&&s_oGame.destroyFromBonusArray(k.ID),f.y>=CANVAS_HEIGHT-135&&s_oGame.destroyFromBonusArray(k.ID))};s_oBonus=this;this._init()}var s_oBonus;
function CAlienHelmet(a,d,b,c,g,e,k){var f,p,l=[],m,n,r,t,v,x,w,y,u,z={},A,D,H,E,B,F;this._init=function(){f=[];p=[];n=0;r=Math.floor(6*Math.random());A=!1;H=D=k;F=!0;console.log(r);var a={images:[b],frames:{width:b.width/4,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{normal:[0,1,"normal",.2],pig:[2,3,"pig",.2]}},a=new createjs.SpriteSheet(a);m=createSprite(a,c,b.width/2/2,b.height/2,b.width/2,b.height);"normal"===c?(a=s_oSpriteLibrary.getSprite("helmet_explosion"),a={images:[a],
frames:{width:a.width/2,height:a.height/2,regX:a.width/2/2,regY:a.height/2/2},animations:{normal:0,destroy:[1,3,"destroy",.2]}},a=new createjs.SpriteSheet(a),E=createSprite(a,"normal",b.width/2/2,b.height/2,b.width/2,b.height),B=new createjs.Container,B.addChild(m,E),E.y=-25,E.x=-40):(B=new createjs.Container,B.addChild(m),F=!1);console.log("CONTAINER "+B);w=[];y=[];m.mouseEnabled=!0;m.visible=!0;t=new CEasing;u=new CTrajectories;s_oStage.addChild(B);s_oStage.setChildIndex(B,2);this.setSpeedDown(e);
this.initPos();this._initListener()};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.initPos=function(){0!==a&&0!==d?(B.x=a,B.y=d):(w.x=s_oGame.getRandomAlienCoord(),w.y=115);var b=[],c;w.x=a;w.y=d;c=Math.floor(Math.random()*CANVAS_WIDTH);c>CANVAS_WIDTH-SPAWN_RANGE_MIN_X&&(c=SPAWN_RANGE_MAX_X);c<CANVAS_WIDTH-SPAWN_RANGE_MAX_X&&(c=SPAWN_RANGE_MIN_X);y.x=c;y.y=CANVAS_HEIGHT-120;w.x>CANVAS_WIDTH/2?(c=Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+
100,b.x=CANVAS_WIDTH/2-100):(c=Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100,b.x=CANVAS_WIDTH/2+100);b.y=c;v=[w.x,b.x,y.x];x=[w.y,b.y,y.y];trace("_aStartingPos: "+w.x);trace("t0: "+b.x);trace("_aEndPos: "+y.x);B.x=w.x;B.y=w.y};this.block=function(a){A=a};this.setState=function(a){m.gotoAndPlay(a);"pig"===a&&!0===F&&(F=!1,E.gotoAndPlay("destroy"),E.on("animationend",function(){B.removeChild(E);E=null}))};this.getX=function(){return B.x};this.getY=function(){return B.y};this.setInfoData=function(a,
b){z[a]=b};this.getInfoData=function(a){return z[a]};this.resetTheIndex=function(a){l.ID=a};this.setSpeedDown=function(a){D=!0===a?H/2:H};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;p[a]=c;l=d};this.buttonRelease=function(){A||f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(p[ON_MOUSE_UP],l)};this.unloadHelmet=function(){null!==E&&(B.removeChild(1),E=null)};this.buttonDown=function(){A||(console.log("BOOLEAN"+F),!1===F?f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],l):(F=!1,E.gotoAndPlay("destroy"),
E.on("animationend",function(){B.removeChild(E);E=null}),s_oGame.addEffect(B.x,B.y,0,!0)))};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);this.unloadHelmet();s_oStage.removeChild(B)};this.update=function(){n+=D;B.y>=y.y&&(n=0,s_oGame.alienDamage(z.Type),s_oGame.destroyFromAlienArray(l.ID));var a;switch(r){case 0:a=t.easeInQuad(n,0,1,z.Max_Frame);break;case 1:a=t.easeInSine(n,0,1,z.Max_Frame);break;case 2:a=t.easeInCubic(n,0,1,z.Max_Frame);break;case 3:a=
t.easeOutBack(n,0,1,z.Max_Frame);break;case 4:a=t.easeOutQuad(n,0,1,z.Max_Frame);break;case 5:a=t.easeOutCubic(n,0,1,z.Max_Frame)}var b=u.quad(a,v);a=u.quad(a,x);B.x=b;B.y=a};s_oAlienHelmet=this;this._init()}var s_oAlienHelmet;
function CAlien(a,d,b,c,g,e,k){var f,p,l=[],m,n,r,t,v,x,w,y,u,z={},A,D,H;this._init=function(){f=[];p=[];n=0;if(8===g){var a=[3,5,6];r=a[Math.floor(Math.random()*a.length)]}else r=Math.floor(6*Math.random());A=!1;H=D=k;9>g?(a={images:[b],frames:{width:b.width/4,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{normal:[0,1,"normal",.2],pig:[2,3,"pig",.2]}},a=new createjs.SpriteSheet(a),m=createSprite(a,c,b.width/2/2,b.height/2,b.width/2,b.height)):(a={images:[b],frames:{width:b.width/2,
height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{normal:[0,1,"normal",.2]}},a=new createjs.SpriteSheet(a),m=createSprite(a,"normal",b.width/2/2,b.height/2,b.width/2,b.height));w=[];y=[];m.mouseEnabled=!0;m.visible=!0;t=new CEasing;u=new CTrajectories;s_oStage.addChild(m);s_oStage.setChildIndex(m,2);this.setSpeedDown(e);this.initPos();this._initListener()};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.initPos=function(){0!==a&&
0!==d?(m.x=a,m.y=d):(w.x=s_oGame.getRandomAlienCoord(),w.y=115);var b=[],c;w.x=a;w.y=d;c=Math.floor(Math.random()*CANVAS_WIDTH);c>CANVAS_WIDTH-SPAWN_RANGE_MIN_X&&(c=SPAWN_RANGE_MAX_X);c<CANVAS_WIDTH-SPAWN_RANGE_MAX_X&&(c=SPAWN_RANGE_MIN_X);y.x=c;y.y=CANVAS_HEIGHT-120;w.x>CANVAS_WIDTH/2?(c=Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100,b.x=CANVAS_WIDTH/2-100):(c=Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100,b.x=CANVAS_WIDTH/2+100);b.y=c;v=[w.x,b.x,y.x];x=[w.y,b.y,y.y];m.x=w.x;m.y=w.y};this.block=
function(a){A=a};this.setState=function(a){m.gotoAndPlay(a)};this.getX=function(){return m.x};this.getY=function(){return m.y};this.setInfoData=function(a,b){z[a]=b};this.getInfoData=function(a){return z[a]};this.resetTheIndex=function(a){l.ID=a};this.setSpeedDown=function(a){D=!0===a?H/2:H};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;p[a]=c;l=d};this.buttonRelease=function(){A||f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(p[ON_MOUSE_UP],l)};this.buttonDown=function(){A||f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],
l)};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this.update=function(){n+=D;m.y>=y.y&&(s_oGame.alienDamage(z.Type),s_oGame.destroyFromAlienArray(l.ID));var a;switch(r){case 0:a=t.easeInQuad(n,0,1,z.Max_Frame);break;case 1:a=t.easeOutSine(n,0,1,z.Max_Frame);break;case 2:a=t.easeInCubic(n,0,1,z.Max_Frame);break;case 3:a=t.easeOutBack(n,0,1,z.Max_Frame);break;case 4:a=t.easeOutExpo(n,0,1,z.Max_Frame);break;case 5:a=t.easeOutQuart(n,
0,1,z.Max_Frame)}var b=u.quad(a,v);a=u.quad(a,x);m.x=b;m.y=a};s_oAlien=this;this._init()}var s_oAlien;
function CSpriteLibrary(){var a,d,b,c,g,e;this.init=function(k,f,p){b=d=0;c=k;g=f;e=p;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){g.call(e)};this._onSpriteLoaded=function(){c.call(e);++b===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=840,CANVAS_HEIGHT=960,EDGEBOARD_X=180,EDGEBOARD_Y=20,FPS_TIME=1E3/30,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="domdiagonal_btregular",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,SPAWN_RANGE_MAX_X=570,SPAWN_RANGE_MIN_X=90,TYPES_OF_ALIENS=12,TYPES_OF_BONUS=7,PER_LEVEL_SPAWN_ALIEN_TIME,ALIEN_OCCURENCE_PER_LEVEL,BONUS_OCCURENCE_PER_LEVEL,ALIEN_OCCURENCE_BONUS_ASTRONAUT_ASSAULT,ALIEN_OCCURENCE_BONUS_EVIL_HORDE,
TIME_FINISH_GAME=60;ALIEN_OCCURENCE_PER_LEVEL=[[17,30,0,19,0,21,0,0,5,1,2,2],[20,1,25,1,20,20,0,0,7,2,2,2],[19,2,18,4,27,18,2,0,4,2,2,2],[13,15,0,26,13,13,22,1,4,2,2,2],[18,13,15,9,9,7,15,7,4,3,4,3],[12,13,12,12,12,13,15,7,4,2,2,2],[0,2,5,12,12,10,7,42,4,2,2,2],[12,12,7,12,9,12,7,0,4,4,6,6],[6,12,7,12,12,18,7,7,4,2,2,2],[10,10,10,6,6,6,8,6,8,5,5,5],[5,5,5,5,5,5,5,35,25,2,3,5]];ALIEN_OCCURENCE_BONUS_ASTRONAUT_ASSAULT=[1,1,1,1,1,1,1,1,1,30,30,31];
ALIEN_OCCURENCE_BONUS_EVIL_HORDE=[12,12,12,12,12,12,12,6,5,1,1,1];BONUS_OCCURENCE_PER_LEVEL=[[50,16,1,16,1,1,30],[40,10,1,30,1,1,16],[30,11,20,30,1,1,7],[20,10,30,20,12,1,7],[15,5,20,30,22,5,13],[8,7,30,15,27,10,6],[8,17,10,15,10,10,33],[15,6,16,15,30,3,15],[7,6,24,20,30,8,5],[7,6,14,60,10,8,5],[14,14,14,14,14,14,16]];ALIENS_MAX_FRAME=[180,160,180,170,160,155,160,150,170,140,150];PER_LEVEL_SPAWN_ALIEN_TIME=[33,27,22,25,23,22,20,18,15,17,14];
function CTrajectories(){this.CTrajectories=function(){};this.quad=function(a,d){return(1-a)*(1-a)*d[0]+2*(1-a)*a*d[1]+a*a*d[2]}}
function CToggle(a,d,b,c){var g,e,k,f=[],p;this._init=function(a,b,c,d){e=[];k=[];var f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});g=d;p=createSprite(f,"state_"+g,c.width/2/2,c.height/2,c.width/2,c.height);p.mouseEnabled=!0;p.x=a;p.y=b;p.stop();s_oStage.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown",this.buttonDown);p.off("pressup",this.buttonRelease);p.mouseEnabled=
!1;s_oStage.removeChild(p)};this._initListener=function(){p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;k[a]=c};this.addEventListenerWithParams=function(a,b,c,d){e[a]=b;k[a]=c;f=d};this.setActive=function(a){g=a;p.gotoAndStop("state_"+g)};this.buttonRelease=function(){p.scaleX=1;p.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");g=!g;p.gotoAndStop("state_"+g);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(k[ON_MOUSE_UP],
f)};this.buttonDown=function(){p.scaleX=.9;p.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],f)};this.setPosition=function(a,b){p.x=a;p.y=b};this.setVisible=function(a){p.visible=a};this._init(a,d,b,c)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIphone(){return-1!==navigator.userAgent.toLowerCase().indexOf("iphone")?!0:!1}
function getSize(a){var d=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var e=b.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+d+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";g.appendChild(e);c.insertBefore(g,b.head);
a=7==e["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,g=0;b<a?(g=a-b,b+=g,c+=CANVAS_WIDTH/CANVAS_HEIGHT*g):c<d&&(g=d-c,c+=g,b+=CANVAS_HEIGHT/CANVAS_WIDTH*g);var g=a/2-b/2,e=d/2-c/2,k=CANVAS_WIDTH/c;if(e*k<-EDGEBOARD_X||g*k<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*
EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,g=(a-b)/2,e=(d-c)/2,k=CANVAS_WIDTH/c;s_iOffsetX=-1*e*k;s_iOffsetY=-1*g*k;0<=g&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",e+"px")}}
function createBitmap(a,d,b){var c=new createjs.Bitmap(a),g=new createjs.Shape;d&&b?g.graphics.beginFill("#fff").drawRect(0,0,d,b):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=g;return c}function createSprite(a,d,b,c,g,e){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,g,e);a.hitArea=d;return a}
function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=Math.floor(a-60*d);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return 10>a?b+("0"+a):b+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return c[1]}}
function CTextToggle(a,d,b,c,g,e,k,f,p){var l=1,m,n=!1,r,t,v,x,w,y;this._init=function(a,b,c,d,e,f,g,k,l){m=!1;r=[];t=[];y=createBitmap(c);var n=Math.ceil(g/20);w=new createjs.Text(d," "+g+"px "+e,"#000000");w.textAlign="center";w.textBaseline="alphabetic";var p=w.getBounds();w.x=c.width/2+n;w.y=Math.floor(c.height/2)+p.height/3+n-7;x=new createjs.Text(d," "+g+"px "+e,f);x.textAlign="center";x.textBaseline="alphabetic";p=x.getBounds();x.x=c.width/2;x.y=Math.floor(c.height/2)+p.height/3-7;v=new createjs.Container;
v.x=a;v.y=b;v.regX=c.width/2;v.regY=c.height/2;k||(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),y=createSprite(a,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),w.x=n,w.y=n+17,x.x=0,x.y=17,v.regX=0,v.regY=0);v.addChild(y,w,x);l.addChild(v);this._initListener()};this.unload=function(){v.off("mousedown");v.off("pressup");p.removeChild(v)};this.setVisible=function(a){v.visible=a};
this._initListener=function(){oParent=this;v.on("mousedown",this.buttonDown);v.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){r[a]=b;t[a]=c};this.buttonRelease=function(){m||n||(v.scaleX=1*l,v.scaleY=1*l,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(t[ON_MOUSE_UP]))};this.buttonDown=function(){m||n||(v.scaleX=.9*l,v.scaleY=.9*l,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.enable=function(){m=!1;f||y.gotoAndStop("state_true")};this.disable=function(){m=!0;f||y.gotoAndStop("state_false")};
this.setTextPosition=function(a,b){var c=Math.ceil(k/20);w.x=a+c;w.y=b+c;x.x=a;x.y=b};this.setText=function(a){x.text=a;w.text=a};this.setPosition=function(a,b){v.x=a;v.y=b};this.setX=function(a){v.x=a};this.setY=function(a){v.y=a};this.getButtonImage=function(){return v};this.getX=function(){return v.x};this.getY=function(){return v.y};this.block=function(a){n=a};this.setScale=function(a){l=a;v.scaleX=a;v.scaleY=a};this.setScaleX=function(a){y.scaleX=a};this._init(a,d,b,c,g,e,k,f,p);return this}
;