function CBonusPanel(){var a,c,l,h,g,k,d,f,e,b;this._init=function(){e=new createjs.Container;s_oStage.addChild(e);var a=createBitmap(s_oSpriteLibrary.getSprite("bonus_bg"));e.alpha=0;e.visible=!1;e.addChild(a);a={framerate:3,images:[s_oSpriteLibrary.getSprite("chicken")],frames:{width:CHICKEN_WIDTH,height:CHICKEN_HEIGHT,regX:CHICKEN_WIDTH/2,regY:CHICKEN_HEIGHT/2},animations:{idle:[0,5,"idle"],lay_egg:[6,9,"lay_egg"],idle_rand_0:[1,5,"idle"],idle_rand_1:[2,5,"idle"],idle_rand_2:[3,5,"idle"],idle_rand_3:[4,
5,"idle"],right:[3],left:[4]}};a=new createjs.SpriteSheet(a);l=[];for(var b=420,c=0;5>c;c++){var h=createSprite(a,"idle",CHICKEN_WIDTH/2,CHICKEN_HEIGHT/2,CHICKEN_WIDTH,CHICKEN_HEIGHT);h.on("click",this._onChickenReleased,this,!1,c);h.x=b;h.y=286;h.stop();h.visible=!1;e.addChild(h);b+=164;l[c]=h}b=s_oSpriteLibrary.getSprite("egg");a={framerate:10,images:[b],frames:{width:Math.floor(b.width/NUM_PRIZES),height:b.height,regX:Math.floor(b.width/NUM_PRIZES)/2,regY:b.height/2},animations:{egg_0:[0],egg_1:[1],
egg_2:[2]}};a=new createjs.SpriteSheet(a);d=createSprite(a,"egg_0",Math.floor(b.width/NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);e.addChild(d);c=new createjs.Shape;c.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(110,390,800,160);e.addChild(c);d.mask=c;g=[];k=[];g[0]=createSprite(a,"egg_0",Math.floor(b.width/NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);g[0].x=350;g[0].y=CANVAS_HEIGHT-70;e.addChild(g[0]);c=new createjs.Text("100","34px "+FONT_GAME,"#ffff00");
c.textAlign="left";c.x=g[0].x+b.width/NUM_PRIZES/2+6;c.y=g[0].y+12;c.textBaseline="alphabetic";e.addChild(c);k.push(c);g[1]=createSprite(a,"egg_1",Math.floor(b.width/NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);g[1].x=650;g[1].y=CANVAS_HEIGHT-70;e.addChild(g[1]);c=new createjs.Text("200","34px "+FONT_GAME,"#ffff00");c.textAlign="left";c.x=g[1].x+ +(b.width/NUM_PRIZES)/2+6;c.y=g[1].y+12;c.textBaseline="alphabetic";e.addChild(c);k.push(c);g[2]=createSprite(a,"egg_2",Math.floor(b.width/
NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);g[2].x=950;g[2].y=CANVAS_HEIGHT-70;e.addChild(g[2]);c=new createjs.Text("300","34px "+FONT_GAME,"#ffff00");c.textAlign="left";c.x=g[2].x+ +(b.width/NUM_PRIZES)/2+6;c.y=g[2].y+12;c.textBaseline="alphabetic";e.addChild(c);k.push(c);f=new createjs.Text("+ 300$","bold 80px Arial","#ffff00");f.alpha=0;f.textAlign="center";f.shadow=new createjs.Shadow("#000",2,2,2);f.x=CANVAS_WIDTH/2;f.y=150;f.textBaseline="alphabetic";e.addChild(f)};this.unload=
function(){for(var a=0;5>a;a++)l[a].off("click",this._onChickenReleased)};this.show=function(c){a=!1;f.alpha=0;switch(c){case 3:h=BONUS_PRIZE[0];break;case 4:h=BONUS_PRIZE[1];break;case 5:h=BONUS_PRIZE[2];break;default:h=BONUS_PRIZE[0]}k[0].text=h[0]+"$";k[1].text=h[1]+"$";k[2].text=h[2]+"$";d.x=118;d.y=308;d.rotation=0;d.gotoAndStop("egg_0");for(var g=0;g<c;g++){var n=Math.floor(4*Math.random());l[g].framerate=3;l[g].visible=!0;l[g].gotoAndPlay("idle_rand_"+n)}e.visible=!0;createjs.Tween.get(e).to({alpha:1},
1E3);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.setVolume(0),b=createjs.Sound.play("soundtrack_bonus",{loop:-1})};this._onChickenReleased=function(b,d){a||(a=!0,this.playChickenLayAnim(d,s_aEggOccurence[Math.floor(Math.random()*s_aEggOccurence.length)]),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("choose_chicken"))};this.playChickenLayAnim=function(a,b){c=h[b];d.gotoAndStop("egg_"+b);for(var e=0;5>e;e++)e<a?l[e].gotoAndStop("right"):e===a?(l[a].framerate=10,l[a].gotoAndPlay("lay_egg")):
l[e].gotoAndStop("left");var f=this;setTimeout(function(){f.layEgg(a)},2500)};this.layEgg=function(a){l[a].gotoAndStop(5);d.x=l[a].x;var b=this;createjs.Tween.get(d).to({y:460},300).call(function(){b.endBonus()});!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reveal_egg")};this.endBonus=function(){f.text="+ "+c+"$";createjs.Tween.get(f).to({alpha:1},500);createjs.Tween.get(d).to({rotation:110},500);setTimeout(function(){e.alpha=0;e.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.setVolume(SOUNDTRACK_VOLUME),
b.stop();s_oGame.endBonus(c)},4E3)};this._init()}
function CBetBut(a,c,l){var h,g,k,d=[],f;this._init=function(a,b,d){h=!1;g=[];k=[];d=s_oSpriteLibrary.getSprite("bet_but");var c=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});f=createSprite(c,"on",0,0,d.width/2,d.height);f.stop();f.x=a;f.y=b;f.regX=d.width/2;f.regY=d.height/2;s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};
this.disable=function(a){h=a};this.setVisible=function(a){f.visible=a};this.setOn=function(){f.gotoAndStop("on")};this.setOff=function(){f.gotoAndStop("off")};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){g[a]=b;k[a]=d};this.addEventListenerWithParams=function(a,b,f,c){g[a]=b;k[a]=f;d=c};this.buttonRelease=function(){g[ON_MOUSE_UP]&&!1===h&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),
g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],d))};this.buttonDown=function(){g[ON_MOUSE_DOWN]&&!1===h&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],d)};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,c,l)}
function CSpriteLibrary(){var a,c,l,h,g,k;this.init=function(d,f,e){l=c=0;h=d;g=f;k=e;a={}};this.addSprite=function(d,f){a.hasOwnProperty(d)||(a[d]={szPath:f,oSprite:new Image},c++)};this.getSprite=function(d){return a.hasOwnProperty(d)?a[d].oSprite:null};this._onSpritesLoaded=function(){g.call(k)};this._onSpriteLoaded=function(){h.call(k);++l===c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var d in a)a[d].oSprite.oSpriteLibrary=this,a[d].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[d].oSprite.src=a[d].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=640,EDGEBOARD_X=300,EDGEBOARD_Y=0,FONT_GAME="walibi0615bold",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=380,REEL_OFFSET_Y=123,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=10,
WILD_SYMBOL=10,BONUS_SYMBOL=9,NUM_PAYLINES=5,SYMBOL_SIZE=140,SPACE_BETWEEN_SYMBOLS=10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,MIN_BET,MAX_BET,TOTAL_MONEY,MAX_NUM_HOLD,CHICKEN_WIDTH=166,CHICKEN_HEIGHT=187,NUM_PRIZES=3,NUM_SYMBOLS_FOR_BONUS,PERC_WIN_EGG_1,PERC_WIN_EGG_2,PERC_WIN_EGG_3,SOUNDTRACK_VOLUME=.5,WIN_OCCURRENCE,SLOT_CASH,MIN_WIN,BONUS_OCCURRENCE,BONUS_PRIZE=[[5,50,
200],[50,200,500],[100,500,1E3]];function CTweenController(){this.tweenValue=function(a,c,l){return a+l*(c-a)};this.easeLinear=function(a,c,l,h){return l*a/h+c};this.easeInCubic=function(a,c,l,h){h=(a/=h)*a*a;return c+l*h};this.easeBackInQuart=function(a,c,l,h){h=(a/=h)*a;return c+l*(2*h*h+2*h*a+-3*h)};this.easeInBack=function(a,c,l,h){return l*(a/=h)*a*(2.70158*a-1.70158)+c};this.easeOutCubic=function(a,c,l,h){return l*((a=a/h-1)*a*a+1)+c}}
function CToggle(a,c,l){var h,g,k;this._init=function(a,f,e){h=[];g=[];var b=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{on:[0,1],off:[1,2]}});k=s_bAudioActive?createSprite(b,"on",e.width/2/2,e.height/2,e.width/2,e.height):createSprite(b,"off",e.width/2/2,e.height/2,e.width/2,e.height);k.x=a;k.y=f;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",
this.buttonRelease);s_oStage.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.setPosition=function(a,f){k.x=a;k.y=f};this.addEventListener=function(a,f,e){h[a]=f;g[a]=e};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");k.scaleX=1;k.scaleY=1;(s_bAudioActive=!s_bAudioActive)?k.gotoAndStop("on"):k.gotoAndStop("off");h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=
function(){k.scaleX=.9;k.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this._init(a,c,l)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIphone(){return-1!==navigator.userAgent.toLowerCase().indexOf("iphone")?!0:!1}
function getSize(a){var c=a.toLowerCase(),l=window.document,h=l.documentElement;if(void 0===window["inner"+a])a=h["client"+a];else if(window["inner"+a]!=h["client"+a]){var g=l.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var k=l.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+c+":"+h["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";g.appendChild(k);h.insertBefore(g,l.head);
a=7==k["offset"+a]?h["client"+a]:window["inner"+a];h.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),l=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),h=CANVAS_WIDTH*l,l=CANVAS_HEIGHT*l,g=0;l<a?(g=a-l,l+=g,h+=CANVAS_WIDTH/CANVAS_HEIGHT*g):h<c&&(g=c-h,h+=g,l+=CANVAS_HEIGHT/CANVAS_WIDTH*g);var g=a/2-l/2,k=c/2-h/2,d=CANVAS_WIDTH/h;if(k*d<-EDGEBOARD_X||g*d<-EDGEBOARD_Y)l=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*
EDGEBOARD_X)),h=CANVAS_WIDTH*l,l*=CANVAS_HEIGHT,g=(a-l)/2,k=(c-h)/2,d=CANVAS_WIDTH/h;s_iOffsetX=-1*k*d;s_iOffsetY=-1*g*d;0<=g&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",h+"px");$("#canvas").css("height",l+"px");0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",k+"px")}}
function createBitmap(a,c,l){var h=new createjs.Bitmap(a),g=new createjs.Shape;c&&l?g.graphics.beginFill("#fff").drawRect(0,0,c,l):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);h.hitArea=g;return h}function createSprite(a,c,l,h,g,k){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-l,-h,g,k);a.hitArea=c;return a}
function randomFloatBetween(a,c,l){"undefined"===typeof l&&(l=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(l))}function shuffle(a){for(var c=a.length,l,h;0!==c;)h=Math.floor(Math.random()*c),--c,l=a[c],a[c]=a[h],a[h]=l;return a}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var l="",l=10>c?l+("0"+c+":"):l+(c+":");return l=10>a?l+("0"+a):l+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),l=0;l<c.length;l++){var h=c[l].split("=");if(h[0]==a)return h[1]}}
function CTextButton(a,c,l,h,g,k,d){var f,e,b,m,u,n,p,v;this._init=function(a,d,c,h,g,k,l){f=!1;m=[];u=[];v=createBitmap(c);e=c.width;b=c.height;p=new createjs.Text(h,"bold "+l+"px "+g,k);p.textAlign="center";p.shadow=new createjs.Shadow("#000",2,2,2);p.textBaseline="middle";p.lineHeight=24;p.x=c.width/2;p.y=c.height/2;n=new createjs.Container;n.x=a;n.y=d;n.regX=c.width/2;n.regY=c.height/2;n.addChild(v,p);s_oStage.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");
s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){f=!1;v.filters=[];v.cache(0,0,e,b)};this.disable=function(){f=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);v.filters=[new createjs.ColorMatrixFilter(a)];v.cache(0,0,e,b)};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){m[a]=b;u[a]=d};this.buttonRelease=function(){f||(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("press_but"),n.scaleX=1,n.scaleY=1,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(u[ON_MOUSE_UP]))};this.buttonDown=function(){f||(n.scaleX=.9,n.scaleY=.9,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(u[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){n.x=a;n.y=b};this.changeText=function(a){p.text=a};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,c,
l,h,g,k,d);return this}
function CStaticSymbolCell(a,c,l,h){var g=-1,k,d,f,e;this._init=function(a,c,h,g){e=new createjs.Container;e.visible=!1;d=[];for(a=0;a<NUM_SYMBOLS;a++)c=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE),c.stop(),c.x=h,c.y=g,c.on("animationend",this._onAnimEnded,null,!1,{index:a}),e.addChild(c),d[a]=c,d[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
19]}};a=new createjs.SpriteSheet(a);f=new createSprite(a,"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);f.stop();f.x=h;f.y=g;e.addChild(f);s_oStage.addChild(e)};this.unload=function(){s_oStage.removeChild(e)};this.hide=function(){-1<g&&(f.gotoAndStop("static"),f.visible=!1,d[g].gotoAndPlay("static"),e.visible=!1)};this.show=function(a){f.gotoAndPlay("anim");f.visible=!0;for(var c=0;c<NUM_SYMBOLS;c++)d[c].visible=c+1===a?!0:!1;d[a-1].gotoAndPlay("anim");g=a-1;k=d[a-1].spriteSheet.getNumFrames();e.visible=!0};
this._onAnimEnded=function(a,e){d[e.index].currentFrame!==k&&(d[e.index].stop(),setTimeout(function(){d[e.index].gotoAndPlay(1)},100))};this.stopAnim=function(){d[g].gotoAndStop("static");d[g].visible=!1;f.gotoAndStop("static");f.visible=!1};this._init(a,c,l,h)}
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolWin();this._initSymbolAnims();this._initSymbolsOccurence();this._initBonus()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var c={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(c)}};this._initPaylines=
function(){s_aPaylineCombo=[[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}]]};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,
1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,
images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,
height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_9_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[8]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_10_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
14]}};s_aSymbolAnims[9]=new createjs.SpriteSheet(a)};this._initSymbolWin=function(){s_aSymbolWin=[[0,0,1500,2500,5E3],[0,0,1E3,1500,2E3],[0,0,500,1E3,1500],[0,100,250,500,1E3],[0,100,250,500,1E3],[0,50,150,250,500],[0,20,100,200,350],[0,10,50,100,150],[0,10,50,100,150]]};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);
for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;7>a;a++)s_aRandSymbols.push(7);for(a=0;8>a;a++)s_aRandSymbols.push(8);for(a=0;2>a;a++)s_aRandSymbols.push(9);for(a=0;1>a;a++)s_aRandSymbols.push(10)};this._initBonus=function(){s_aEggOccurence=[];var a;for(a=0;a<PERC_WIN_EGG_1;a++)s_aEggOccurence.push(0);for(a=0;a<PERC_WIN_EGG_2;a++)s_aEggOccurence.push(1);for(a=0;a<PERC_WIN_EGG_3;a++)s_aEggOccurence.push(2)};this._init()}var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols,s_aEggOccurence;
function CReelColumn(a,c,l,h){var g,k,d,f,e,b,m,u,n,p,v,w,x,B,r;this._init=function(a,c,h,l){f=d=k=g=!1;u=0;e=a;m=l;b=e<NUM_REELS?e:e-NUM_REELS;p=0;v=MAX_FRAMES_REEL_EASE;n=REEL_STATE_START;w=h;x=w+SYMBOL_SIZE*NUM_ROWS;this.initContainer(c,h)};this.initContainer=function(a,b){r=new createjs.Container;r.x=a;r.y=b;var d=0;B=[];for(var e=0;e<NUM_ROWS;e++){var c=createSprite(s_aSymbolData[s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);c.stop();c.x=
0;c.y=d;r.addChild(c);B[e]=c;d+=SYMBOL_SIZE}s_oStage.addChild(r)};this.unload=function(){s_oStage.removeChild(r)};this.activate=function(){w=r.y;x=w+SYMBOL_SIZE*NUM_ROWS;g=!0};this._setSymbol=function(a){r.removeAllChildren();for(var b=0,d=0;d<a.length;d++){var e=new createSprite(s_aSymbolData[a[d]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);e.stop();e.x=0;e.y=b;r.addChild(e);B[d]=e;b+=SYMBOL_SIZE}};this.setHold=function(a){f=a};this.restart=function(a,b){r.y=w=REEL_START_Y;x=w+SYMBOL_SIZE*NUM_ROWS;this._setSymbol(a);
if(k=b){p=0;v=MAX_FRAMES_REEL_EASE;n=REEL_STATE_STOP;for(var e=0;e<NUM_ROWS;e++)B[e].gotoAndStop("static");d=!0}else for(e=0;e<NUM_ROWS;e++)B[e].gotoAndStop("moving")};this.setReadyToStop=function(){p=0;v=MAX_FRAMES_REEL_EASE;n=REEL_STATE_STOP};this.isReadyToStop=function(){return k};this.isHold=function(){return f};this._updateStart=function(){0===p&&e<NUM_REELS&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("start_reel",{volume:.3}));p++;p>v&&(p=0,v/=2,n++,w=r.y,x=w+SYMBOL_SIZE*
NUM_ROWS);var a=s_oTweenController.easeInBack(p,0,1,v),a=s_oTweenController.tweenValue(w,x,a);r.y=a};this._updateMoving=function(){p++;p>v&&(p=0,w=r.y,x=w+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(p,0,1,v),a=s_oTweenController.tweenValue(w,x,a);r.y=a};this._updateStopping=function(){p++;if(p>=v)g=!1,p=0,v=MAX_FRAMES_REEL_EASE,n=REEL_STATE_START,u=0,k=!1,d&&(d=!1,r.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(p,0,1,v),a=s_oTweenController.tweenValue(w,
x,a);r.y=a}};this.update=function(a){if(!1!==g&&(u++,u>m))if(f)a===e&&(g=!1,s_oGame.stopNextReel(),s_oGame.stopNextReel(),0===e&&s_oGame.increaseReelLoops());else switch(!1===k&&r.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(e,b),n){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,c,l,h)}
function CPreloader(){var a,c,l,h,g,k,d;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("preloader_bar","./sprites/preloader_bar.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();d=new createjs.Container;s_oStage.addChild(d)};this.unload=function(){d.removeAllChildren()};this.hide=function(){var a=
this;setTimeout(function(){createjs.Tween.get(k).to({alpha:1},500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));d.addChild(f);f=s_oSpriteLibrary.getSprite("preloader_bar");l=createBitmap(f);l.x=510;l.y=CANVAS_HEIGHT-171;d.addChild(l);h=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));
h.x=511;h.y=CANVAS_HEIGHT-170;d.addChild(h);a=f.width;g=new createjs.Shape;g.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-170,1,30);d.addChild(g);h.mask=g;c=new createjs.Text("","24px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-148;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";d.addChild(c);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;d.addChild(k)};this.refreshLoader=
function(d){c.text=d+"%";g.graphics.clear();d=Math.floor(d*a/100);g.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-170,d,30)};this._init()}
function CPayTablePanel(){var a,c,l,h,g,k;this._init=function(){k=new createjs.Container;g=createBitmap(s_oSpriteLibrary.getSprite("paytable"));k.addChild(g);a=[];var d,f=424,e=90;a[0]=[];for(d=0;3>d;d++){var b=new createjs.Text("X"+(5-d),"bold 22px "+FONT_GAME,"#ffffff");b.textAlign="center";b.shadow=new createjs.Shadow("#000",1,1,2);b.x=f;b.y=e;b.textBaseline="alphabetic";k.addChild(b);a[0][d]=b;e+=30}f=634;e=90;a[1]=[];for(d=0;3>d;d++)b=new createjs.Text("X"+(5-d),"bold 22px "+FONT_GAME,"#ffffff"),
b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),a[1][d]=b,e+=30;f=864;e=90;a[2]=[];for(d=0;3>d;d++)b=new createjs.Text("X"+(5-d),"bold 22px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),a[2][d]=b,e+=30;f=1098;e=84;a[3]=[];for(d=0;4>d;d++)b=new createjs.Text("X"+(5-d),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",
1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),a[3][d]=b,e+=22;f=430;e=190;a[4]=[];for(d=0;4>d;d++)b=new createjs.Text("X"+(5-d),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),a[4][d]=b,e+=22;f=654;e=190;a[5]=[];for(d=0;4>d;d++)b=new createjs.Text("X"+(5-d),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline=
"alphabetic",k.addChild(b),a[5][d]=b,e+=22;f=874;e=190;a[6]=[];for(d=0;4>d;d++)b=new createjs.Text("X"+(5-d),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),a[6][d]=b,e+=22;f=1096;e=190;a[7]=[];for(d=0;4>d;d++)b=new createjs.Text("X"+(5-d),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),a[7][d]=
b,e+=22;c=[];f=460;e=90;c[0]=[];for(d=0;3>d;d++)b=new createjs.Text(s_aSymbolWin[0][4-d],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[0][d]=b,e+=30;f=670;e=90;c[1]=[];for(d=0;3>d;d++)b=new createjs.Text(s_aSymbolWin[1][4-d],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[1][d]=b,e+=30;f=900;e=90;c[2]=
[];for(d=0;3>d;d++)b=new createjs.Text(s_aSymbolWin[2][4-d],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[2][d]=b,e+=30;f=1130;e=84;c[3]=[];for(d=0;4>d;d++)b=new createjs.Text(s_aSymbolWin[3][4-d],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[3][d]=b,e+=22;f=460;e=190;c[4]=[];for(d=0;4>d;d++)b=new createjs.Text(s_aSymbolWin[4][4-
d],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[4][d]=b,e+=22;f=685;e=190;c[5]=[];for(d=0;4>d;d++)b=new createjs.Text(s_aSymbolWin[5][4-d],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[5][d]=b,e+=22;f=905;e=190;c[6]=[];for(d=0;4>d;d++)b=new createjs.Text(s_aSymbolWin[6][4-d],"21px "+FONT_GAME,"#ffff00"),
b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[6][d]=b,e+=22;f=1130;e=190;c[7]=[];for(d=0;4>d;d++)b=new createjs.Text(s_aSymbolWin[7][4-d],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=f,b.y=e,b.textBaseline="alphabetic",k.addChild(b),c[7][d]=b,e+=22;l=new createjs.Text(TEXT_HELP_WILD,"21px "+FONT_GAME,"#ffff00");l.shadow=new createjs.Shadow("#000",2,2,2);l.textAlign="center";l.lineHeight=
22;l.x=636;l.y=286;k.addChild(l);h=new createjs.Text(TEXT_HELP_BONUS,"21px "+FONT_GAME,"#ffff00");h.shadow=new createjs.Shadow("#000",2,2,2);h.textAlign="center";h.lineHeight=22;h.x=1012;h.y=294;k.addChild(h);k.visible=!1;s_oStage.addChild(k);var m=this;k.on("pressup",function(){m._onExit()})};this.unload=function(){var d=this;k.off("pressup",function(){d._onExit()});s_oStage.removeChild(k);for(var f=0;f<a.length;f++)k.removeChild(a[f]);for(f=0;f<c.length;f++)k.removeChild(c[f])};this.show=function(){k.visible=
!0};this.hide=function(){k.visible=!1};this.resetHighlightCombo=function(){for(var d=0;d<a.length;d++)for(var f=0;f<a[d].length;f++)a[d][f].color="#ffffff",c[d][f].color="#ffff00",createjs.Tween.removeTweens(c[d][f]),c[d][f].alpha=1};this.highlightCombo=function(a,f){8<a||(c[a-1][NUM_REELS-f].color="#ff0000",this.tweenAlpha(c[a-1][NUM_REELS-f],0))};this.tweenAlpha=function(a,c){var e=this;createjs.Tween.get(a).to({alpha:c},200).call(function(){1===c?e.tweenAlpha(a,0):e.tweenAlpha(a,1)})};this._onExit=
function(){s_oGame.hidePayTable()};this.isVisible=function(){return k.visible};this._init()}
function CMenu(){var a,c,l,h,g,k;this._init=function(){l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(l);var d=s_oSpriteLibrary.getSprite("but_play_bg");h=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-60,d,TEXT_PLAY,FONT_GAME,"#ffffff",32);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-d.width/2+20,c=d.height/2+20,g=new CToggle(a,c,d),g.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),null===s_oSoundTrack&&(s_oSoundTrack=createjs.Sound.play("soundtrack",{volume:SOUNDTRACK_VOLUME,loop:-1}));k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},600).call(function(){k.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(d,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(a-d,f+c)};this.unload=function(){h.unload();h=
null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var c,l=0,h=0,g=STATE_LOADING,k,d,f;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;d=new CPreloader};
this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();c=!0};this.soundLoaded=function(){l++;l===h&&(d.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg",
"press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/reels.ogg","reels"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel",6),createjs.Sound.registerSound("./sounds/choose_chicken.ogg","choose_chicken"),createjs.Sound.registerSound("./sounds/press_hold.ogg","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/soundtrack_bonus.ogg",
"soundtrack_bonus"),createjs.Sound.registerSound("./sounds/reveal_egg.ogg","reveal_egg")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/reels.mp3","reels"),createjs.Sound.registerSound("./sounds/reel_stop.mp3","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.mp3",
"start_reel",6),createjs.Sound.registerSound("./sounds/choose_chicken.mp3","choose_chicken"),createjs.Sound.registerSound("./sounds/press_hold.mp3","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/soundtrack_bonus.mp3","soundtrack_bonus"),createjs.Sound.registerSound("./sounds/reveal_egg.mp3","reveal_egg")),h+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.jpg");s_oSpriteLibrary.addSprite("but_play_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but",
"./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but","./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg","./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hit_area_col","./sprites/hit_area_col.png");s_oSpriteLibrary.addSprite("hold_col","./sprites/hold_col.png");
s_oSpriteLibrary.addSprite("bonus_bg","./sprites/bonus_bg.jpg");s_oSpriteLibrary.addSprite("chicken","./sprites/chicken.png");s_oSpriteLibrary.addSprite("hit_area_chicken","./sprites/hit_area_chicken.png");s_oSpriteLibrary.addSprite("egg","./sprites/egg.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+
a,"./sprites/payline_"+a+".png");h+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){l++;d.refreshLoader(Math.floor(l/h*100));l===h&&(d.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoGame=function(){f=new CGame(k);g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=
!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&f.update();s_oStage.update(a)}};s_oMain=this;k=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null;TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_MONEY="SCORE";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";TEXT_SPIN="SPIN";TEXT_WIN="WIN";TEXT_HOLD="HOLD";TEXT_HELP_WILD="JOLLY SYMBOL\nCAN REPLACE\nANY OTHER\nSYMBOL TO\nMAKE UP A\nCOMBO";TEXT_HELP_BONUS="3 OR MORE\nMR CHICKEN\nLET YOU PLAY\nTHE BONUS\nGAME!";
TEXT_CONGRATULATIONS="Congratulations!";TEXT_MSG_SHARE1="You collected <strong>";TEXT_MSG_SHARE2=" points</strong>!<br><br>Share your score with your friends!";TEXT_MSG_SHARING1="My score is ";TEXT_MSG_SHARING2=" points! Can you do better?";
function CInterface(a,c,l){var h,g,k,d,f,e,b,m,u,n,p,v,w,x,B,r,A;this._init=function(a,c,l){var q=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-q.width/2-20;g=q.height/2+20;b=new CGfxButton(h,g,q,!0);b.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=b.getX()-q.width,d=q.height/2+20,p=new CToggle(k,d,s_oSpriteLibrary.getSprite("audio_icon")),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("spin_but");m=new CTextButton(1090+
q.width/2,CANVAS_HEIGHT-q.height/2,q,"",FONT_GAME,"#ffde00",22);m.addEventListener(ON_MOUSE_UP,this._onSpin,this);q=s_oSpriteLibrary.getSprite("info_but");u=new CTextButton(328+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_INFO,FONT_GAME,"#ffffff",30);u.addEventListener(ON_MOUSE_UP,this._onInfo,this);q=s_oSpriteLibrary.getSprite("but_lines_bg");n=new CTextButton(494+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_LINES,FONT_GAME,"#ffffff",30);n.addEventListener(ON_MOUSE_UP,this._onAddLine,this);q=s_oSpriteLibrary.getSprite("coin_but");
v=new CTextButton(680+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_COIN,FONT_GAME,"#ffffff",30);v.addEventListener(ON_MOUSE_UP,this._onBet,this);q=s_oSpriteLibrary.getSprite("but_maxbet_bg");w=new CTextButton(866+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_MAX_BET,FONT_GAME,"#ffffff",30);w.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);B=new createjs.Text(TEXT_MONEY+"\n"+l.toFixed(2),"30px "+FONT_GAME,"#ffde00");B.x=450;B.y=46;B.textBaseline="alphabetic";B.lineHeight=28;B.textAlign="center";s_oStage.addChild(B);
A=new createjs.Text(NUM_PAYLINES,"26px "+FONT_GAME,"#ffffff");A.x=584;A.y=CANVAS_HEIGHT-65;A.shadow=new createjs.Shadow("#000",2,2,2);A.textAlign="center";A.textBaseline="alphabetic";s_oStage.addChild(A);x=new createjs.Text(a.toFixed(2),"26px "+FONT_GAME,"#ffffff");x.x=776;x.y=CANVAS_HEIGHT-65;x.shadow=new createjs.Shadow("#000",2,2,2);x.textAlign="center";x.textBaseline="alphabetic";s_oStage.addChild(x);r=new createjs.Text(TEXT_BET+": "+c.toFixed(2),"26px "+FONT_GAME,"#ffffff");r.x=980;r.y=CANVAS_HEIGHT-
65;r.shadow=new createjs.Shadow("#000",2,2,2);r.textAlign="center";r.textBaseline="alphabetic";s_oStage.addChild(r);q=s_oSpriteLibrary.getSprite("bet_but");f=[];a=new CBetBut(334+q.width/2,282+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);f[0]=a;a=new CBetBut(334+q.width/2,180+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);f[1]=a;a=new CBetBut(334+q.width/2,432+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,
this._onBetLineClicked,this,3);f[2]=a;a=new CBetBut(334+q.width/2,114+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);f[3]=a;a=new CBetBut(334+q.width/2,502+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);f[4]=a;e=[];for(q=0;q<NUM_PAYLINES;q++)a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("payline_"+(q+1))),a.x=0,a.y=0,a.visible=!1,s_oStage.addChild(a),e[q]=a;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=
function(){b.unload();b=null;m.unload();m=null;u.unload();u=null;n.unload();n=null;v.unload();v=null;w.unload();w=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;for(var a=0;a<NUM_PAYLINES;a++)f[a].unload();s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(k-a,c+d);b.setPosition(h-a,c+g)};this.refreshMoney=function(a){B.text=TEXT_MONEY+"\n"+a.toFixed(2)};this.refreshBet=function(a){x.text=
a.toFixed(2)};this.refreshTotalBet=function(a){r.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){A.text=a;for(var b=0;b<NUM_PAYLINES;b++)b<a?(f[b].setOn(),e[b].visible=!0):f[b].setOff();setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)e[a].visible=!1},1E3)};this.resetWin=function(){m.changeText("")};this.refreshWinText=function(a){m.changeText(TEXT_WIN+"\n"+a.toFixed(2))};this.showLine=function(a){e[a-1].visible=!0};this.hideLine=function(a){e[a-1].visible=!1};this.hideAllLines=
function(){for(var a=0;a<NUM_PAYLINES;a++)e[a].visible=!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)f[b].disable(a)};this.enableGuiButtons=function(){m.enable();w.enable();v.enable();n.enable();u.enable()};this.enableSpin=function(){m.enable();w.enable()};this.disableSpin=function(){m.disable();w.disable()};this.disableGuiButtons=function(){m.disable();w.disable();v.disable();n.disable();u.disable()};this._onBetLineClicked=function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};
this._onExit=function(){s_oGame.onExit()};this._onSpin=function(){s_oGame.onSpin()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oInterface=this;this._init(a,c,l);return this}var s_oInterface=null;
function CGfxButton(a,c,l,h){var g,k,d,f,e,b,m;this._init=function(a,b,c,h){g=!1;f=[];e=[];m=createBitmap(c);m.x=a;m.y=b;k=c.width;d=c.height;m.regX=c.width/2;m.regY=c.height/2;!1!==h&&s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this.enable=function(){g=!1;m.filters=[];m.cache(0,0,k,d)};this.disable=function(){g=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
m.filters=[new createjs.ColorMatrixFilter(a)];m.cache(0,0,k,d)};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){f[a]=b;e[a]=d};this.addEventListenerWithParams=function(a,d,c,h){f[a]=d;e[a]=c;b=h};this.buttonRelease=function(){g||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),m.scaleX=1,m.scaleY=1,f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(e[ON_MOUSE_UP],b))};this.buttonDown=function(){g||
(m.scaleX=.9,m.scaleY=.9,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],b))};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this.getSprite=function(){return m};this._init(a,c,l,h);return this}
function CGame(a){var c=!1,l,h,g,k,d,f,e,b,m,u,n,p,v,w=0,x,B,r,A,y,F,z,q,G,E,D,L,H,I,J,t,C=null,K;this._init=function(){g=GAME_STATE_IDLE;l=!0;_iNumSpinCont=v=f=k=0;F=[0,1,2,3,4];d=F[0];e=NUM_PAYLINES;p=TOTAL_MONEY;u=MIN_BET;n=u*e;z=[];for(var a=0;a<NUM_ROWS;a++){z[a]=[];for(var b=0;b<NUM_REELS;b++)z[a][b]=0}s_oTweenController=new CTweenController;I=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(I);this._initReels();J=createBitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oStage.addChild(J);
this._initStaticSymbols();this._initHitAreaColumn();t=new CInterface(u,n,p);K=new CBonusPanel;C=new CPayTablePanel;p<n&&t.disableSpin();c=!0};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.stop(),s_oSoundTrack=null;s_oStage.removeChild(I);s_oStage.removeChild(J);t.unload();C.unload();for(var a=0;a<r.length;a++)r[a].unload();for(a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)A[a][b].unload();K.unload()};this._initReels=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y,
d=0;r=[];for(var c=0;c<NUM_REELS;c++)r[c]=new CReelColumn(c,a,b,d),r[c+NUM_REELS]=new CReelColumn(c+NUM_REELS,a,b+SYMBOL_SIZE*NUM_ROWS,d),a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS,d+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y;A=[];for(var d=0;d<NUM_ROWS;d++){A[d]=[];for(var c=0;c<NUM_REELS;c++){var e=new CStaticSymbolCell(d,c,a,b);A[d][c]=e;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;b+=SYMBOL_SIZE}};this._initHitAreaColumn=function(){D=[];E=[];for(var a=
376,b=120,d=0;d<NUM_REELS;d++){var c=createBitmap(s_oSpriteLibrary.getSprite("hold_col"));c.x=a;c.y=b;c.visible=!1;s_oStage.addChild(c);a+=150;E.push(c);D[d]=!1}q=[];G=[];for(var a=381,b=108,d=s_oSpriteLibrary.getSprite("hit_area_col"),c=0;c<NUM_REELS;c++){var e=new createjs.Text(TEXT_HOLD,"22px "+FONT_GAME,"#ffffff");e.visible=!1;e.x=a+d.width/2;e.y=b+d.height-20;e.shadow=new createjs.Shadow("#000",1,1,2);e.textAlign="center";s_oStage.addChild(e);q[c]=e;e=new CGfxButton(a+d.width/2,b+d.height/2,
d);e.setVisible(!1);e.addEventListenerWithParams(ON_MOUSE_UP,this._onHitAreaCol,this,{index:c});a+=150;G.push(e)}};this.generateFinalSymbols=function(){for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)!1===r[b].isHold()&&(z[a][b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]);y=[];for(a=x=0;a<e;a++){var b=s_aPaylineCombo[a],d=[],c=z[b[0].row][b[0].col];if(c!==BONUS_SYMBOL){var f=1,g=1;for(d.push({row:b[0].row,col:b[0].col,value:z[b[0].row][b[0].col]});c===WILD_SYMBOL&&g<NUM_REELS;)f++,
c=z[b[g].row][b[g].col],d.push({row:b[g].row,col:b[g].col,value:z[b[g].row][b[g].col]}),g++;for(;g<b.length;g++)if(z[b[g].row][b[g].col]===c||z[b[g].row][b[g].col]===WILD_SYMBOL){if(z[b[g].row][b[g].col]===BONUS_SYMBOL)break;f++;d.push({row:b[g].row,col:b[g].col,value:z[b[g].row][b[g].col]})}else break;0<s_aSymbolWin[c-1][f-1]&&(x+=s_aSymbolWin[c-1][f-1],y.push({line:a+1,amount:s_aSymbolWin[c-1][f-1],num_win:f,value:c,list:d}))}}h=!1;w=0;d=[];for(a=0;a<NUM_ROWS;a++)for(b=0;b<NUM_REELS;b++)z[a][b]===
BONUS_SYMBOL&&(d.push({row:a,col:b,value:z[a][b]}),w++);w>=NUM_SYMBOLS_FOR_BONUS&&(y.push({line:-1,amount:0,num_win:w,value:BONUS_SYMBOL,list:d}),5<w&&(w=5),h=!0);return 0<y.length?!0:!1};this._generateRandSymbols=function(){for(var a=[],b=0;b<NUM_ROWS;b++)a[b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)];return a};this.reelArrived=function(a,b){if(k>MIN_REEL_LOOPS)if(d===b){if(!1===r[a].isReadyToStop()){var c=a;a<NUM_REELS?(c+=NUM_REELS,r[c].setReadyToStop(),r[a].restart([z[0][a],
z[1][a],z[2][a]],!0)):(c-=NUM_REELS,r[c].setReadyToStop(),r[a].restart([z[0][c],z[1][c],z[2][c]],!0))}}else r[a].restart(this._generateRandSymbols(),!1);else r[a].restart(this._generateRandSymbols(),!1),0===a&&k++};this.increaseReelLoops=function(){k+=2};this.stopNextReel=function(){f++;0===f%2&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reel_stop",{volume:.3}),d=F[f/2],f===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||L.stop();f=k=0;d=F[0];for(var a=0;a<NUM_REELS;a++)D[a]=!1,E[a].visible=!1,r[a].setHold(!1),r[a+NUM_REELS].setHold(!1);v=0;if(0<y.length){for(var c=0;c<y.length;c++){C.highlightCombo(y[c].value,y[c].num_win);-1!==y[c].line&&t.showLine(y[c].line);for(var e=y[c].list,a=0;a<e.length;a++)A[e[a].row][e[a].col].show(e[a].value)}x*=u;p+=x;SLOT_CASH-=x;0<x&&(t.refreshMoney(p),t.refreshWinText(x));b=0;g=GAME_STATE_SHOW_ALL_WIN;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)H=createjs.Sound.play("win")}else l&&
this.enableColumnHitArea(),g=GAME_STATE_IDLE;!1===l&&(l=!0);!1===h&&(t.disableBetBut(!1),t.enableGuiButtons());p<n&&t.disableSpin();_iNumSpinCont++;_iNumSpinCont===B&&(_iNumSpinCont=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",p)};this.hidePayTable=function(){C.hide()};this._showWin=function(){var a;if(0<m){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||H.stop();-1!==y[m-1].line&&(a=y[m-1].line,t.hideLine(a));a=y[m-1].list;for(var b=0;b<a.length;b++)A[a[b].row][a[b].col].stopAnim()}m===
y.length&&(m=0);-1!==y[m].line&&(a=y[m].line,t.showLine(a));a=y[m].list;for(b=0;b<a.length;b++)A[a[b].row][a[b].col].show(a[b].value);m++};this._hideAllWins=function(){for(var a=0;a<y.length;a++)for(var c=y[a].list,d=0;d<c.length;d++)A[c[d].row][c[d].col].stopAnim();t.hideAllLines();m=b=0;b=TIME_SHOW_WIN;g=GAME_STATE_SHOW_WIN;h&&K.show(w)};this.enableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)q[a].visible=!0,G[a].setVisible(!0)};this.disableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)q[a].visible=
!1,G[a].setVisible(!1)};this.activateLines=function(a){e=a;this.removeWinShowing();n=a=u*e;t.refreshTotalBet(n);t.refreshNumLines(e);a>p?t.disableSpin():t.enableSpin()};this.addLine=function(){e===NUM_PAYLINES?e=1:e++;var a=u*e;n=a;t.refreshTotalBet(n);t.refreshNumLines(e);a>p?t.disableSpin():t.enableSpin()};this.changeCoinBet=function(){var a=Math.floor(100*(u+.05))/100;a>MAX_BET?(u=MIN_BET,n=u*e,t.refreshBet(u),t.refreshTotalBet(n),a=n):(a*=e,u+=.05,u=Math.floor(100*u)/100,n=a,t.refreshBet(u),t.refreshTotalBet(n));
a>p?t.disableSpin():t.enableSpin()};this.onMaxBet=function(){var a=MAX_BET;e=NUM_PAYLINES;a*=e;u=MAX_BET;n=a;t.refreshBet(u);t.refreshTotalBet(n);t.refreshNumLines(e);a>p?t.disableSpin():(t.enableSpin(),this.onSpin())};this._onHitAreaCol=function(a){a=a.index;!0===D[a]?(D[a]=!1,E[a].visible=!1,q[a].visible=!0,v--,r[a].setHold(!1),r[a+NUM_REELS].setHold(!1)):v<MAX_NUM_HOLD&&(D[a]=!0,v++,E[a].visible=!0,q[a].visible=!1,r[a].setHold(!0),r[a+NUM_REELS].setHold(!0),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("press_hold"));l=!1};this.removeWinShowing=function(){C.resetHighlightCombo();t.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)A[a][b].hide();for(a=0;a<r.length;a++)r[a].activate();g=GAME_STATE_IDLE};this.endBonus=function(a){p+=a;t.refreshMoney(p);SLOT_CASH-=a;t.disableBetBut(!1);t.enableGuiButtons()};this.onSpin=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)H&&H.stop(),L=createjs.Sound.play("reels",{volume:.3});this.disableColumnHitArea();t.disableBetBut(!0);
this.removeWinShowing();MIN_WIN=s_aSymbolWin[0][s_aSymbolWin[0].length-1];for(var a=0;a<s_aSymbolWin.length;a++)for(var b=s_aSymbolWin[a],c=0;c<b.length;c++)0!==b[c]&&b[c]<MIN_WIN&&(MIN_WIN=b[c]);MIN_WIN*=u;p-=n;t.refreshMoney(p);SLOT_CASH+=n;if(SLOT_CASH<MIN_WIN){do a=this.generateFinalSymbols();while(!0===a)}else if(Math.floor(100*Math.random())>WIN_OCCURRENCE){do a=this.generateFinalSymbols();while(!0===a)}else if(SLOT_CASH<BONUS_PRIZE[0][0]){do a=this.generateFinalSymbols();while(!1===a||x*u>
SLOT_CASH||h)}else if(Math.floor(100*Math.random())>BONUS_OCCURRENCE){do a=this.generateFinalSymbols();while(!1===a||x*u>SLOT_CASH||h)}else{do a=this.generateFinalSymbols(),b=0,h&&(b=w-3);while(!1===a||x*u>SLOT_CASH||!1===h||BONUS_PRIZE[b][0]>SLOT_CASH)}t.hideAllLines();t.disableGuiButtons();g=GAME_STATE_SPINNING};this.onInfoClicked=function(){g!==GAME_STATE_SPINNING&&(C.isVisible()?C.hide():C.show())};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",
{img:"200x200.jpg",title:TEXT_CONGRATULATIONS,msg:TEXT_MSG_SHARE1+p+TEXT_MSG_SHARE2,msg_share:TEXT_MSG_SHARING1+p+TEXT_MSG_SHARING2})};this.getState=function(){return g};this.update=function(){if(!1!==c)switch(g){case GAME_STATE_SPINNING:for(var a=0;a<r.length;a++)r[a].update(d);break;case GAME_STATE_SHOW_ALL_WIN:b+=s_iTimeElaps;b>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:b+=s_iTimeElaps,b>TIME_SHOW_WIN&&(b=0,this._showWin())}};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;
SLOT_CASH=a.slot_cash;BONUS_OCCURRENCE=a.bonus_occurrence;MIN_REEL_LOOPS=a.min_reel_loop;REEL_DELAY=a.reel_delay;TIME_SHOW_WIN=a.time_show_win;TIME_SHOW_ALL_WINS=a.time_show_all_wins;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MAX_NUM_HOLD=a.max_hold;PERC_WIN_EGG_1=a.perc_win_egg_1;PERC_WIN_EGG_2=a.perc_win_egg_2;PERC_WIN_EGG_3=a.perc_win_egg_3;NUM_SYMBOLS_FOR_BONUS=a.num_symbol_bonus;B=a.num_spin_ads_showing;new CSlotSettings;this._init()}var s_oGame,s_oTweenController;